### ISSUE TITLE
Can't close an Apple Pay component

### ISSUE THREAD

**Issue by iszhuravlev** [Adyen/adyen-react-native#109]
Hi, we're having an issue, which looks exactly like this one https://github.com/Adyen/adyen-ios/issues/517, except I'm not quite sure if there's a way to manipulate the Apple Pay component.

The "Cancel" button doesn't work, and if I press on the dark overlay, the component goes down but I get stuck in DropIn unable to close it.

1. Open DropIn
2. Press on the apple pay option
3. Press on " Pay" - another bottom sheet gets open
4. Try pressing "Cancel" - no result
5. Press on the empty space above the sheet - it's closed

Result: I see the component with " Pay" again, but can't close it.

Device: iPhone SE (1st)

**Comment by descorp** [comment]
Hey @iszhuravlev 

Thank you for reporting this!
I was able to reproduce this bug, will keep you posted..

**UPD**

Apparently it was broken for quite some time on Native iOS.
Will keep you posted

**Comment by descorp** [comment]
Fixed on [native iOS](https://github.com/Adyen/adyen-ios/pull/1111)
Will update to latest v4 when released

**Comment by iszhuravlev** [comment]
Hi @descorp, is there an approximate release date with this fix? It's just to know where we can go live with the DropIn.

**Comment by descorp** [comment]
[v4.10.3](https://github.com/Adyen/adyen-ios/releases/tag/4.10.3) is released.
We will update RN shortly

**Comment by descorp** [comment]
**Beta-8** is released with the fix.
Please confirm it resolves the problem 💚
