### ISSUE TITLE
holderNameRequired not working.

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#11]
In native SDK, there is a param named holderNameRequired, that will hide/show the cardholder name field in the card component, but this is not working in react-native.

**To Reproduce**
1. Add this **holderNameRequired** param value 
1. Go to the example app
2. Click on Open DropIn
3. Click on Card Payment Method
4. See field is not working as per the set value of **holderNameRequired**

**Expected behavior**
**holderNameRequired** if the value is set to true, the holder name should be visible in the card component, hidden in another case.

**Screenshots**

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/18231674/170369204-9ce29dd2-6e5a-4ff2-ab77-9898b983a308.png)

**Producible on Devices**
 - Platform: iOS & Android both
 - Device: Any
 - OS: Any
 - Version: 1.0.0 [BETA.3]

**Comment by descorp** [comment]
Fixed with 1.0.0-beta.4 release
