### ISSUE TITLE
Card component doesn't store card details

### ISSUE THREAD

**Issue by iszhuravlev** [Adyen/adyen-react-native#111]
**Describe the bug**
Hi, looking at the README, I thought that the Card component can store client's card details by default. I don't know if I'm missing something or if it's supposed to work in "test" environment, so I'll also attach the config that I provide to AdyenCheckout.
```
 {
  "skipListWhenSinglePaymentMethod": true,
  "returnUrl": <returnUrl>,
  "holderNameRequired": true,
  "amount": {
    "currency": "EUR",
    "value": 2450
  },
  "countryCode": "DE",
  "reference": <reference>,
  "environment": "test",
  "clientKey": <clientKey>,
  "shopperReference": <shopperReference>
}
```

**To Reproduce**
1. Open the dropIn
2. Press "Pay with card"
3. Enter all the details
4. Switch "Remember for next time" on
5. Make a payment

**Expected behavior**
When I make a next payment with card, my card details are saved.

**Actual behavior**
I have to enter the details again.

**Device:**
 - iPhone 13 Simulator
 - OS: iOS 15.2

**Comment by descorp** [comment]
Hey @iszhuravlev 

For tokenisation to work your `/payment` request must contain :

- [shopperReference](https://docs.adyen.com/api-explorer/Checkout/69/post/payments#request-shopperReference) 
- [storePaymentMethod](https://docs.adyen.com/api-explorer/Checkout/69/post/payments#request-storePaymentMethod) (set by a DropIn/component)

> When I make a next payment with card, my card details are saved.

Did you re-request `/paymentMethods`? New "stored" card should be in a list of "storedPaymentMethods"

---

If you still can't see a stored card - try to set [recurringProcessingModel](https://docs.adyen.com/api-explorer/Checkout/69/post/payments#request-recurringProcessingModel) like described in [our Docs](https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens#save-for-one-off).
If still no luck - please reach to a [support team](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420), they will help with configuration of your Customer Area.

**Comment by iszhuravlev** [comment]
Hi @descorp,

Thank you for your help, seems like we don't pass `storePaymentMethod` from the client. I'll try and let you know!

**Comment by iszhuravlev** [comment]
@descorp Works now, thank you again! Closing this thread then.

**Comment by rosenpost** [comment]
@descorp I also have a similar issue though I am able to correctly store cards and get them from the the API call as a       `storedPaymentMethods` array. However, after I pass an object with the following format to dropin, I do not see the stored payment methods being rendered: { paymentMethods: [...], storedPaymentMethods: [...]}. The dropin works with new payment methods. I am also using a test environment. Thank you.
