### ISSUE TITLE
Support for sessions

### ISSUE THREAD

**Issue by todibbang** [Adyen/adyen-react-native#113]
I have built a react website which uses the 'adyen/adyen-react' library to offer Adyen payments. 
I more specifically use the sessions-API to facilitate payments which the 'adyen/adyen-react' does support.
I'm now in the process of building an app-based version of the website using React Native.
It does not look as if this react-native library supports sessions though?
How would you suggest that I proceed in adding Adyen support?
Is the sessions-API the wrong approach?
I'll look forward to your reply.

**Comment by descorp** [comment]
Hey @todibbang 

> I have built a react website which uses the 'adyen/adyen-react' library to offer Adyen payments.

Do you mean [adyen/adyen-web](https://github.com/Adyen/adyen-web)? 
This is interesting use case. We do not expect `adyen/adyen-react` to work for web 🤔

> Is the sessions-API the wrong approach?

Sessions are simple and recommended way of integration on Web and iOS. 
Android is not yet supporting it, that is why React Native is also not yet supporting it.

> How would you suggest that I proceed in adding Adyen support?

There is no ideal solution. I can only suggest:
A) wait till we deliver Sessions on React Native(Q3 2023 is my best guess)
B) implement [advanced flow](https://docs.adyen.com/online-payments/web-drop-in/additional-use-cases/advanced-flow) for React Native. You don't have to change your existing implementation.
C) implement [native iOS](https://github.com/Adyen/adyen-ios) with Sessions and wait till native Android v5 delivered.

**Comment by mg-dominicdrysdale** [comment]
hello @descorp, any update on delivering Sessions for React Native?

**Comment by descorp** [comment]
Hey @pof-dominicdrysdale 

We are starting work on adopting v5 on Android for `2.0.0`
Delivery time - Q4 2023.

Keep an eye on our releases :)

**Comment by daniel-johns-99** [comment]
Hi @descorp , how are we tracking for this release!

**Comment by camil-adyen** [comment]
Support for sessions has been released with the [v2-beta](https://github.com/Adyen/adyen-react-native/releases/tag/2.0.0-beta.1) release. Therefore, I'm closing this issue.
