### ISSUE TITLE
Support for MobilePay, Swish & Vipps

### ISSUE THREAD

**Issue by todibbang** [Adyen/adyen-react-native#114]
Hi - does the current solution support the payment methods: MobilePay, Swish & Vipps.
If not, when are they (if at all) planned to be added?
I'll look forward to your response.
(I'm unable to change the tag to a 'question')

**Comment by descorp** [comment]
Hey @todibbang 

Those are considered a redirect payment methods and supported on current solution.

On iOS:
**Swish** & **Vipps** definitely works on iOS.
**MobilePay** I haven't tried personally, but I assume it works as well.

On Android:
I haven't tested it personally, but I assume it should work as well.
Will keep you posted! 

If you can verify on your test environment - would be great 💚

**Comment by descorp** [comment]
**UPD**

**Vipps** and **Swish** works on Android React Native. **MobilePay** expected to work as well

**Comment by descorp** [comment]
Hey @todibbang 

Hope this answer is sufficient.
I am going to close this ticket due to a lack of activity

**Comment by todibbang** [comment]
Hi @descorp. Sorry for the slow response and thank you for your reply.
I am working in an iOS test environment. I havn't yet implemented a "standard-payments" api implementation to replace the "sessions" based api implementation which I currently have. Once I have this implemented I'll give the various methods a test. But it sounds like that is going to work which is great news. 
I understand that it is work in progress, but the reason for my question was that "adyen-react-native/src/ComponentMap.js" doesn't have these payment methods listed in the NATIVE_COMPONENTS array, which is different from the componentsMap found in the "@adyen/adyen-web" library. So thank you for clearing that up for me :-)

**Comment by descorp** [comment]
Hey @todibbang 

> "adyen-react-native/src/ComponentMap.js" doesn't have these payment methods listed

This is a fair question 🤔
At the moment `NATIVE_COMPONENTS` array only listing paymentMethods that require shopper's input collected by SDK directly (input entered in a native form/list), everything else is treated as "instant payment" - payment data will be generated "on a spot" and in majority of cases will trigger web/app redirect

[AdyenNativeModules.js](https://github.com/Adyen/adyen-react-native/blob/develop/src/AdyenNativeModules.js#L63-L67):
```js
  if (NATIVE_COMPONENTS.includes(type)) {
    return { nativeComponent: AdyenDropIn, paymentMethod: paymentMethod };
  }

  return { nativeComponent: AdyenInstant, paymentMethod: paymentMethod };
```

---

**Rule of thumb**: if you see it in `/paymentMethods` but not in  `NATIVE_COMPONENTS`, it is redirect and going to be treated by `AdyenInstant` 🙂

**Comment by todibbang** [comment]
Amazing, thank you for this! 😁
