### ISSUE TITLE
Can't handle redirect from Klarna on Android

### ISSUE THREAD

**Issue by iszhuravlev** [Adyen/adyen-react-native#116]
**Describe the bug**
Hi, I suppose, this one will definitely turn into a "question", but I'm confused with the behaviour of the Android implementation, so let me please describe the problem. I would really appreciate any feedback, and from my side I'll give you any piece of code that you might need to understand the context.

When I open the Klarna website and finish the payment, it redirects me back to the app with the `redirectResult` which is correct, but:

1. The app handles the url that I provided the AdyenCheckout with - not the one that should overwrite it. To be clear: app receives `myappshceme://my-route-name` instead of `adyencheckout://com.myapp.id`. Reading the docs I thought it must be the opposite
2. Even when I parse the link and retrieve the `redirectResult` hash, seems like due to the deeplink handling the whole state of the page gets cleared. - That can be my bad, I may handle it wrong. If you faced anything like that before, can you please share your thoughts?

**To Reproduce**
1. Open the dropIn
3. Click on Pay with Klarna (or any other "browser" payment method, I suppose)
4. Go through all the steps on the web page to complete the purchase

**Expected behavior**
I thought that `onProvide` would be fired automatically like on iOS.
Also, from the point one: don't really understand what link is used to redirect me back.

**Comment by iszhuravlev** [comment]
@descorp Sorry it was my mistake indeed, closing this.

**Comment by descorp** [comment]
Hey @iszhuravlev 

I am sorry - I forgot to press "Comment" 😅

What was the confusion?
Are you using DropIn or Component?

On iOS you can provide one Custom Url scheme for the whole app and both DropIn and Component will use it. Hence, SDK have no need to override `redirectUrl` on `didSubmit`.
On Android - redirect is Activity-based. DropIn Activity (also used for Cards, Sepa, iDeal etc) have own URL configured - `adyencheckout://`; Instant Payments(e.x. Klarna, PayPal) doesn't have own activity and [must be configured](https://github.com/Adyen/adyen-react-native#for-standalone-components) on `MainActivity` of your app. On both cases SDK will override `redirectUrl` on `didSubmit` accordingly.

**Comment by iszhuravlev** [comment]
Hey @descorp 

No worries, it made me double-check what I'm doing. 
I wrote this because I saw that the `redirectUrl` is not overridden, but then it was fine - it might've been some kind of caching issue.

Anyway, everything's good now, thank you!
