### ISSUE TITLE
Skip List when single payment method is not working.

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#12]
In native SDK, there is a param named skipListWhenSinglePaymentMethod, that will skip showing the payment methods list if the list contains only one component, but this is not working in react-native.

**Steps to reproduce the behavior:**
Add this skipListWhenSinglePaymentMethod param value in config.
Go to the example app
Click on Open DropIn
The payment methods list will show even if we have only one payment method

**Expected behavior:**
if the **skipListWhenSinglePaymentMethod** value is set to true, that will skip showing the payment methods list if the list contains only one component,

**Producible on Devices:**
Platform: iOS & Android both
Device: Any
OS: Any
Version: 1.0.0 [BETA.3]

**Comment by ahsan-lebara** [comment]
@descorp It's partially working, working for native payment view like a credit card, but it's not working for web redirect payment methods like PayPal, giropay, etc.

**Comment by descorp** [comment]
Hey @ahsan-lebara 

Indeed, our native components show single list element in this case. 
#thisisnotabugbutfeature 😄

We are working on support for standalone Action Handler, so you can make [\payment](https://docs.adyen.com/api-explorer/#/CheckoutService/v69/post/payments__example_payments-giropay) request for any redirect ( aka "instant") payment method and then handle `action` via SDK.

**Comment by descorp** [comment]
Feature added on [1.0.0-beta5](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.5)

* add ability call any PM with UI (card, SEPA, iDEAL. etc) directly. It uses Drop-In's skipPaymentMathodListing "under the hood".
* add ability to call any other (UI-less) PM (paypal, sofas, klarna etc) directly
