### ISSUE TITLE
Show/hide "Remember for next time" not working

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#14]
In native SDK, there is a param named showStorePaymentField, that will hide/show "Remember for next time" in the card component, but this is not working in react-native.

**To Reproduce**
1. Add this **showStorePaymentField** param value in config
2. Go to the example app
3. Click on Open DropIn
4. Card component will show "Remember for next time"  always, irrespective of the value set to **showStorePaymentField**

**Expected behavior**
**showStorePaymentField** if the value is set to false, the "Remember for next time" field should hide from the card component

**Screenshots**

![image](https://user-images.githubusercontent.com/18231674/170436995-c8fc60cb-650b-4ef2-ae3b-0af1670a82f0.png)

**Producible on Devices**
 - Platform: iOS & Android both
 - Device: Any
 - OS: Any
 - Version: 1.0.0 [BETA.3]

**Comment by descorp** [comment]
Fixed with 1.0.0-beta.4 release
