### ISSUE TITLE
Localisation is partially working

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#15]
If locale value is set in config other than en, localization is not working partially.

**To Reproduce**
1. Add any locale value other than en
2. Click on Open DropIn
3. Click on Card Payment Method
4. See all fields are not translated.

**Expected behavior**
All fields of drop-in and components should be translated.

**Screenshots**
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/18231674/170373105-13d4aaf8-2add-4329-b696-3c5aad161f1a.png)
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/18231674/170373254-e215e6e6-7a2d-4c80-adc0-01c8cfdb2026.png)

**Producible on Devices**
 - Platform: iOS & Android both
 - Device: Any
 - OS: Any
 - Version: 1.0.0 [BETA.3]

**Comment by descorp** [comment]
@iranaahsanali 

Ability to enforce specific locale is not yet supported, but already in our backlog.
By providing locale in configuration you are setting localisation of PaymentMethod names and external URLs.

**Comment by descorp** [comment]
Hey @iranaahsanali 

I did small research and it seems there is massive misalignments between native iOS and Android 😅

**iOS:**
uses device locale for translation. To activate specific locale add it to the list of "Localizations" in your App's Info.plist

![Screenshot 2022-08-17 at 15 20 51](https://user-images.githubusercontent.com/2648655/185144794-d42d805a-f325-43a8-b5f6-507b14a8b495.png)

**Android:**
apply locale from `shopperLocale`.

**For now:**

You can activate necessary locales for iOS and for Android send system's locale to `shopperLocale`:

```js

import { Platform, NativeModules } from 'react-native'

const deviceLanguage =
      Platform.OS === 'ios'
        ? NativeModules.SettingsManager.settings.AppleLocale ||
          NativeModules.SettingsManager.settings.AppleLanguages[0] //iOS 13
        : NativeModules.I18nManager.localeIdentifier;

...

  shopperLocale: deviceLanguage.replace("_", "-")
```

**Comment by bbialas** [comment]
Any news about this? Would be great to have working translations on iOS.

**Comment by descorp** [comment]
Hey @bbialas 

"enforced locale" was added on iOS v5.

We are working on React Native 2.0.0 that would incorporate v5 version of iOS and Android SDK.
Stay tuned!

**Comment by gunnartorfis** [comment]
Hey @descorp 
I just noticed that this is still unimplemented on the 2.0 beta - are there still plans on fixing this before the 2.0 stable release?

**Comment by descorp** [comment]
PR #363

**Comment by descorp** [comment]
Released on [2.0.0 BETA 2](https://github.com/Adyen/adyen-react-native/releases/tag/2.0.0-beta.2)

**Comment by gunnartorfis** [comment]
Thanks for the fix @descorp 
It is working in most parts, except for the header (Credit Card). Is that a limitation in the Adyen iOS SDK?

<img width="358" alt="Screenshot 2024-02-12 at 09 54 31" src="https://github.com/Adyen/adyen-react-native/assets/5333875/da2ad90d-5bd6-4a28-b444-cf6bcf421ba2">

**Comment by camil-adyen** [comment]
Hi @gunnartorfis, the headers are fetched from the /paymentMethods response. Are you sending in the [shopperLocale](https://docs.adyen.com/api-explorer/Checkout/68/post/paymentMethods#request-shopperLocale) in your /paymentMethods or /sessions request?

**Comment by gunnartorfis** [comment]
@camil-adyen 🤦 Thanks a lot - it works to add the shopperLocale.

**Comment by descorp** [comment]
I have updated Localization.md #372

**Comment by inveon-sezerkenar** [comment]
Hi @descorp,

I'm using the sessions-flow with Adyen DropIn integration in my project.
Environment:
React Native: 0.79.2
@adyen/react-native: 2.8.1
Issue:
I'm trying to add localization support for languages other than English. While the backend team is working on adding the shopperLocale parameter to the /sessions endpoint, I wanted to test the iOS localization on the mobile side first.
Based on the screenshots in this issue thread, I understand that translations should work partially (excluding headers/titles) even before the backend changes. However, all text remains in English regardless of the locale I set.

What I've done:
1. Added supported languages to Info.plist:
```
<key>CFBundleLocalizations</key>
<array>
    <string>tr</string>
    <string>en</string>
    <string>fr</string>
    <string>de</string>
    <string>nl</string>
</array>
```

<img width="603" height="116" alt="Image" src="https://github.com/user-attachments/assets/f3583022-9e57-4c13-ab6d-a056a14dd855" />

2. Set the locale in Adyen configuration:
```
setAdyenConfiguration({
  environment: adyenSettings.environment,
  clientKey: adyenSettings.clientKey,
  // ... other config
  locale: 'fr-FR', // Also tried 'fr', 'nl-NL', 'de-DE', etc.
})
``` 

Question:
What am I missing for the iOS localization to work? Are there any additional steps required on the mobile side?

Additional question for Android:
From the comments in this thread, I understand that for Android, no additional mobile-side configuration is needed. Once the `shopperLocale` parameter is added to the `/sessions` request from the backend, the localization should work automatically. Ex: (fr-FR, de-DE, nl-NL) Is this understanding correct?
Thank you!

**Comment by descorp** [comment]
Hey @inveon-sezerkenar 

Thanks for reaching out!

> From the comments in this thread, I understand that for Android, no additional mobile-side configuration is needed. Once the shopperLocale parameter is added to the /sessions request from the backend, the localization should work automatically.

This is true for both platforms:

For Session flow locale will match value provided by your backend via [shopperLocale](https://docs.adyen.com/api-explorer/Checkout/71/post/sessions#request-shopperLocale) parameter. The `locale` value will be used only if nothing provided by a backend.

You can see [Localization.md](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Localization.md) for more details.
