### ISSUE TITLE
beta9 - iOS build error with use_frameworks!

### ISSUE THREAD

**Issue by gaspop** [Adyen/adyen-react-native#159]
**Describe the bug**
Trying to build an app with use_frameworks! enabled in the Podfile fails with this error:
`'adyen_react_native-Swift.h' not found`

Perhaps not the fault of this library. The reason for having to enable use_frameworks! is because of Firebase. Is there anything I can do to get it to build with use_frameworks?

**To Reproduce**
1. Add use_frameworks! to Podfile
2. Disable Flipper, hermes and fabric in Podfile
3. Build project

**Screenshots**
![image](https://user-images.githubusercontent.com/22764296/224327571-5a334ad9-58d6-4e53-a245-3a04536f6b52.png)

**Additional context**
react-native version: 0.71.3
@adyen/react-native version: 1.0.0-beta.9

**Comment by descorp** [comment]
Hey @gaspop 

Thank you for feedback!

We were able to reproduce this issue on our side with `use_frameworks!`.
The swift header is not discoverable, since it is behind framework now..

As a workaround, adding framework to a local file should work:
```objc
#import "adyen_react_native/adyen_react_native-Swift.h"
```

We will look into potential solution.

---

Side note:
if you are using `use_frameworks!`, Xcode will change hyphen with underscore in module name.
This effects 'AppDelegate':

```objc
#import <adyen_react_native/ADYRedirectComponent.h>
```

**Comment by gaspop** [comment]
Thanks for the answer!

It turns out that this library was just the first in a long chain that failed to build with use_frameworks! So I hope in the future that the firebase-maintainers can fix this on their end.

**Comment by jesperjohansson** [comment]
We are facing this same error when enabling `use_frameworks!` which we require for Firebase (🙄). EDIT: Even with the workaround

Manually changing `#import <adyen_react_native-Swift.h>` to `#import <adyen_react_native/adyen_react_native-Swift.h>` inside `Pods` seems to fix the issue if that's any help @descorp:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/21033162/229069702-3d6a32f1-bf78-4819-93c3-37be00b43b75.png">

**Comment by descorp** [comment]
Thanks for confirming @jesperjohansson 💚
