### ISSUE TITLE
Sending `didFailCallback` with no listeners registered.

### ISSUE THREAD

**Issue by descorp** [Adyen/adyen-react-native#168]
I'm encountering a similar issue with iOS where we pass the returnUrl as scheme://abc/:id and after completing or canceling the payment with Vipps,  returning to the app, the routing is done correctly but the payment window modal remains open and cannot be closed even after clicking close icon or a payment method. Additionally, I'm also getting the following error messages when clicking these buttons inside the payment window modal:

```
WARN Sending `didFailCallback` with no listeners registered.
WARN Sending `didSubmitCallback` with no listeners registered.
```

I also saw that the returnUrl comes with a redirectResult, should this be handled by the component?

Could you please suggest a solution for this?

_Originally posted by @joaooliveiramanteigas in https://github.com/Adyen/adyen-react-native/issues/162#issuecomment-1490287443_

**Comment by descorp** [comment]
Hey  @joaooliveiramanteigas

Thanks for reaching out 💚

Do you use `AdyenCheckout` context as mentioned in [README](https://github.com/Adyen/adyen-react-native#opening-payment-component) ?

**Comment by johndoeblocks** [comment]
Hello @descorp,

Yes, we are using AdyenCheckout. However, we are not wrapping the entire app in its context. Instead, we are rendering the context and its view only when it's time to pay, which is controlled by state inside our app. The webview we render also controls the removal of the context and its view once the payment is completed, by sending & receiving onMessage events to start and stop.

**Comment by descorp** [comment]
> we are not wrapping the entire app in its context

Wrapping entire app is not necessary. 

What I mean is - do you set up "onAdditionalDetails" and "onError" callbacks?

```js
<AdyenCheckout
  config={configuration}
  paymentMethods={paymentMethods}
  onSubmit={ (paymentData, component) => { /* Call your server to make the `/payments` request */ } }
  onAdditionalDetails={ (paymentData, component) => { /* Call your server to make the `/payments/details` request */ }}
  onError={ (error, component) => { /* Handle errors or termination by shopper */ }} >
    <MyCheckoutView/>
</AdyenCheckout>
```

**Comment by johndoeblocks** [comment]
Hi @descorp 

Yes we do, we used the [example](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Views/Checkout/CheckoutView.js) and have a similar implementation.

But for some instance when iOS returns from the returnUrl none of these activate.

The current implementation is working for android.

**Comment by descorp** [comment]
Hey @joaooliveiramanteigas 

This is interesting behaviour.
We are not entirely sure how to reproduce it.
Is it possible from your side to create a blank project that showcases this behaviour?

**Comment by descorp** [comment]
Hey @joaooliveiramanteigas 

How is it going?
Were you able to isolate problem in sandbox environment?

**Comment by johndoeblocks** [comment]
Hi @descorp sorry for late reply.

We've made it work with a simple change in the order we added AdyenRedirectComponent.

```
// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [ADYRedirectComponent applicationDidOpenURL:url] || [super application:application openURL:url options:options] || [RCTLinkingManager application:application openURL:url options:options];
}
```

We are using expo and initially, AdyenRedirectComponent was added as last option on mentioned function.

After that order change our Vipps & Swish payments started working accordingly.

**Comment by pinpong** [comment]
The check is in the adyen ios sdk [see](https://github.com/Adyen/adyen-ios/blob/develop/AdyenActions/Components/Redirect/RedirectComponent.swift#L111)

We are using:
```objective-c
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options {
  if ([RNGoogleSignin application:app openURL:url options:options]) {
    return YES;
  }

  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:app openURL:url options:options]) {
    return YES;
  }

  if([ADYRedirectComponent applicationDidOpenURL:url]) {
   return YES;
  }

  return NO;
}
```

**Comment by descorp** [comment]
I am going to close this for now.

Thanks @pinpong for sharing code snippet!
