### ISSUE TITLE
Show/hide pre selected payment method view not working 

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#17]
In native SDK, there is a param, that will hide or show the pre-selected payment method view, this field is not being mapped in react-native to the native implementation.

**To Reproduce**

1. Go to the example app
2. Click on Open DropIn
3. Pre-selected payment method view will show always, irrespective of the value set in config.

**Expected behavior**
 if the value of **showPreselectedStoredPaymentMethod** is set to false, the pre-selected View should not show.

**Screenshots**
This is a pre-selected view, It will display always if the user has saved payment methods.

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/18231674/170485638-1c71b09d-9772-49b0-9df6-28774661f4cc.png)

**Producible on Devices**
 - Platform: iOS & Android both
 - Device: Any
 - OS: Any
 - Version: 1.0.0 [BETA.3]

**Comment by descorp** [comment]
Fixed with 1.0.0-beta.4 release
