### ISSUE TITLE
Bad type for `google pay` configuration

### ISSUE THREAD

**Issue by gkueny** [Adyen/adyen-react-native#175]
## Bug

In the definition of type `Configuration`, `google` key is used instead of `googlepay`.

## Reproduction

Setup GooglePay config with `google` key.
An error "GooglePay merchantAccount not found" is throw.

## Expected behavior

With `googlepay` key, payment work as expected

**Comment by descorp** [comment]
> An error "GooglePay merchantAccount not found" is throw.

In general `merchantAccount` is passed in [\paymentMethods](https://docs.adyen.com/api-explorer/Checkout/68/post/paymentMethods); setting it manually (unlike for Apple Pay) is not required

**Comment by gkueny** [comment]
yeah, sadly our backend team stripe this info from `paymentMethods` so we set it manually.

But with `googlepay` key, everything work fine for us !
