### ISSUE TITLE
Jest: ReferenceError: Platform is not defined

### ISSUE THREAD

**Issue by gkueny** [Adyen/adyen-react-native#178]
## Bug

In `src/Core/constants.ts` `Platform` is used but is not imported?

I do not know if we face the issue with npm module, but in our case we use your module with GitHub commit.

When we run our jest tests, we face 

```
ReferenceError: Platform is not defined
```

error

**To Reproduce**
1. Install `adyen-react-native` with GitHub commit
2. Setup some test that use `adyen-react-native` module
3. Run test

## Expected behavior

I do not see why `Platform` is not imported in this file (but is imported in other file)

## Potential solution

```patch
--- a/node_modules/@adyen/react-native/src/Core/constants.ts
+++ b/node_modules/@adyen/react-native/src/Core/constants.ts
@@ -1,4 +1,5 @@
 // @ts-check
+import { Platform } from 'react-native';
 
 export const UNKNOWN_PAYMENT_METHOD_ERROR =
   'Unknown payment method or native module. \n\n' +
@@ -6,7 +7,6 @@ export const UNKNOWN_PAYMENT_METHOD_ERROR =
 
 export const LINKING_ERROR =
   `The package '@adyen/react-native' doesn't seem to be linked. Make sure: \n\n` +
-  // @ts-ignore
   Platform.select({ ios: "- You have run 'pod install'\n", default: '' }) +
   '- You rebuilt the app after installing the package\n' +
   '- You are not using Expo managed workflow\n';
```

**Comment by descorp** [comment]
PR #180

**Comment by gkueny** [comment]
@descorp we can close this issue as released ?

**Comment by descorp** [comment]
Released as RC.2.

Thanks @gkueny !
