### ISSUE TITLE
zero amount translation

### ISSUE THREAD

**Issue by Willham12** [Adyen/adyen-react-native#182]
Providing a zero value it's working on IOS as expected but not on Android:
`{ currency: 'EUR', value: 0 }`

https://github.com/Adyen/adyen-android/blob/d8132b64cb457c26fef6bbe913f5d3147a6ab995/ui-core/src/main/java/com/adyen/checkout/ui/core/internal/util/PayButtonFormatter.kt#L38

The current string is `Pay €0.00` but if we providing a zero value we expect `Confirm preauthorization`

**Comment by descorp** [comment]
Hey @Willham12 

Thanks for reaching out!
This is known issue on Android SDK.
Duplicat of #64
