### ISSUE TITLE
Dropin different value for payment methods

### ISSUE THREAD

**Issue by Willham12** [Adyen/adyen-react-native#183]
We want to use the dropin for pre authorizations.
As we know for example paypal needs a minimum value of 50 and applepay 10. Only creditcard can handle pre authorizations with zero value.

How can we archive the goal to know the selected payment method from dropin to change the configuration or how can we configure different amount for each payment method?

**Comment by camil-adyen** [comment]
Hi @Willham12,

For more information on pre-authorizations I'd like to refer you to our [docs](https://docs.adyen.com/online-payments/adjust-authorisation). It is possible to check which payment method the shopper selected with the help of the [onSelect](https://docs.adyen.com/online-payments/web-drop-in/optional-configuration#optional-drop-in-configuration) event.

I hope this helps.

**Comment by camil-adyen** [comment]
Hi @Willham12, 

Before loading the Drop-in, we expect you to be aware of the necessary payment flow. If you specify the payment amount in the [/paymentMethods](https://docs.adyen.com/api-explorer/Checkout/69/post/paymentMethods) request, we present all the available payment methods for that combination of amount and currency. If you want to handle very specific flows per payment method, then you can always look into the option of working with [individual components](https://docs.adyen.com/online-payments/react-native/components). 

If you want to pre-authorize a payment, you can specify that in the [additionalData of the /payments](https://docs.adyen.com/online-payments/adjust-authorisation#pre-authorise) request. 

I hope this helps. Feel free to reach out for any other questions.
