### ISSUE TITLE
issue with react-native IOS 3DS integration

### ISSUE THREAD

**Issue by gkueny** [Adyen/adyen-react-native#186]
## Contexte

As specified in the doc (see https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#example), we setup Adyen with theses informations (see `returnUrl`. We changed on purpose the package name for this issue):

```ts
const configuration = {
      environment: 'test',
      clientKey: 'SOME_CLIENT_KEY',
      countryCode: 'FR',
      amount: { currency: 'EUR', value: 1500 }, // Value in minor units
      returnUrl: `fr.gkueny.myapp://`,
      card: {
        showStorePaymentField: true,
        supported: ['maestro', 'mc', 'visa', 'cb'],
      },
    }
``` 

But on iOS 3DS payment, we face this error before 3DS action :

```
"Field value incorrect. Fields affected: [threeDSRequestorAppURL]"
```

# To Reproduce

1. Setup a project with Adyen
2. Set your app package as `returnUrl` (exemple `fr.gkueny.myapp://`)
3. Try a 3DS payment
4. See the `threeDSRequestorAppURL`error

## Expected behavior

3DS work

## Resolution

After getting in touch with Adyen support (Request [#3786041](https://www.adyen.help/hc/requests/3786041)), they suggest us a solution

```
Could you please leave the adyen package name in front of your package name?

"returnUrl":"adyencheckout://fr.gkueny.myapp",

This should solve the issue you are encountering.
```

It's indeed resolve our issue.<br/>
Is the documentation not up to date on this package? Or is there a deeper problem and the solution proposed by the support is just a workaround?

**Comment by descorp** [comment]
Hey @gkueny 

Thanks for reaching out :)

> "returnUrl":"adyencheckout://fr.gkueny.myapp",

I would suggest to do it other way around:

```json
"returnUrl":"fr.gkueny.myapp://adyencheckout",
```

Adding an extra path after `://` is a good practice so you can easily separate Adyen's redirects and your app's deep linking (in case you using one).

It is mentioned in [README](https://github.com/Adyen/adyen-react-native#configuration), but you are right - our Docs need to be updated. Thanks for pointing it out!

FYI, This issue is only effecting TEST environment.

**Comment by gkueny** [comment]
thanks and sorry I missed the right info in the doc 🤦‍♂️

> FYI, This issue is only effecting TEST environment.

Good to know !

**Comment by descorp** [comment]
Our documentation indeed need some grooming :)
It is always good to ask, so in future others can find the answer.
