### ISSUE TITLE
After successful PayPal payment, no redirect back to the app

### ISSUE THREAD

**Issue by RyanLinXiang** [Adyen/adyen-react-native#203]
**Describe the bug**
After successful Paypal payment, we get not redirected back to the App.

**To Reproduce**
1. Open DropIn
2. Click on PayPal
3. Finish payment

**Expected behavior**
Redirection back to the app

**Screenshots**
![Screenshot_1682620115](https://user-images.githubusercontent.com/59595349/234958158-9bfd875b-aee9-4aa0-8700-5719dfc62097.png)

**Desktop (please complete the following information):**
 - OS: Ventura 13.3.1
 - Browser Chrome, Safari
 - MacBook Pro M1

**Smartphone (please complete the following information):**
 - Device: Android Emulator, Pixel XL API 33

**Additional context**
MainActivity.java:

```
import android.content.Intent;
import android.os.Bundle;

import com.adyenreactnativesdk.AdyenCheckout;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
import org.devio.rn.splashscreen.SplashScreen;

public class MainActivity extends ReactActivity {
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		SplashScreen.show(this, R.style.SplashTheme, false);
		super.onCreate(savedInstanceState);
		AdyenCheckout.setLauncherActivity(this);
	}

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        AdyenCheckout.handleIntent(intent);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
      super.onActivityResult(requestCode, resultCode, data);
      AdyenCheckout.handleActivityResult(requestCode, resultCode, data);
    }

// ...

```

**Comment by pinpong** [comment]
Hi. it' working with the example on both platforms.

You can check https://github.com/Adyen/adyen-react-native/issues/168 or maybe you forgot the android manifest part of the installation guide?

**Comment by RyanLinXiang** [comment]
Yes, we have. Also testing with `adb ` successfully opens the app. For some reasons after payment finished, the redirect does not place. Does `AdyenCheckout` need to wrap more than just currently basically a button component? All event handlers are set (`onAdditionalDetails`) - but no effect. Any other ideas?

**Comment by pinpong** [comment]
I thought it's a conflict with the SplashScreen but it's not the case.
You should get a `didProvide` callback if the payments was successful.
Is the `returnUrl` from `didSubmit` correct?

**Comment by RyanLinXiang** [comment]
Never mind - it was a backend related issue as it does not call the correct return url scheme.
