### ISSUE TITLE
iOS: Error when return url doesn't include any params

### ISSUE THREAD

**Issue by RyanLinXiang** [Adyen/adyen-react-native#205]
**Describe the bug**
Currently our backend is implemented in a way that manages the part which is supposed to be handled by the front-end in the `onAdditionalDetails` callback whenever there is more data required from the user. That means that our backend will just return the redirect url scheme `myapp://payment` without any params whenever a payment is successful. For e.g. PayPal it means that this scheme is used to return to the app.

As far as I can observe, the `onAdditionalDetails` is only triggered when there is a `redirectResult` param in the url scheme like `myapp://payment?redirectResult=...`

I noticed that this is in Android not an issue, but in iOS, the `onError` callback is triggered, whenever returning to the app without `redirectResult` param, resulting in the following error object:
` {"description": "Couldn't find payload, redirectResult or PaRes/md keys in the query parameters.", "message": "Couldn't find payload, redirectResult or PaRes/md keys in the query parameters."}`

Why is there this different behaviour on Android vs iOS? Would it not make sense just to do nothing, when the return url does not include any params?

**Comment by descorp** [comment]
Hey @RyanLinXiang 

> Why is there this different behaviour on Android vs iOS?

iOS and Android have different mechanisms for handling redirects: iOS is handling redirects on application level, wether Android doing so per Activity (SDK level).

> Would it not make sense just to do nothing, when the return url does not include any params?

For this reason: Android providing custom `returnURL` that is unique per app, hence ignored for "blank" return URL.
On iOS it is expected that if call `[ADYRedirectComponent applicationDidOpenURL:url]` - you know what you are doing :)

> That means that our backend will just return the redirect url scheme myapp://payment without any params whenever a payment is successful.

I would suggest to just not call `[ADYRedirectComponent applicationDidOpenURL:url]`.

**Comment by RyanLinXiang** [comment]
Thanks for the response, but since I am not a iOS native developer - that is why we use React Native - I don't get the answer. What you mean by not calling `[ADYRedirectComponent applicationDidOpenURL:url]` ? Removing the line from `AppDelegate`? But how do I get redirected back to the app then?

**Comment by descorp** [comment]
> Removing the line from AppDelegate?

Correct :)
Line `[ADYRedirectComponent applicationDidOpenURL:url]` intended to pass **url** with query to RedirectComponent, but since your URL does not contain any query - this line is not needed. If your app do not have any other deep linking - you can simply `return true;` 

> But how do I get redirected back to the app then?

On iOS, redirect is configured on app level: 

[How to register your URL scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app#Register-your-URL-scheme).

**Comment by RyanLinXiang** [comment]
OK got it - thanks!

Another question: the example app always attaches `redirectResult` param to the return url - e.g. for PayPal when it was successful, url would look like `myapp://payment?redirectResult=...&type=completed&resultCode=successful` and when I cancel on the PayPal login page, url would be `myapp://payment?redirectResult=...&type=completed&resultCode=cancelled`.

Should we follow here the same pattern? How is `redirectResult` hashed? When I try to Base64-decode - it shows strange symbols....

**Comment by descorp** [comment]
> Should we follow here the same pattern? 

I am afraid that this pattern is not standardised. Query parameters may vary per payment method or sometimes even per version of the payment method's API used.

>  How is redirectResult hashed?

It is more secure than Base64 :) 
No one (including Adyen employees) can decrypt it without specific level of authorisation.
In short - we are using payment-industry-grade RSA and ASE algorithms. All private keys are secured between Adyen Servers and the Payment provider.

**Comment by RyanLinXiang** [comment]
OK got it - but my question is more if there are query parameters to be forwarded to the app, then this needs to be done, correct? Because currently our backend accepts a `returnSuccessUrl` and a `returnFailedUrl` and the return to the app is only done with one of these urls, not with any query params. So I wonder where these params in the example app are coming from...

**Comment by RyanLinXiang** [comment]
> I am afraid that this pattern is not standardised. Query parameters may vary per payment method or sometimes even per version of the payment method's API used.
> 
> ...
> 
> I would suggest to just not call [ADYRedirectComponent applicationDidOpenURL:url].

I have now tested on our end. The problem is when leaving `[ADYRedirectComponent applicationDidOpenURL:url]` out, we would need to handle the deep link via React Native Linking. In case of PayPal, if returning to the app without any `redirectResult` as query param, then the in-app browser won't close. This causes conflicts with React Navigation if we e.g. want to redirect the user to a screen. The screen won't show at the top of the screen. 

In case of a `redirectResult` param, `onAdditionalDetails` would be triggered where the `hide` function provided by Adyen can be called - this is exactly what is done by the example app. There every return to the app after a redirect calls `onAdditionalDetails` which closes the in-app browser. 

Is there any way to close the in-app browser opened by Adyen? A workaround would be to return to the app with a fake `redirectResult` param and then hide it in the `onAdditionalDetails` callback with the `hide` function. But this feels dirty.

**Comment by descorp** [comment]
Hey @RyanLinXiang 

> In case of a redirectResult param, onAdditionalDetails would be triggered where the hide function provided by Adyen can be called - this is exactly what is done by the example app. 

This scenario is only possible when there is ongoing payment. If no ongoing payment (ex you call your app's custom URL scheme from browser or notepad) - `onAdditionalDetails` would not be called.

> The problem is when leaving [ADYRedirectComponent applicationDidOpenURL:url] out, we would need to handle the deep link via React Native Linking

You use different query structure for different cases. For example, your backend can use different Custom URL scheme query (like `myapp://internal` or even `myapp-non-payment://`), so you can do something like:

```objc
  if ([[url query] hasPrefix:@"payment"]) {
    return [ADYRedirectComponent applicationDidOpenURL:url];
  }
  return [ReactNative doDeepLinking:url]; // Here goes your app's logic :) 
```

**Comment by descorp** [comment]
Hey @RyanLinXiang 

Were you able to resolve the problem?

**Comment by descorp** [comment]
I am going to close this ticket for now. 
Feel free to reopen and continue the discussion here.

**Comment by RyanLinXiang** [comment]
Unfortunately this bug now re-appeared in the RC 2.0.0. onError callback is triggered even in Android, after PayPal payment

`{"description": "[Ljava.lang.StackTraceElement;@13bce7e", "errorCode": "unknown", "message": "Error parsing redirect result, could not any query parameters"}`

Can you help please ?

**Comment by descorp** [comment]
@RyanLinXiang 
Let's continue discussion in #448
