### ISSUE TITLE
Android Issue: Can't determine type for tag '<macro name="m3_comp_bottom_app_bar_container_color">?attr/colorSurface</macro>'

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#213]
**Describe the bug**
Facing this issue while building the application with version 1.0.0-rc.2.

 

Can't determine type for tag '<macro name="m3_comp_bottom_app_bar_container_color">?attr/colorSurface</macro>'

 

That is caused by 1.7.0:
implementation 'com.google.android.material:material:1.7.0'

 

**Screenshots**

 
<img width="1152" alt="Screenshot 2023-05-09 at 4 45 26 PM" src="https://github.com/Adyen/adyen-react-native/assets/33232649/67128a9d-08c4-4bb0-9a52-34592a530d42">

 

**Smartphone (please complete the following information):**
- Device: Android
- "react-native": "0.64.2",

**Comment by EvertV** [comment]
I had the same issue, when upgrading from 1.0.0-beta.7 to the latest version. I assume it's because in 1.0.0 [BETA.8] these dependency updates happened:

**Comment by EvertV** [comment]
I had the same issue, when upgrading from 1.0.0-beta.7 to the latest version. I assume it's because in 1.0.0-beta.8 some dependency updates happened.

To fix this, I upgraded to `com.android.tools.build:gradle:7.3.1` (in android/build.gradle) and updating the distributionUrl to 7.6.1 `distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip` (in android/gradle/wrapper/gradle-wrapper.properties).

I also updated the `kotlinVersion` to "1.7.20" (in android/build.gradle).

**Comment by faizantariq1** [comment]
any update?

**Comment by sjain0700** [comment]
> I had the same issue, when upgrading from 1.0.0-beta.7 to the latest version. I assume it's because in 1.0.0-beta.8 some dependency updates happened.
> 
> To fix this, I upgraded to `com.android.tools.build:gradle:7.3.1` (in android/build.gradle) and updating the distributionUrl to 7.6.1 `distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip` (in android/gradle/wrapper/gradle-wrapper.properties).
> 
> I also updated the `kotlinVersion` to "1.7.20" (in android/build.gradle).

Same issue facing, tried with implementation 'com.google.android.material:material:1.6.0 also.

**Comment by sjain0700** [comment]
please update anyone find something

**Comment by ahmetgsu** [comment]
it is not an ideal solution but, I downgraded to material version to 1.6.0 in the node_modules. It is just a workaround!

node_modules > @adyen > react-native > android > gradle.build

`implementation 'com.google.android.material:material:1.6.0`

If you want to make this change, please do not forget to create a patch file.

**Comment by descorp** [comment]
I'll close this ticket for now. Feel free to leave feedback and continue the discussion here.
