### ISSUE TITLE
Callback onAdditionalDetails not called when using DropIn

### ISSUE THREAD

**Issue by EvertV** [Adyen/adyen-react-native#214]
**Describe the bug**
When using Components to add paymentMethodType `bcmc_mobile_app`, I get error `Required field 'paymentData' is not provided` on callback onAdditionalDetails. In the documentation it says that I should receive paymentData on `POST /payments`. But I don't get anything there, even after adding `threeDSPaymentData` to the response on our back-end (using `"@adyen/api-library": "^13.1.2"`).

Here's some logs
```
 LOG  users/me/payments?channel=Android 200 0.51s
 LOG  onSubmit {"paymentMethod": {"type": "bcmc_mobile_app"}, "returnUrl": "adyenreactnative://com.gopoppy.app", "storePaymentMethod": false}
 LOG  POST users/me/payments 201 0.33s
 LOG  {"action": {"method": "GET", "paymentMethodType": "bcmc_mobile_app", "type": "redirect", "url": "https://checkoutshopper-live.adyen.com/checkoutshopper/checkoutPaymentRedirect?redirectData=..."}, "resultCode": "RedirectShopper"}
 LOG  onAdditionalDetails {"details": {"redirectResult": "X3XtfGC7!H4sIAAAA...."}}
 LOG  POST users/me/payments/details 400 1.13s
 LOG  {
  "status": 400,
  "data": {
    "message": "HTTP Exception: 422. : Required field 'paymentData' is not provided.",
    "data": {},
    "key": "HTTP Exception: 422. : Required field 'paymentData' is not provided."
  },
  "line": 19260,
  "column": 61,
  "sourceURL": "http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.gopoppy.app&modulesOnly=false&runModule=true"
}
```

On back-end side when calling `checkout.payments`, with request: 

```
checkout.payments({
    merchantAccount: `${process.env.ADYEN_MERCHANT}`,
    amount: { currency: EURO, value: amount },
    paymentMethod: cardDetails,
    reference: transactionReference,
    channel,
    shopperReference,
    shopperEmail,
    telephoneNumber,
    shopperIP,
    enableRecurring: true,
    enableOneClick: false,
    shopperInteraction: PaymentRequest.ShopperInteractionEnum.Ecommerce,
    recurringProcessingModel:
      PaymentRequest.RecurringProcessingModelEnum.Subscription,
    returnUrl: `${returnUrl}`,
    additionalData: {
      allow3DS2: "true",
      "riskdata.riskProfileReference": "2519...."
    }
  })
```
And this is the response :
```
PaymentResponse {
  action: {
    paymentMethodType: 'bcmc_mobile_app',
    url: 'https://checkoutshopper-test.adyen.com/checkoutshopper/checkoutPaymentRedirect?redirectData=X3XtfGC7%21H4sIAAAAA...',
    method: 'GET',
    type: 'redirect'
  },
  additionalData: undefined,
  amount: undefined,
  donationToken: undefined,
  fraudResult: undefined,
  merchantReference: undefined,
  order: undefined,
  paymentMethod: undefined,
  pspReference: undefined,
  refusalReason: undefined,
  refusalReasonCode: undefined,
  resultCode: 'RedirectShopper',
  threeDS2ResponseData: undefined,
  threeDS2Result: undefined,
  threeDSPaymentData: undefined
}
```

When using DropIn, callback onAdditionalDetails doesn't seem to get called and continues works without error, but the payment method does not seem to get saved.

Logs when using DropIn:
```
 LOG  users/me/payments?channel=Android 200 0.40s
 LOG  onSubmit {"amount": {"currency": "EUR", "value": 2}, "paymentMethod": {"type": "bcmc_mobile_app"}, "returnUrl": "adyencheckout://com.gopoppy.app", "storePaymentMethod": false}
 LOG  POST users/me/payments 201 0.20s
 LOG  POST /payments result {"action": {"method": "GET", "paymentMethodType": "bcmc_mobile_app", "type": "redirect", "url": "https://checkoutshopper-live.adyen.com/checkoutshopper/checkoutPaymentRedirect?redirectData=X3XtfGC7%21H4sIAAA..."}, "resultCode": "RedirectShopper"}
```

For non-3DS payment methods, like credit card, it's working fine. We didn't have this issue on BETA-7, but started happening since we upgraded to latest (RC-2).

**To Reproduce**
1. Add payment method `bcmc_mobile_app` using Components
2. Do the 3DS successful payment *(of 0.02 euros in this case)
3. Back to the app, and Error 422. : Required field 'paymentData' is not provided. appears, after the onAdditionalDetails callback, which calls `/payments/details`
4. Payment method does not get stored correctly

Same when using DropIn, but onAdditionalDetails callback does not get called, so no error. But also payment method does not get stored here.

**Expected behavior**
Payment method `bcmc_mobile_app` should get correctly stored when coming back to the app and calling `onAdditionalDetails`.

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Android 13

**Additional context**
When using BETA-7, I have these logs and the payment data gets saved correctly in our database (using the same back-end endpoints here).
```
LOG  users/me/payments?channel=Android 200 0.39s
 LOG  didSubmit {"amount": {"currency": "EUR", "value": 2}, "paymentMethod": {"type": "bcmc_mobile_app"}, "returnUrl": "adyencheckout://com.gopoppy.app", "storePaymentMethod": false}
 LOG  users/me/payments 201 2.61s
 LOG  didSubmit result {"action": {"method": "GET", "paymentMethodType": "bcmc_mobile_app", "type": "redirect", "url": "https://checkoutshopper-live.adyen.com/checkoutshopper/checkoutPaymentRedirect?redirectData=X3XtfGC7%21H4sIAAAAAAA..."}, "resultCode": "RedirectShopper"}
 LOG  didProvide {"details": {"redirectResult": "X3XtfGC7!H4sIAAAAA..."}}
 LOG  users/me/payments/details 201 0.44s
```

**Comment by EvertV** [comment]
Looks like I was passing the wrong data in the body of my `users/me/payments/details` 🤦 

While making the changes and refactoring a bit, I ended up sending the `details` inside `details`, so it couldn't find the correct data.

But it looks like the type of `data` (PaymentMethodData) seems to be incorrect, since it looks like this:
```
{"details": {"redirectResult": "X3XtfGC7!H4sIAAAA...."}}
```
and not like this
```
export interface PaymentMethodData {
  paymentMethod: {
    type: string;
    [key: string]: any;
    checkoutAttemptId?: string;
  };
  browserInfo?: {
    userAgent: string;
  };
}
```

So my mistake was that I was sending this body to the endpoint
```
{"details": {"details": {"redirectResult": "X3XtfGC7!H4sIAAAA...."}}}
```

All good now! But maybe look at the type of `data` on method `onAdditionalDetails` @descorp ?

**Comment by EvertV** [comment]
Looks like I closed the issue too fast. `onAdditionalDetails` is not being called when using DropIn, but it's called when using Components. So `bcmc_mobile_app` cannot be set up with DropIn, since it needs `onAdditionalDetails` to be called.

**Comment by 0xClpz** [comment]
Hello! We have a very similar setup on our side and we can't get ```onAdditionalDetails``` to be called when using ```bcmc_mobile_app``` either, it works fine with credit cards though.

**Comment by descorp** [comment]
Hey @EvertV @0xClpz 

This is an issue on Android or both?

**Comment by EvertV** [comment]
@descorp I only tested Android, not sure for iOS right now

**Comment by 0xClpz** [comment]
On my side this was an iOS issue, did not test it on android

**Comment by descorp** [comment]
hm.. 🤔

this could be issue on issuer side or this flow is somehow not yet supported.
Will run tests locally and get back to you

**Comment by EvertV** [comment]
It was working well on `beta-7` (with dropIn). We rolled out our app with the latest version now (using only components).We're getting reports from users that cannot add `bcmc_mobile_app` and we're only using components now. When looking in the logs, it seems that onAdditionalDetails is not being called. It is working for me though, maybe it's specific issuers? I'm using the BNP Paribas Fortis app, but a client using the same app has this issue. In the logs I see that `onAdditionalDetails` is not being called, in Adyen everything is fine, the payment happens.

**Comment by descorp** [comment]
> It is working for me though

This is the tricky part. It could be one/small number of many issuers that acting unexpectedly.

**Comment by EvertV** [comment]
It was working well on beta-7 (with dropIn). We rolled out our app with the latest version now (using only components).

We're getting reports from users that cannot add payment method bcmc_mobile_app. When looking in the logs, it seems that onAdditionalDetails is not being called. It is working for me though, maybe it's specific issuers? I'm using the BNP Paribas Fortis app, but a client using the same bank app has this issue. In the logs I see that onAdditionalDetails is not being called, in Adyen everything is fine, the payment happens.

**Comment by descorp** [comment]
> I'm using the BNP Paribas Fortis app, but a client using the same bank app

Maybe different version of issuer app? Or Web/Mobile flow? 

@EvertV could you reach out to [Adyen Support Team](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) and provide them with PSP reference for your successful and shopper's unsuccessful transactions?

"PSP reference" could be found in your CA portal or in the header of network call.

**Comment by EvertV** [comment]
Done! Ticket ID #3988635 (in case it's relevant for you as well).

FYI: Turns out the issue was existing on beta-7 already

**Comment by descorp** [comment]
Great thanks @EvertV 💚
We will investigate from our side!

**Comment by EvertV** [comment]
@descorp I feel like this issue can be closed, since it got a bit messy to know what the issue exactly is (my bad). Should I open a new issue with the information mentioned in the support ticket #3988635 (successful payment without onAdditionalDetails called)?

**Comment by descorp** [comment]
This would be helpful to focus on one thing and consolidate our findings 
Thanks @EvertV

**Comment by EvertV** [comment]
Will do! See https://github.com/Adyen/adyen-react-native/issues/249
