### ISSUE TITLE
Redirect back to app not working on 1.0.0-rc.2

### ISSUE THREAD

**Issue by kadikraman** [Adyen/adyen-react-native#217]
**Describe the bug**
Redirect back to app not working on `1.0.0-rc.2`.

We recently upgraded from `1.0.0-beta.9` -> `1.0.0-rc.2` and our Klarna payment stopped redirecting back to the app.

Instead the user gets stuck in the "waiting for redirect" page.

We didn't have any other code changes, and the redirect was in the format of `my-app://`.

**To Reproduce**
Check out with Klarna on `1.0.0-rc.2`

**Expected behavior**
User can complete payment

**Screenshots**
<img src="https://github.com/Adyen/adyen-react-native/assets/6534400/f99bc7c5-129b-42b7-a8a9-845ab097ec21" width="300px" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iPhone 14

**Additional context**
As a fix for now, we reverted to `1.0.0-beta.9`, but it would be great to be able to upgrade to the latest version.

**Comment by descorp** [comment]
Hey @kadikraman 

On **rc1** `onProvide` callback was renamed to `onAdditionalDetails`.
Could you check if this is the case?

```js
<AdyenCheckout
  config={configuration}
  paymentMethods={paymentMethods}
  onSubmit={(paymentData, component) => {
    /* Call your server to make the `/payments` request */
  }}
  onAdditionalDetails={(paymentData, component) => {
    /* Call your server to make the `/payments/details` request */
  }}
  onError={(error, component) => {
    /* Handle errors or termination by shopper */
  }}
>
  <MyCheckoutView />
</AdyenCheckout>;
```

**Comment by kadikraman** [comment]
Thanks @descorp that did the trick.

Could be an argument in favour of adding TypeScript types to the library?

This is what we have so far: we've only typed the stuff we use of course, but in case you'd like to use it as a starting point!

```ts
type AdyenConfig = {
  environment: string;
  clientKey: string;
  countryCode: string;
  amount: {
    currency: string;
    value: number;
  };
  merchantAccount: string;
  returnUrl: string;
};

type AdyenData = {
  browserInfo: {
    userAgent: string;
  };
  paymentMethod: { type: 'paypal' | 'klarna' | 'klarna_account' };
  returnUrl: string;
  storePaymentMethod: false;
};

type AdyenProvideData = {
  paymentData: string;
  details: {
    payload: string;
  };
};

type AdyenPaymentMethodType =
  | {
      configuration: {
        merchantId: string;
        intent: string;
      };
      name: string;
      type: 'paypal';
    }
  | {
      name: string;
      type: string;
    };

declare module '@adyen/react-native' {
  function useAdyenCheckout(): {
    start: (
      name: 'paypal' | 'klarna' | 'klarna_account' | 'zip' | 'applepay',
    ) => void;
  };

  const AdyenCheckout: React.FC<
    React.PropsWithChildren<{
      config: AdyenConfig | undefined;
      paymentMethods: {
        paymentMethods: AdyenPaymentMethodType[] | undefined;
      };
      onSubmit: (
        data: AdyenData,
        nativeComponent: AdyenNativeComponent,
      ) => void;
      onAdditionalDetails: (
        data: AdyenProvideData,
        nativeComponent: AdyenNativeComponent,
      ) => void;
      onComplete: (nativeComponent: AdyenNativeComponent) => void;
      onFail: (error: Error, nativeComponent: AdyenNativeComponent) => void;
      onError: (error: Error, nativeComponent: AdyenNativeComponent) => void;
    }>
  >;
}
```

**Comment by descorp** [comment]
Hey @kadikraman 

We added [Typescript support](https://github.com/Adyen/adyen-react-native/blob/1.0.0-rc.2/src/AdyenCheckoutContext.tsx#L36-L54) in `rc2`.
I am wondering why it didn't worked(highlighted error) for you 🤔

**Comment by kadikraman** [comment]
I see - my bad! It wouldn't have worked for us since the stuff in our `declarations.d.ts` would override the new types from the library. I'll try to upgrade to using the library types now, thanks for pointing it out (and 🥳 🎉 👏 for TypeScript support!!).

Edit: I think there's a couple of types to be added, e.g. for the `environment` the [options](https://github.com/Adyen/adyen-react-native/blob/develop/src/Core/configuration.ts#L4) are
```js
type Environment =
  | 'test'
  | 'live-eu'
  | 'live-us'
  | 'live-au'
  | 'live-apse'
  | 'live-in';
```
But our live env is just called `live`. Would it be ok if I create a PR for this and any new types or do you prefer to keep it as is?

**Comment by descorp** [comment]
> there's a couple of types to be added

Indeed, missed some exports..

> Would it be ok if I create a PR

PRs are always welcome :)
