### ISSUE TITLE
Clicking the X to close a pop-up does not work out of the box

### ISSUE THREAD

**Issue by erik-kallen** [Adyen/adyen-react-native#219]
**Describe the bug**
After calling `adyenCheckout.start()`, clicking the X in the popup does noting.

Using `component.hide(false)` in the onError handler seems to work, so perhaps it's a documentation issue. However, it is not very well documented exactly when the `onError` handler will be called, so perhaps hiding the component in response to any error is not a good idea? Also, I don't really see why anyone would not want the pop-up to be closed in response to clicking the X, so perhaps close it automatically and add a separate `onClosed` event would be a good idea?

**To Reproduce**
1. Call `adyenCheckout.start('dropin')` with a valid configuration
3. Try to close the pop-up that appears by clicking the X

**Expected behavior**
The pop-up is closed

**Device**
iPhone

**Comment by descorp** [comment]
Hey @erik-kallen 

> After calling adyenCheckout.start(), clicking the X in the popup does noting.

The `onError` handler is called with `canceledByShopper` error code.

>  Also, I don't really see why anyone would not want the pop-up to be closed in response to clicking the X, so perhaps close it automatically and add a separate onClosed event would be a good idea?

This is not possible in some cases, for ex. Apple Pay.

The SDK provides you full control over it's UI lifecycle: entry and exit points. 
For example, one needs to perform "order cancelation" network calls that might take longer to execute - this will prevent shopper interacting with application between "pop up" dismiss and next step taken.

> add a separate onClosed event 

This could be a nice addition on it's own. We will investigate.

> hiding the component in response to any error is not a good idea?

`onError` usually means termination of the payment process.
There is a [short list](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Error%20codes.md) of error codes.

**Comment by erik-kallen** [comment]
For some reason the X works today, but didn't yesterday
