### ISSUE TITLE
Terminal API Client

### ISSUE THREAD

**Issue by brianjd** [Adyen/adyen-react-native#220]
Is the a terminal API client for React Native?  The NodeJS library (https://github.com/Adyen/adyen-node-api-library) will take some time to rewrite for ReactNative (ie. it uses node https module etc.).

**Comment by camil-adyen** [comment]
Hi @brianjd, 

This React Native SDK can be used to integrate our online Checkout in a React Native project. This is only for online payments using the [Checkout API.](https://docs.adyen.com/api-explorer/Checkout/69/post/payments).

~~When connecting terminals to the Terminal API, we always advice to use a mediation backend for security reasons.~~

**UPD**

For now, we can only suggest that you try to take apart our NodeJS library for your React Native needs.
If you have any further questions, please reach out possupport@adyen.com
