### ISSUE TITLE
3DS Card Loading stop issue user can click again on pay button

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#234]
**Describe the bug**
when you directly open the scheme enter the 3ds test card and click on pay button, pay button stop loading before the 3ds view open, user can again click on pay button.

**To Reproduce**
you can watch the video for reproducing the issue.

**Expected behavior**

**Screenshots**

https://github.com/Adyen/adyen-react-native/assets/33232649/897bc25b-88b2-4b82-833d-043840966753

**Smartphone (please complete the following information):**
 - IOS 
 - Iphone Simulator 13

**Comment by descorp** [comment]
Hey @faizantariq1 

This is [known issue](https://github.com/Adyen/adyen-react-native/issues/70).
Will be fixed on iOS 4.11.0 and updated on React Native `1.1.0`
