### ISSUE TITLE
GiroPay is not working App

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#236]
**Describe the bug**
when we open giropay we received a message 'method requesst 'GET' is not support'. i'm also observing on web giropay is working fine.
base url for app:
[https://atruvia-proxy-test.girocheckout.de/api/v1/checkout/bank](https://atruvia-proxy-test.girocheckout.de/api/v1/checkout/bank)

base url for web:
[https://sandbox.paydirekt.de/checkout](https://sandbox.paydirekt.de/checkout/)

**To Reproduce**
Just open giro pay.

**Sc
![Simulator Screen Shot - iPhone 13 - 2023-06-22 at 19 11 41](https://github.com/Adyen/adyen-react-native/assets/33232649/4f5a1059-6925-4fcd-86de-782f47c91a45)
reenshots**

**Smartphone (please complete the following information):**
 - Device: IOS

**Comment by descorp** [comment]
Hey @faizantariq1 

thanks for reporting this! 
We will check with Local Payment Methods team and get back to you.

**Comment by descorp** [comment]
Small update:
This seems to be a problem on Adyen's side after migrating to the new GiroPay API, introduced lately.
Still investigating...

**Comment by ahsan-ali-lebara** [comment]
@descorp Previously web view as not loading, now it's working, but once we have successful or failed transaction, webview is not triggering the callback. 

So webview will be open forever, ass callbacks are not working.

**Comment by descorp** [comment]
Hey @ahsan-lebara 

I was able to successfully test GiroPay flow on iOS.
Does callback works fine for you on other redirect PMs(ex. klarna, paypal) ?

**Comment by ahsan-ali-lebara** [comment]
Yeah, for Paypal redirects are working fine. Which versions are you using?

**Comment by descorp** [comment]
I am running onExample App from 1.0.0
Will verify on standalone sample project..


https://github.com/Adyen/adyen-react-native/assets/2648655/c9fd8c2d-fc4f-430f-af13-fbf4864b0d2a

**Comment by ahsan-ali-lebara** [comment]
HI @descorp 
This way working for me too, go for a successful transaction, It's not working there.

**Comment by descorp** [comment]
Hey @ahsan-lebara 

I was able to run TEST flow successfully on Android.
On iOS TEST flow is not frictionless, but after copying URL - redirect works.


https://github.com/Adyen/adyen-react-native/assets/2648655/c85135e1-b60f-4fa6-8a25-477363e27675

**Comment by ahsan-ali-lebara** [comment]
When will you be able to resolve this issue?

**Comment by descorp** [comment]
Hey @ahsan-lebara 

> When will you be able to resolve this issue?

I believe that the issue was resolved. I would suggest to run LIVE penny test

**Comment by descorp** [comment]
Hey @ahsan-lebara 

was this resolved?

**Comment by descorp** [comment]
I am going to close this ticket due to a lack of activity.
