### ISSUE TITLE
AdyenCheckout callback props not fired

### ISSUE THREAD

**Issue by fauzymk** [Adyen/adyen-react-native#238]
**Describe the bug**
 I'm using the drop-in flow. onError, onSubmit, onComplete not fired. It occurs when starting using `start('payment_type')`. It works fine when using `start('dropIn')`

**To Reproduce**
1. start using `start('payment_type')`
2. close the modal or complete payment
3. onError/onComplete/onSubmit not fired

**Expected behavior**
onError, onSubmit, onComplete fired

**Comment by descorp** [comment]
Hey @fauzymk 

Is it Android, iOS or both?

**Comment by fauzymk** [comment]
Sorry forgot to mention. I only tested it on Android.

**Comment by descorp** [comment]
Hey @fauzymk 

> start using start('payment_type')

For what `payment_type` does this happen?
Can you try `scheme`?

We had similar issue #196 
Could you try:
- Upgrade to latest react native
- Make sure you followed all steps on [Android integration](https://github.com/Adyen/adyen-react-native#android-integration) guidelines

**Comment by fauzymk** [comment]
Hi! it works now. We are using payment_type `paywithgoogle`. It turns out we forgot to add this.

```java
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
  super.onActivityResult(requestCode, resultCode, data);
  AdyenCheckout.handleActivityResult(requestCode, resultCode, data);
}
```

Previously we were following the steps from [here](https://docs.adyen.com/online-payments/build-your-integration/additional-use-cases/advanced-flow-integration?platform=Cross-platform&integration=React+Native+Drop-in&version=1.0.0&tab=android_2#step-2-add-adyen-drop-in-to-your-app) and doesn't mention about adding this code.

Thanks! @descorp. Closing the issue.

**Comment by descorp** [comment]
Hey @fauzymk 

Glad that everything is working now 🎉
Since it is v1.0.0 - our documentation might still be imperfect.

If you find anything missing or confusing, please let us know 💚
