### ISSUE TITLE
Drop In Component Pay button not working in android APK's.

### ISSUE THREAD

**Issue by jbcampbell1** [Adyen/adyen-react-native#241]
We successfully implemented the adyen drop in component in our development builds and have been able to make payments to the test environment on both IOS and Android devices.

However when we created our QA build the pay £xx.xx button within the component (after entering card details) seems to
be inactive. Nothing at all happens when we press the button, we cannot even generate a 'hello world' log when pressing the button. (See screenshot of button below)

<img width="440" alt="image" src="https://github.com/Adyen/adyen-react-native/assets/132555914/69c8a2a3-1e02-4f7d-a4df-a3ba832ff210">

This was tested across multiple android emulators and multiple android devices using multiple android versions, and all resulted in this button not responding when clicked. 

 In our IOS QA builds it works as expected and we can make payments to the test environment. 

It does not seem to be an issue to do with debug versus release builds either as we tried a local react native release mode run and this allowed us to make a payment to the test environment, so we are at a loss as to what could be causing this issue.

Is this an issue you have encountered before and do you have any advice on how to resolve this issue?

**Comment by descorp** [comment]
Hey @jbcampbell1 

Have you followed all steps on [Android integration](https://github.com/Adyen/adyen-react-native#android-integration) guidelines?

**Comment by jbcampbell1** [comment]
Hey @descorp,

It appeared we forgot to update our AndroidManifest.xml for each environment, hence why it was working in develop and on IOS!

Thanks for the quick response! Issue is now resolved :)
