### ISSUE TITLE
Missing `summaryItems` from ApplePay Component

### ISSUE THREAD

**Issue by patrikmolnar** [Adyen/adyen-react-native#243]
**Describe the bug**
When using the ApplePay Component implementation, I expect to see the item summary and subTotals of each item that I'm purchasing. Instead I'm only seeing the total price without the Summary section.

**To Reproduce**
1. Start payment by using `start('applepay')`
2. Click on the price to bring up the details
3. Verify that the summary section is not there

**Expected behavior**
I expect to see the item summary and subTotals of each item that I'm purchasing.

**Screenshots**
| Expected | Current  |
|---|---|
|<img src="https://github.com/Adyen/adyen-react-native/assets/31874516/4c5ddc80-e695-4b47-87b0-bd96e49ae40d" width="200">|<img src="https://github.com/Adyen/adyen-react-native/assets/31874516/a7cf91d9-b032-4a83-be34-8bd0d933f9fb" width="200">|

**Additional context**
This is what my configuration looks like: 
```js
const adyenConfig = {
      environment: 'test',
      clientKey: 'xxxxxxxxxxxxxx',
      returnUrl: 'joeloyalty://',
      countryCode: 'DK',
      amount: { currency, value: totalAmount * 100 },
      applepay: {
        merchantID: 'xxxxxxxxxxxxxxx',
        merchantName: 'JOE & THE JUICE',
        allowOnboarding: true,
        summaryItems: items.map((item) => ({
          label: item.name,
          amount: {
            currency,
            value: item?.price.priceTotal * 100,
          },
        })),
      },
    }
```

**Comment by descorp** [comment]
Hey @patrikmolnar 

This is indeed missing feature on `1.0.0`.
We will prioritise it.

**Comment by patrikmolnar** [comment]
Hey @descorp

Thanks for the reply! Do you have an ETA for 1.1.0? Thanks :)

**Comment by descorp** [comment]
Hey @patrikmolnar 

We are aiming to release 1.1.0 around next week.

**Comment by descorp** [comment]
PR #258

**Comment by descorp** [comment]
Added on [1.1.0](https://github.com/Adyen/adyen-react-native/releases/tag/1.1.0)
