### ISSUE TITLE
Handle authentication-only 3DS2 actions

### ISSUE THREAD

**Issue by alexisloiselle** [Adyen/adyen-react-native#245]
**Is your feature request related to a problem? Please describe.**
The problem is that when a customer wants to make a transaction with a payment method that already was added, there is no way to open the drop-in only to handle the action payload. The first step is always the form for the credit card.

**Describe the solution you'd like**
It would be nice for the drop-in component to always be available and to always have access to the `handle` method, without having to open it before.

**Describe alternatives you've considered**
- Implement my own native module.
- Patching the package to prevent the drop-in component to be `nil`.

**Additional context**
The way it works in our system right now is that we authorize the payment from the backend, and, if necessary, send the `action` to the frontend. But there's no way to initiate the drop-in directly with the `action`.

**Comment by descorp** [comment]
Hey @alexisloiselle 

This feature is in our backlog.
Currently we are waiting for Adyen Checkout Android SDK `v5` release.
Will keep you posted.

**Comment by alexisloiselle** [comment]
Thank you @descorp,
is there some sort of workaround in the meantime to your knowledge?

Also, do you have an idea of the timeline for 2.0.0?

**Comment by descorp** [comment]
Hey @alexisloiselle 

No workarounds so far.

> Implement my own native module.

This is probably the best shot. You can look at iOS [AdyenActionComponent](https://github.com/Adyen/adyen-ios/blob/4.10.4/AdyenActions/AdyenActionComponent.swift) and Android [standalone action handling](https://github.com/Adyen/adyen-react-native/blob/1.0.0-beta.4/android/src/main/java/com/adyenreactnativesdk/ActionHandler.kt).

> Also, do you have an idea of the timeline for 2.0.0?

We are pending on stable Android `v5` release, that is expected this year. My best guess - Q4 2023.

**Comment by descorp** [comment]
As an alternative/temporary workaround:

1) Use web-based 3DS flow (reach out for [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) for more details)
2) Make [API-Only](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Views/CseView.js#L39-L55) call to [`make a one-off payment with a token and CVV, using encrypted card details`](https://docs.adyen.com/api-explorer/Checkout/68/post/payments#examples-request-oneclick-securedfields) 
3) Handle web-redirect action manually
    a. present URL from [redirect action](https://docs.adyen.com/api-explorer/Checkout/68/post/payments#responses-200-action) in browser;
    b. handle redirect URL and make [`/payments/details`](https://docs.adyen.com/api-explorer/Checkout/68/post/payments/details) API call with [payload](https://docs.adyen.com/api-explorer/Checkout/68/post/payments/details#request-details-payload);

**Comment by alexisloiselle** [comment]
Thanks @descorp, this is indeed the solution that we currently use.

**Comment by ahsan-ali-lebara** [comment]
@alexisloiselle Once you get IdentifyShopper in case of the saved card, how you are re-directing flow to the web for 3DS authentication flow? Even if the action is IdentifyShopper, I am not getting any URL that can be opened in the web-browser for 3DS authentication.

**Comment by alexisloiselle** [comment]
@ahsan-lebara I think that we are forcing URLs (3DS v1) authentications.

**Comment by ryadav1495** [comment]
@descorp , I was going through with the documentation of [Android](https://github.com/Adyen/adyen-android). I have found that v5.0 has been releases. I just wanted a suggestion regarding `Handle authentication-only 3DS2 actions`. 

Is there any way to have access  of [standalone](https://github.com/Adyen/adyen-react-native/blob/1.0.0-beta.4/android/src/main/java/com/adyenreactnativesdk/ActionHandler.kt) in our JS side. 
According to this current documentation we have to define the complete `AdyenCheckoutComponent` which is not required in our use-case.

**Comment by descorp** [comment]
Hey @ryadav1495 

This is correct suggestion - we are currently working on [adopting Android v5](https://github.com/Adyen/adyen-react-native/tree/v5_android_advanced).
"Standalone action handling" is indeed one of the main features we are looking to introduce.
Stay tuned!

**Comment by jhta** [comment]
> As an alternative/temporary workaround:
> 
> 1. Use web-based 3DS flow (reach out for [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) for more details)
> 2. Make [API-Only](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Views/CseView.js#L39-L55) call to [`make a one-off payment with a token and CVV, using encrypted card details`](https://docs.adyen.com/api-explorer/Checkout/68/post/payments#examples-request-oneclick-securedfields)
> 3. Handle web-redirect action manually
>    a. present URL from [redirect action](https://docs.adyen.com/api-explorer/Checkout/68/post/payments#responses-200-action) in browser;
>    b. handle redirect URL and make [`/payments/details`](https://docs.adyen.com/api-explorer/Checkout/68/post/payments/details) API call with [payload](https://docs.adyen.com/api-explorer/Checkout/68/post/payments/details#request-details-payload);

@descorp are you expecting to release this feature for 2023?

We have the same situation but in our case, we cannot go with the `redirect action` solution, and I'm not sure about to proceed with creating our own native module considering that you are working on it.

**Comment by ryadav1495** [comment]
> Hey @ryadav1495
> 
> This is correct suggestion - we are currently working on [adopting Android v5](https://github.com/Adyen/adyen-react-native/tree/v5_android_advanced). "Standalone action handling" is indeed one of the main features we are looking to introduce. Stay tuned!

@descorp I am planning to use [Native 3ds Android SDK](https://github.com/Adyen/adyen-3ds2-android) and write a native module. Will it be right approach to use for 3ds authorisation?

**Comment by descorp** [comment]
Hey @ryadav1495 @jhta 

> Will it be right approach to use for 3ds authorisation?

It is not a straightforward business to create native module for 3DS2 handling on v4 Android.
We are currently finalising adoption for v5 Android for [Advanced flow](https://docs.adyen.com/online-payments/build-your-integration/additional-use-cases/?tab=sessions_flow_advanced_flow_1) (used to be "normal flow on v4").

> are you expecting to release this feature for 2023?

Whether we will make an ALPHA release with it is TBD, but as soon as we have it working on `develop` - I will post it here.

**Comment by leofolive** [comment]
Hi everyone, have we had any updates on this? We urgently need this feature 👍🏼 
@descorp

**Comment by leofolive** [comment]
Hey guys, I've implemented a patch for this. Now, the handler supports authentication only if you provide a configuration with the environment and clientKey.

Works on: Android and IOS.

To call the handler:

```
AdyenInstant.handle(action, {
  environment: 'test',
  clientKey: 'CLIENTKEY_HERE',
});
```
To capture the 3DS2 Response payload:

```
const eventEmitter = new NativeEventEmitter(AdyenInstant);

useEffect(() => {
  // Wrap your async call here

  eventEmitter.addListener('didProvideCallback', data => {
    console.log(data);
  });
}, []);
```

**Attention: Please use this patch only if you don't need other drop-in actions. I implemented it because the action was already present in my backend, and I need to handle it on my app. Note that I haven't validated other flows, and I'm uncertain about the impact of this change on them. Exercise caution and thoroughly test before incorporating this patch.**

Patch 1.2.0:
https://gist.github.com/LFMAKER/e0c429d16a8788cd4584f28b2007aed2

Feel free to incorporate these changes into your code. Let me know if you have any questions!

**Comment by leofolive** [comment]
@descorp, could you kindly review this patch and assess its appropriateness for a pull request? I aim to preserve the existing flow, but I believe it could be modified as follows:

```
const response = await AdyenInstant.handle(action, {
  environment: 'test',
  clientKey: 'CLIENTKEY_HERE',
});

```
However, implementing this change could involve substantial alterations to the library's architecture. It's worth noting that this adjustment could provide support for asynchronous calls with await (resolve, reject) and events with addListener.

**Comment by ryadav1495** [comment]
@LFMAKER , Thanks for update.  I have  already tried to implement the changes you have proposed, but app was crashing randomly. To comply with library, indeed it need substantial changes. 
Currently, I am looking for Webview approach. 
Will appreciate  to hear from  @descorp

**Comment by descorp** [comment]
Hey @LFMAKER 

Thank you for contribution! 💚
Your approach is 100% correct.

I am a bit concerned about patch itself - it contains irrelevant/build diffs and not easy to read thought.
Could you generate a PR out of this patch? We can verify it and officially add to `v.1.3.0`.

---

As you can see it is relatively easy to make it work on iOS.
Main reason it wasn't done on SDK just yet: `ActionHandler` on Android part is "custom made" for React native SDK.
Android v5 introduced "build-in" ActionHandler and we are looking to switch to it on upcoming v2.0.0

**Comment by LFMAKER** [comment]
@descorp Thanks! I will work on a PR with these changes, and I'll finish it next week.

**Comment by leofolive** [comment]
@descorp I attempted to integrate my patch with the latest develop code, but the transition to version 5 introduced significant changes, making it challenging to implement the same solution for Android. It seems I won't be able to proceed with the pull request under these circumstances. I believe I'll have to wait until version 2.0.0.

In the meantime, I'll continue using my 1.2.0 patch. 

I've encountered a challenge where the reference to the fragment obtained through findFragmentByTag(tag) consistently returns null. 

```
fun handle(fragmentManager: FragmentManager, action: Action, tag: String) {
            val fragment = fragmentManager.findFragmentByTag(tag) as GenericFragment<*, *>
            fragment.viewModel.handle(action)
        }
```

**Comment by leofolive** [comment]
Hey everyone, have we had any updates on this? 
@descorp

**Comment by descorp** [comment]
Hey @LFMAKER 

Standalone action handling is available now on `develop`, so you can archive stored card payment flow with combination of Client side encryption (CSE) and Standalone Action:
See [example here](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Utilities/payByID.js)

**Comment by descorp** [comment]
I am going to close this ticket. Feel free to continue discussion and provide feedback here.
