### ISSUE TITLE
[ANDROID] App got crashed when selecting Online Banking PL payment method

### ISSUE THREAD

**Issue by esack-n-lebara** [Adyen/adyen-react-native#246]
**Getting crash when selecting the payment method Online Banking PL**

**To Reproduce**

When the payment options were shown, selected the payment method Online Banking PL, app got crashed. Please refer the screenshot attached,

**Expected behavior**
Crash shouldn't happened when selecting the payment method.
**Screenshots**
<img width="185" alt="image" src="https://github.com/Adyen/adyen-react-native/assets/88027580/27fd9369-5ca3-4459-8d25-ca616d69d52f">

**Smartphone (please complete the following information):**
 - Device: Android Emulator - Pixel 4(Android 11) API level 30. 
 - OS: Android

**Additional context**
 This crash happens only on android. Thanks.

**Comment by ahsan-ali-lebara** [comment]
@descorp Can you please check this issue?

**Comment by descorp** [comment]
Approached in #250

**Comment by ahsan-ali-lebara** [comment]
When are you planning to release this fix? @descorp

**Comment by descorp** [comment]
Hey @ahsan-lebara 

we are aiming to release 1.1.0 in July.

**Comment by descorp** [comment]
Fixed on [1.1.0](https://github.com/Adyen/adyen-react-native/releases/tag/1.1.0)
