### ISSUE TITLE
onAdditionalDetails not called on some successful 3DS payments

### ISSUE THREAD

**Issue by EvertV** [Adyen/adyen-react-native#249]
**Describe the bug**
Some new users have a successful payment (0.02€ for us), but without payment method in our DB. This is because the function onAdditionalDetails is (sometimes) not being called by the adyen-react-native package. I can confirm this because of tracking that we added on these functions.

**Scope**
Not all users adding bcmc_mobile_app as a payment method have this issue. But it still happens regularly. 
- Both iOS and Android
- Before and after adyen-react-native package upgrade
- Not related to a specific bank or banking app
- While mostly bcmc_mobile_app, I also found issues on Visa Debit and Visa Credit (I assume the bank required 3DS action here) 

**To reproduce**
1. Try a Bancontact (or I assume any other 3DS) payment with a bunch of different devices and (Belgian?) banking apps until you find a device where it doesn't call onAdditionalDetails
4. Redirected to banking app (perform 3DS) & pay the required amount (0.02 EUR for us)
5. Get redirected back to the app
6. onAdditionalDetails (and onComplete / onError) is not called

**Examples**
PSP references can be found in Adyen Support Ticket #4016934. There's 1 specific case I'd like to mention here;

Client using the BNP Paribas Fortis app (same app as me, and I never had this issue):
- Jun 30, 2023, 13:33:29: 1st attempt, payment success, but no onAdditionalDetails call
- Jun 30, 2023, 13:51:18: 2nd attempt, payment success, but no onAdditionalDetails call
- Jul 3, 2023, 11:27:53: 3rd attempt, reinstalled the Poppy app a few days later and suddenly it worked (this surprised me)

The first 2 attempts have the payment method "Bancontact", but the last one has "Bancontact app". For me, also using BNP Paribas Fortis app, I always have Payment method "Bancontact app". The user confirmed to me that they didn't do anything different after reinstalling the app, they selected the same payment method, it opened the same banking app and suddenly it worked.

**Possible workaround**
I will start looking into the details that we get from the webhook. I think we can take the recurringDetailReference from the RECURRING_CONTRACT event and use cardSummary from the AUTHORISATION event for the paymentMethodDigits. If this works we have a workaround for people that experience this issue. However it results in a less optimal onboarding flow, since onComplete or onError don't get called by the adyen-react-native package when this issue occurs.

**Expected behavior**
onAdditionalDetails always gets called after 3DS payments

**Comment by descorp** [comment]
Hey @EvertV 

Were you able to figure this out?

**Comment by EvertV** [comment]
Hi @descorp , yeah the back-end workaround did the trick

> I will start looking into the details that we get from the webhook. I think we can take the recurringDetailReference from the RECURRING_CONTRACT event and use cardSummary from the AUTHORISATION event for the paymentMethodDigits. If this works we have a workaround for people that experience this issue. However it results in a less optimal onboarding flow, since onComplete or onError don't get called by the adyen-react-native package when this issue occurs.
