### ISSUE TITLE
3DS2 challenge issue

### ISSUE THREAD

**Issue by jbcampbell1** [Adyen/adyen-react-native#257]
Hello,

I am trying to add the 3DS2 challenge to our react-native app, I submitted a payment using test card:

4917 6100 0000 0000

and we received paymentAdditonalDetails as part of the response. I then call

`nativeComponent.handle(paymentAdditionalDetails.action)`

the content of this object is 

`{
   "type":"threeDS2",
   "paymentData":"Ab02b4c0!B....",
   "paymentMethodType":"scheme",
   "token":"eyJ0aHJ....",
   "authorisationToken":"Ab02b4X.....",
   "subtype":"fingerprint"
}`

In android after calling this code the app is just crashing completely and on IOS I get the following: 

onError {"message": "The data couldn’t be read because it is missing."}

Am I missing anything from this object or do I need to change the format of any of the content?

I read through the docs but as far as I can tell I don't think we are doing anything wrong. 
Any help would be greatly appreciated!

**Comment by jbcampbell1** [comment]
Hi, 

sorry still stuck on the same issue, I wondered if there was a way we could enable any additional logging within the component to try and identify our errors? 

The IOS message is not helpful and we are getting no error messages in android, the app is just crashing.

If it helps we are in the onSubmit function of the AdyenCheckout component (which again aligns with the docs)

Any help would be greatly appreciated

**Comment by descorp** [comment]
Hey @jbcampbell1 

Content above seems legit. 
Do you see any error if you debug in Xcode/Android Studio ?

Is it happen every time? Does it happen with other test cards (`5454 5454 5454 5454` ex) ?

**Comment by descorp** [comment]
Hey @jbcampbell1 

Were you able to resolve the problem?

**Comment by stuartmcvean** [comment]
@descorp We are still seeing this issue and have not been able to resolve it. We took the example project from this repository, replaced the APIClient with our backend endpoints, and this is the Android stack trace when the app crashes. We do not know how to debug further as we have no idea what directoryServerId is. Do you know what this could be? Could it be a configuration issue?

Note: this log is from an older Adyen API version but we get the same error with the newest Adyen API version, the only difference I noticed is the newer API had submitFingerprintAutomatically: true instead of false, and it uses the newer threeDS2 type with subtype fingerprint.

```09-18 15:48:21.589 28317 28317 D CO.DropInServiceKt: dispatching DropInServiceResult
09-18 15:48:21.591 28317 28317 D CO.DropInActivityKt: handleDropInServiceResult - Action
09-18 15:48:21.591 28317 28317 D CO.ActionHandler: handleAction - threeDS2Fingerprint
09-18 15:48:21.603 28317 28317 D CO.ActionHandler: handleAction - loaded a new component - Adyen3DS2Component
09-18 15:48:21.604 28317 28317 D CO.Adyen3DS2Component: identifyShopper - submitFingerprintAutomatically: false
09-18 15:48:21.658 28317 28317 E AndroidRuntime: FATAL EXCEPTION: main
09-18 15:48:21.658 28317 28317 E AndroidRuntime: Process: com.adyenexample, PID: 28317
09-18 15:48:21.658 28317 28317 E AndroidRuntime: com.adyen.threeds2.exception.InvalidInputException: directoryServerId must not be empty.
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.threeds2.util.Preconditions.requireNonEmpty(Unknown Source:2)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.threeds2.util.AdyenConfigParameters$Builder.build(Unknown Source:1)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.identifyShopper(Adyen3DS2Component.kt:206)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component.handleActionInternal(Adyen3DS2Component.kt:118)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.components.base.BaseActionComponent.handleAction(BaseActionComponent.java:56)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.ActionHandler.handleAction(ActionHandler.kt:78)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.ui.DropInActivity.handleAction(DropInActivity.kt:504)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.ui.DropInActivity.handleDropInServiceResult(DropInActivity.kt:469)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.ui.DropInActivity.handleDropInServiceResult(DropInActivity.kt:459)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.ui.DropInActivity.access$handleDropInServiceResult(DropInActivity.kt:91)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.ui.DropInActivity$serviceConnection$1$onServiceConnected$1$1.invoke(DropInActivity.kt:117)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.ui.DropInActivity$serviceConnection$1$onServiceConnected$1$1.invoke(DropInActivity.kt:117)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.service.DropInService$observeResult$2.emit(DropInService.kt:467)
09-18 15:48:21.658 28317 28317 E AndroidRuntime: 	at com.adyen.checkout.dropin.service.DropInService$observeResult$2.emit(DropInService.kt:467)

**Comment by descorp** [comment]
Hey @stuartmcvean 

`directoryServerId` could be empty if your backend triggering Web 3DS2 flow instead of mobile flow.
See [this ticket](https://github.com/Adyen/adyen-android/issues/453#issuecomment-897565277)

Try adding [allow3DS2](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_additionalData-AdditionalData3DSecure-allow3DS2) flag inside `additionalData`.

If no luck. please reach out to Adyen Support

**Comment by descorp** [comment]
Hey @stuartmcvean 

Were you able to resolve the issue?

**Comment by stuartmcvean** [comment]
Hi @descorp 

Yes, this issue can be closed. The backend API was with a different team and they had hardcoded the channel field in the payment requiest to 'web' which resulted in this error. Changing it to correctly pass ios or android solved the issue.
