### ISSUE TITLE
ReturnURL is unexpectedly called on android

### ISSUE THREAD

**Issue by stefkampen** [Adyen/adyen-react-native#262]
**Describe the bug**
When testing a failed payment flow in the React Native SDK on Android the returnURL is requested. However the documentation states that this is not the case.

**To Reproduce**
1. Start an iDeal payment
2. Choose Test Issuer Cancelled
3. Complete the cancelled payment
4. App is called back on the returnURL

**Expected behavior**
I expect the SDK to handle this (as mentioned in the documentation). Or for the documentation to more clearly indicate how to handle this on Android. ( https://docs.adyen.com/online-payments/build-your-integration/?platform=Cross-platform&integration=React+Native+Drop-in&version=1.0.0#make-a-payment )

I noticed the android documentation shows this: `Get this URL from Drop-in in the RedirectComponent.getReturnUrl(context).` However this function is not available in React Native as far as I know.

As a workaround I have now implemented this for generating the redirectUrl:
```
const getRedirectURL = () => {
   if (Platform.OS === "android") {
     return `adyencheckout://${DeviceInfo.getBundleId()}`;
   }
   return Config.APP_DEEPLINK;
 };
```

**Screenshots**
![Screenshot 2023-08-09 at 12 15 18](https://github.com/Adyen/adyen-react-native/assets/187132/e871080a-fc69-451d-9ab0-ceb7bda91f01)

**Comment by descorp** [comment]
Hey @stefkampen 

> I noticed the android documentation shows this: Get this URL from Drop-in in the RedirectComponent.getReturnUrl(context). However this function is not available in React Native as far as I know.

On Android React Native this is done by SDK - property `returnURL` is [populated](https://github.com/Adyen/adyen-react-native/blob/develop/src/AdyenCheckoutContext.tsx#L100) by `AdyenCheckout` (as you can see on a screenshot.)

All you need to do - set `returnURL` value to [Configuration](https://github.com/Adyen/adyen-react-native/blob/develop/src/Core/configuration.ts#L27) then [use the one SDK generates](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Views/Checkout/CheckoutView.js#L31) to request `\payments` on Adyen API; on iOS it will use your value, on Android - ignore it and assign new value generated by SDK.

**Comment by stefkampen** [comment]
I get this for the initialisation of the AdyenCheckout. But how would you handle this for the 3rd step in the documentation (calling the payments api)? Because a returnUrl is needed there too and it can't (magically) come from the SDK because you need to provide it yourself to the API call.

**Comment by descorp** [comment]
> Because a returnUrl is needed there too and it can't (magically) come from the SDK because you need to provide it yourself to the API call.

Good news - it is "magically" come from the SDK  :)
 
In example:

```js
<AdyenCheckout
  config={{ 
    returnUrl: 'my-app://adyen', // This will be used only on iOS
    ...
  }}
  onSubmit={(data, component) => {
    // data.returnUrl here contains passed-throught value for iOS or `adyencheckout://${DeviceInfo.getBundleId()}` for Android
    // you can pass `data.returnUrl` directly to /paymnets API call
  }}
  ...
  >
  ...
</AdyenCheckout>
```

**Comment by descorp** [comment]
As a side note:

If you are using component integration for standalone redirect PMs (ex. PayPal, Klarna), make sure you call [AdyenCheckout.handleActivityResult(requestCode, resultCode, data)](https://github.com/Adyen/adyen-react-native/blob/develop/example/android/app/src/main/java/com/adyenexample/MainActivity.java#L40-L44)

**Comment by stefkampen** [comment]
Thanks. Due to our backend team having strict rules about the backend API structure I have to restructure the incoming data from the onSubmit before sending it to our backends payments endpoint. And since it's not in the types of the interface I did not expect it over there.

As a suggestion is it possible to add it to the type of the PaymentMethodData?

**Comment by descorp** [comment]
> And since it's not in the types of the interface I did not expect it over there.

This is a good point!
Thanks for feedback @stefkampen 💚

---

PR #263

**Comment by descorp** [comment]
Release on [1.2.0](https://github.com/Adyen/adyen-react-native/releases/tag/1.2.0)
