### ISSUE TITLE
Tried integration apple pay but its getting failed

### ISSUE THREAD

**Issue by miniunikove** [Adyen/adyen-react-native#268]
**Describe the bug**
We are using the sdk provided to integrate the adyen payment gateway in our app. For cards its working fine i sandbox and production environment but apple pay is getting failed. We have checked with the adyen support as well and as per them the configuration is fine at the adyen merchant account.

**To Reproduce**
1. Go to 'Checkout page'
2. Click on 'Payment methods'
3. Scroll down to 'select apple pay and click on pay using passcode'

**Expected behavior**
Success screen should show but its showing error

**Screenshots**
![Simulator Screen Shot - iPhone 14 - 2023-08-21 at 21 55 09](https://github.com/Adyen/adyen-react-native/assets/142818535/4b6cf71c-6667-4a1e-b335-d2d3d08f652f)
its showing payment failed instead of asking for the passcode

**Smartphone (please complete the following information):**
 - Device: simulator iPhone 14

**Additional context**
We have installed all the certificate which we have created as part of setup the apple pay on adyen and using following as part of configuration 
 applepay: {
      merchantID: 'merchant.prod.tfs.com',
      merchantName: 'TheFragranceShopECOM',
    allowOnboarding: true
    },

Are we doing something wrong?

**Comment by descorp** [comment]
Hey @miniunikove 

It is not possible to test ApplePay on Simulator.
Please consider using physical device with [sandbox](https://developer.apple.com/apple-pay/sandbox-testing/) account and test cards in the wallet.

**Comment by miniunikove** [comment]
Hi @descorp 

We tried testing the same on real device as well with sandbox account but not moving ahead when we are clicking on pay button on apple pay screen.

![Skype_Picture_2023_08_22T06_49_29_020Z](https://github.com/Adyen/adyen-react-native/assets/142818535/92c2d621-46de-466a-81fa-32fde0ecc559)

**Comment by descorp** [comment]
Hey @miniunikove 

In your iOS app `AppDelegate` add:
```swift
#if DEBUG
    AdyenLogging.isEnabled = true
#endif
```

This will print out internal logs including ApplePay failure reason.

**Comment by miniunikove** [comment]
@descorp 

Added the same but still not getting any log or error from Adyen in android and iOS

also get reply from Adyen that .pem is creating issue so could you please help where we need to use .pem file path from apple pay

![image](https://github.com/Adyen/adyen-react-native/assets/142818535/fd3bf51a-2737-4849-9d85-baffeea8e566)

**Comment by descorp** [comment]
Hey @miniunikove 

> get reply from Adyen

You mean Adyen Support?

> .pem is creating issue 

Do you follow [Enable Apple Pay with your own certificate](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay/?tab=i_os_2#process-overview-1) guide **for iOS**?
**.pem** only needed for web sites.

**Comment by miniunikove** [comment]
Hello @descorp,

Yes from Adyen support. We have followed the https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay/#create-merchant-identity-certificate link but not able to get how to follow this. 

"When requesting an Apple Pay payment session, use the full path to the apple-pay-cert.pem file."

**Comment by descorp** [comment]
Please check "iOS" tab for iOS instructions:

![Screenshot 2023-08-28 at 14 28 10](https://github.com/Adyen/adyen-react-native/assets/2648655/d62a05f7-35f2-42e2-b7da-55425a711b42)

**Comment by miniunikove** [comment]
ok thats done so what can be reason for not getting any response. Either for appel pay or for cards.

**Comment by descorp** [comment]
@miniunikove 

Could you be more specific? 
What kind of response are you referring to?

**Comment by miniunikove** [comment]
We are not getting any response when we are doing payment. Not any success pr error in the attached methods.

![image](https://github.com/Adyen/adyen-react-native/assets/142818535/279a26f0-60dd-463b-a21f-edd157090411)

**Comment by descorp** [comment]
@miniunikove 

You should receive `onSubmit` callback.
If it is not happening - please check the lifecycle of your view:
Make sure you do not refresh the view hosting `AdyenCheckout` or any value related to it after `start()` is called.

It is also recommended to use `useCallback` instead of JavaScript functions.

---

If suggestion above do not help - please make a blank app where you reproduce the bug and share it with us.

**Comment by descorp** [comment]
Hey @miniunikove 

Any luck?

**Comment by miniunikove** [comment]
no

**Comment by descorp** [comment]
@miniunikove 

hm.. do you expect any help?
Were you able to follow up on [last comment](https://github.com/Adyen/adyen-react-native/issues/268#issuecomment-1695799301)?

**Comment by camil-adyen** [comment]
Closing for now due to inactivity.
