### ISSUE TITLE
Accessing / Requesting shipping address for Apple pay 

### ISSUE THREAD

**Issue by iyanushow** [Adyen/adyen-react-native#269]
**Is your feature request related to a problem? Please describe.**

Hi @descorp , not sure if this is available yet, but I need a way to access (or request) users shipping address when using apple pay. 

**Describe the solution you'd like**

From the iOS & web  integration documentation, I found that there are custom fields for requesting the shipping address(see [here](https://docs.adyen.com/payment-methods/apple-pay/ios-drop-in/#drop-in-configuration)). Could we have something similar for the react native integration 

**Additional context**

Would it also be possible to validate the shipping address information with custom validators

**Comment by descorp** [comment]
Hey @iyanushow 

This feature is on our backlog.
Expected ETA is Q4 ~~2024~~ 2023.

**Comment by iyanushow** [comment]
@descorp that's a bit too late for us. Is there anything we can do in the mean time?. 

Also does the apple pay integration at least send the token with the user's current stored shipping address even if they can't edit it ?

**Comment by descorp** [comment]
Hey @iyanushow 

Sorry for confusion. 
Expected ETA is Q4 2023.

If this is still to long:

> does the apple pay integration at least send the token with the user's current stored shipping address

No. One needs to request this property from Apple Pay, and this functionality is not yet available.
Unfortunately there is no React Native ApplePay library (unlike web or iOS), so to achieve that we need to meticulously wrap every property on Apple API in our ReactNative SDK.

>  Is there anything we can do in the mean time?.

You can always fork our SDK and propagate this property into config (https://github.com/Adyen/adyen-react-native/blob/develop/ios/Configuration/ApplepayConfigurationParser.swift#L10)
As an optional step - you can make PR to us, this will speedup our release :)

**Comment by iyanushow** [comment]
Thank you @descorp 
It's something I'll look into

**Comment by descorp** [comment]
Related PR #297

**Comment by descorp** [comment]
Release on [1.2.0](https://github.com/Adyen/adyen-react-native/releases/tag/1.2.0)
You can find new configurations documented [here](https://github.com/Adyen/adyen-react-native/blob/1.2.0/docs/Configuration.md)
