### ISSUE TITLE
Adyen Billing Address Country Field Android

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#272]
**Describe the bug**
Open Card with addressVisibility with 'full' mode. you can see the countries in drop down list. it's selecting the default first value. like you can see in the screenshot it select Afghanistan. Despite our countryCode is difference. But in IOS it's selecting the right country. Do we have any mechanism to pre select the country? because it's hectic to scroll the dropdown list. I'm unable to find any parameter that help me out.

**To Reproduce**
1. Open card with  addressVisibility: 'full'
2. CountryCode should be other than first default selected dropdown country. 
3. you can see default country is selected.

**Expected behavior**
Do we have anything to preselected this? as it's working fine for ios.

**Screenshots**
<img width="401" alt="Screenshot 2023-08-30 at 6 01 38 PM" src="https://github.com/Adyen/adyen-react-native/assets/33232649/697d441d-acec-4ff0-99e1-a6863dd5fa34">

**Smartphone (please complete the following information):**
 - Android
 - Simulator

**Comment by descorp** [comment]
Hey @faizantariq1 

There is no way to set default country on current version of RN "Drop-In and Components".
Will add to our backlog, thank you for suggestion! 💚

**Comment by descorp** [comment]
PR #301

**Comment by descorp** [comment]
Release on [1.2.0](https://github.com/Adyen/adyen-react-native/releases/tag/1.2.0)
