### ISSUE TITLE
DropIn does not show in version 1.1.0

### ISSUE THREAD

**Issue by RyanLinXiang** [Adyen/adyen-react-native#273]
**Describe the bug**
So far Adyen worked for us without problems. But with version 1.1.0 the following error appears whenever start('dropIn') is called:

```
Possible Unhandled Promise Rejection (id: 0):
Error: Unknown payment method or native module. 

Make sure your paymentMethods response contains: dropIn
Error: Unknown payment method or native module. 

Make sure your paymentMethods response contains: dropIn
```

Any idea? I can't find any change logs in 1.1.0 which tells to use the drop in in a different way ...

**Comment by descorp** [comment]
Hey @RyanLinXiang 

What was your previous version?

**Comment by RyanLinXiang** [comment]
1.0.0

**Comment by descorp** [comment]
I see..
Could you try `dropin` instead of `dropIn` ?
We have noticed that some payment method types are case-sensitive and changed this on 1.1.0

**Comment by RyanLinXiang** [comment]
works! Thanks!
