### ISSUE TITLE
3DS2 not working with Google Pay

### ISSUE THREAD

**Issue by Akatroj** [Adyen/adyen-react-native#275]
**Describe the bug**

When I tried using Google Pay with a 3ds visa card ([4917 6100 0000 0000](https://docs.adyen.com/development-resources/testing/test-card-numbers/#test-3d-secure-2-authentication)) on the example app, I got an error saying that the action is not supported.

**Expected behavior**
3ds for google pay works the same as when using `scheme` method

**Screenshots**
<img width="412" alt="image" src="https://github.com/Adyen/adyen-react-native/assets/46789820/2fe66115-0a6b-424b-9d07-9cee84bf7590">

**Comment by Akatroj** [comment]
I wasn't sure if this is duplicate of https://github.com/Adyen/adyen-react-native/issues/245, because the issue description talks only about saved payment methods

**Comment by descorp** [comment]
Hey @Akatroj 

Are you calling `GooglePay` as standalone component or as part of DropIn ?

**Comment by Akatroj** [comment]
This is standalone, I'm using your example app.

**Comment by descorp** [comment]
Currently `handle` function [disabled](https://github.com/Adyen/adyen-react-native/blob/develop/src/AdyenNativeModules.tsx#L62) on GooglePay component.
We can enable it for 1.2.0
Problem is - not all GooglePay 3DS flows are supported on current v4 version of Android SDK.

Does the same card work if you try via DropIn ?

**Comment by Akatroj** [comment]
Tested right now - it's working with dropin, however we would prefer to use components for app integration as it fits better  with our current UX.

I also noticed a similar problem happening with using AdyenCSE:
<img width="416" alt="image" src="https://github.com/Adyen/adyen-react-native/assets/46789820/ff75ec38-ef8e-4f99-8120-b7d0320b75bc">

I don't see any api to handle actions using AdyenCSE component

**Comment by descorp** [comment]
So the are 2 missing feature on 1.1.0:

1) Standalone action handling - #245 - will be added on 2.0.0
2) GooglePay 3DS action handling - #275 - will be added on 1.2.0

**Comment by Cattari** [comment]
Hi, guys! @descorp what is the ETA for implementing 3DS2 for Google Pay? When can we expect the release?

**Comment by descorp** [comment]
Hey @Cattari 

Sorry for long wait.
We are going to asses if this is possible to provide 3DS handling for GooglePay Component within current 1.2.0

**Comment by Cattari** [comment]
@descorp Got it, but what is the approximate timeline, dates for the 1.2.0 release?

**Comment by descorp** [comment]
Hey @Cattari @Akatroj 

We found an internal issues with testing and verifying 3DS flow for Google Pay.
We decided to provide more research, so this issue will be addressed it on v2.0.0

ETA of v2.0.0 is Q4 2023.
Thanks you for your patience.

**Comment by camil-adyen** [comment]
This issue has been resolved in v2.0.0-BETA.
