### ISSUE TITLE
onSubmit not working also not showing the console log 

### ISSUE THREAD

**Issue by mgnikdev** [Adyen/adyen-react-native#276]
```js
  <AdyenCheckout
    config={  {
        environment: 'test', 

        clientKey: 'Key',

        countryCode: "NL",
        amount: { currency: "EUR", value:300 }, // Value in minor units
        returnUrl: 'myapp://payment',
        showStorePaymentField:false 
      }}
    paymentMethods={paymentMethods}
    onSubmit={(paymentData, component) => {
      console.log("onSubmit is called", paymentData, component);
      subPay();
    }}
 onAdditionalDetails={(paymentData, component) => {
      // subPayDetail();
        console.log("Detail");

    }}
    onError={(error, component) => {
        console.log("error",error);

    }}
  >
    <MyCheckoutView />
  </AdyenCheckout>
  ```

**Comment by descorp** [comment]
Hey @mgnikdev 

I assume you successfully opening the DropIn/Component, but pressing "submit" do not trigger `onSubmit` ?

**Comment by mgnikdev** [comment]
yes i tried to click on pay button but there is no response on it ..

**Comment by mgnikdev** [comment]
can you tell me the exact way of calling with android

**Comment by descorp** [comment]
@mgnikdev 

I suspect the problem with the state of the view where `<AdyenCheckout ></AdyenCheckout >` is placed - if `AdyenCheckout` regenerated after Drop-In/Component was presented - it will lost reference to event listeners created  previous.

1) Try using React's [useCallback](https://react.dev/reference/react/useCallback) instead of simply assigning callback:
2) Make sure `paymentMethods` does not change while after Drop-In/Component was presented

If nothing helps - please create a small blank project where you can reproduce the bug and share it with us!
Thanks

**Comment by mgnikdev** [comment]
[PaymentComponent.js.zip](https://github.com/Adyen/adyen-react-native/files/12544932/PaymentComponent.js.zip)
this is my sample code as you said i tried but still i didn't get any output can u show the code tell me where i was wrong

**Comment by mgnikdev** [comment]
[PaymentComponent.js 2.zip](https://github.com/Adyen/adyen-react-native/files/12550930/PaymentComponent.js.2.zip)

ok i got the log and also got the "resultCode":"Authorised" from payment api but now problem is spinner (loading) not stop

**Comment by mgnikdev** [comment]
and also payments/details api showing every time "message": "Invalid redirectResult provided", err

**Comment by descorp** [comment]
Hey @mgnikdev 

> now problem is spinner (loading) not stop

You expected to dismiss `AdyenCheckout` by calling `component.hide(true | false)`.

**Comment by descorp** [comment]
Hey @mgnikdev 

Were you able to resolve the issue?

**Comment by BenSagir** [comment]
i am experiencing similar behaviour.
on Android (Release versions only), when hit the pay button on the SDK its infinite loading and not triggering the onSubmit function. 

react-native version : 0.70.1
@adyen/react-native version : 1.2.0

this functionality used to work on previous build of mine. 
@descorp is there any dependencies that might block this functionality?

**Comment by descorp** [comment]
Hey @BenSagir 

> on Android (Release versions only)

Are you using Proguard or some form of obfuscation?
Like in `build.gradle`:

```gradle
buildTypes {
        release {
            minifyEnabled true
        }
    }
```

**Comment by BenSagir** [comment]
> Hey @BenSagir
> 
> > on Android (Release versions only)
> 
> Are you using Proguard or some form of obfuscation? Like in `build.gradle`:
> 
> ```groovy-gradle
> buildTypes {
>         release {
>             minifyEnabled true
>         }
>     }
> ```
Hello @descorp thanks for the quick respond

i am not using Proguard and the minifyEnabled is set to false.

in fact i was checking my code for my last working android version and there was no code change in the project regarding android or the payment flow. thats why its weird...

**Comment by descorp** [comment]
Hey @BenSagir 

Any luck?
