### ISSUE TITLE
Can't build for iOS if project has app extension

### ISSUE THREAD

**Issue by lordkiz** [Adyen/adyen-react-native#277]
**Describe the bug**
Can't build for iOS probably because the `"Adyen", '4.10.4'` dependency in the podspec which in turn depends on `AdyenNetworking v1.0.0` which has code that uses `UIApplication.shared` which is explicitly forbidden in Extensions if the `Require Only App-Extension-Safe API` flag is YES.

**To Reproduce**
To a RN app that has an extension target, add the add the `adyen-react-native` lib

**Expected behavior**
App Can build

**Screenshots**
![Screenshot 2023-09-08 at 14 09 00](https://github.com/Adyen/adyen-react-native/assets/18648835/ee5394b2-de1b-4d68-afff-e5d425feb628)

**Desktop (please complete the following information):**
 - OS: iOS
 - Xcode: Version 14.3.1 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by descorp** [comment]
Hey @lordkiz 

This is known limitation on iOS v4 due to `AdyenNetworking v1.0.0`.
It was fixed on iOS v5 with update to `AdyenNetworking v2.0.0`.

At the moment there is no known fix.
We are looking to update our React-Native to v5 iOS and Android in Q4 2023.

**Comment by descorp** [comment]
This was fixed on v2.0.0-BETA
