### ISSUE TITLE
Payment logos not shown in drop-in

### ISSUE THREAD

**Issue by RyanLinXiang** [Adyen/adyen-react-native#279]
**Describe the bug**
Suddenly in the drop-in no payment provider icons are shown in Android in sandbox environment. In iOS it just works fine. It does not work even in older branches so I guess must be related to Adyen backend?

Screenshot:

![image](https://github.com/Adyen/adyen-react-native/assets/59595349/15a82985-098c-43d3-ba98-7c5177c26e4f)

**To Reproduce**
1. Open drop in in Android

**Expected behavior**
Payment methods are shown with their logos

Adyen React Native version 1.1.0

**Comment by camil-adyen** [comment]
Hi @RyanLinXiang, we made some changes on our side. Can you please confirm that this issue is solved?

**Comment by YankovWeb** [comment]
@camil-adyen Is working now !
