### ISSUE TITLE
Need to have logos only for the supportive cards

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#280]
**Describe the bug**
On Credit/Debit Card Screen we have logos that's order is different for IOS and Android. Can we change the order of the cards? or can we hide/show the cards according to requirement?

**To Reproduce**
1. Just Open Card
2. See the logos highlight in screenshot.

**Screenshots**
![Simulator Screen Shot - iPhone 12 - 2023-09-18 at 16 14 21](https://github.com/Adyen/adyen-react-native/assets/33232649/2bb3a06c-70d1-4663-9c7b-049a4ac2d382)

**Comment by camil-adyen** [comment]
Hey @faizantariq1, 

You can use the allowedCardTypes parameter to filter out brands that are actually supported. This is also mentioned in our [docs](https://docs.adyen.com/payment-methods/cards/react-native-drop-in/#optional-configuration).

**Comment by faizantariq1** [comment]
@camil-adyen  is there any option exist, for changing order of the cards?

**Comment by camil-adyen** [comment]
You can use the same parameter for that. The logos are presented based on the order of the brands in the array.
