### ISSUE TITLE
Flutter SDK

### ISSUE THREAD

**Issue by baptistesx** [Adyen/adyen-react-native#281]
Does Adyen plan to develop a Flutter SDK?
I need to integrate Twint payment in my mobile app, and no payment provider has a Flutter SDK. It would be very nice to have, and could allow you to get new clients if you're the only provider to propose this sdk.

thank you

**Comment by camil-adyen** [comment]
Hi @baptistesx, we are currently investigating the development of a Flutter SDK. No concrete timelines as of now, but keep an eye out for future updates.

**Comment by descorp** [comment]
Good news,

Our official Flutter SDK is out https://github.com/Adyen/adyen-flutter 🎉
