### ISSUE TITLE
Apple pay is not showing 

### ISSUE THREAD

**Issue by miniunikove** [Adyen/adyen-react-native#283]
**Describe the bug**
apple pay is not showing in the payment methods

**To Reproduce**
1. Go to payment method
2. Click on select other payment method
3. apple pay is not showing in android google pay is showing

**Expected behavior**
as sandbox card is added it should show apple pay

**Screenshots**
![image](https://github.com/Adyen/adyen-react-native/assets/142818535/d5bf05a3-cc09-4251-a49e-28ef5213b16e)

![image](https://github.com/Adyen/adyen-react-native/assets/142818535/1d92c9f5-e8c8-4630-8fab-4166c1a0597c)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: os-13

**Additional context**
in checkoutview.js added 
applepay: {
                merchantID: 'merchant.prod.tfs.com',
                merchantName: 'TheFragranceShopECOM',
                allowOnboarding: true,
              },

**Comment by descorp** [comment]
Hey @miniunikove 

Is [ApplePay configured](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay/?tab=i_os_2#process-overview-1) on your Customer Area ?
Do you send correct [`channel`](https://docs.adyen.com/api-explorer/Checkout/68/post/paymentMethods#request-channel) for `/paymentMethods` request ? (ex. `iOS`)

**Comment by miniunikove** [comment]
Hi Team, Yes we are passing channel and apple pay is configured on the Adyen account. In simulator it is showing apple pay but on iPhone its not showing.

```js
export const CHANNEL = Platform.select({
  ios: () => 'iOS',
    android: () => 'Android',
})();  
```

**Comment by descorp** [comment]
@miniunikove 

> In simulator it is showing apple pay but on iPhone its not showing.

Did you follow all the steps in [the Enable Apple Pay](https://developer.apple.com/help/account/manage-identifiers/enable-app-capabilities#enable-apple-pay) guide?

**Comment by camil-adyen** [comment]
Hi @miniunikove, have you been able to resolve the issue?

**Comment by camil-adyen** [comment]
Closing for now due to inactivity.
