### ISSUE TITLE
OnAdditionalDetails suppresses Alerts in Android

### ISSUE THREAD

**Issue by RyanLinXiang** [Adyen/adyen-react-native#285]
**Describe the bug**
When I try to call Alert.alert in the onAdditionalDetails callback - it would be suppressed. This does not happen however in other callbacks as onError. Happens on Android only - in iOS everything works fine.

**To Reproduce**
Enter the following (it is invalid card for Adyen) card# 5201 2829 9900 5515, expiration 03/30, code 737 in Android 

**Expected behavior**
App shows alert that payment failed

**Comment by descorp** [comment]
Hey @RyanLinXiang 

This is known limitation on Android.
Unfortunately, it take some time for Activity to be dismissed on Android.

We have solution for this. It will be introduced on RN 2.0.0.
In a meanwhile you can await for around 400 ms or use [forced](https://github.com/Adyen/adyen-react-native/compare/develop...android_handle_alert) alert via new activity.

**Comment by RyanLinXiang** [comment]
OK - perfect. With the timeout it works!

**Comment by camil-adyen** [comment]
Closing this ticket due to inactivity. Feel free to reopen if it's still relevant.
