### ISSUE TITLE
Blik taking too much time to give response

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#287]
**Describe the bug**
(checking on test environment)Doing transaction with Blik and using test code. so it's move to native component of adyen. and it's talking so much time to giving us response. it's taking around 15 mints to give us response that's what i observe.

**To Reproduce**
1. open blik
2. add code and click on pay.

**Expected behavior**
response should be much faster.

**Screenshots**
![Simulator Screen Shot - iPhone 12 Pro - 2023-10-03 at 12 43 18](https://github.com/Adyen/adyen-react-native/assets/33232649/b1551cfc-c2d6-41fc-a740-1493075fa634)

**Smartphone (please complete the following information):**
 - IOS
 - Simulator

**Comment by descorp** [comment]
Hey @faizantariq1 

Is this TEST or LIVE?

**Comment by faizantariq1** [comment]
Hi @descorp ,
it's test.

**Comment by descorp** [comment]
Hey @faizantariq1 

Sorry for delay.
Our Blik flow on TEST is broken since some time.
For now we advise to perform a penny test in LIVE

**Comment by camil-adyen** [comment]
Hi @faizantariq1, were you able to resolve this issue?

**Comment by faizantariq1** [comment]
Hi @camil-adyen , It was working fine in production, so I decided to leave it as it was at that time.

**Comment by descorp** [comment]
Thanks @faizantariq1 

I am closing this ticket then :)
Fee free to continue discussion here if needed.
