### ISSUE TITLE
Drop-in cancel button not working when clicked cancel on Paypal payment method

### ISSUE THREAD

**Issue by vijay6162** [Adyen/adyen-react-native#295]
**Describe the bug**
Drop-in cancel button not working when clicking on cancel test on paypal screen.

**To Reproduce**
1. Going to drop-in
2. Click on paypal payment method
3. Observe that paypal login screen will open
4. When we click cancel on paypal login screen paypal popup is closing and dropin cancel button not working

**Expected behavior**
     Drop-in cancel button should work when coming back from any payment type or it should call any callbacks where we can handle the cancel part

**Screenshots**
https://github.com/Adyen/adyen-react-native/assets/42997076/9ea6ffc0-6611-4675-b4b4-928d0dabdc08

**Smartphone (please complete the following information):**
 Device: iOS 13
 OS: macOs Monterey
 Platform: React Native v0.67.5 [ Both Android & iOS ]
 Adyen version: @adyen/react-native : ^1.1.0

**Additional context**
Just Fyi configuration object is same as mentioned in adyen doc
     <AdyenCheckout
      config={configuration}
      paymentMethods={paymentMethods}
      onSubmit={(state,component) => { console.log(state,component) }}
      onAdditionalDetails={(state,component) => { console.log(state,component) }}
      onError={(state,component) => { console.log(state,component) }}
      onComplete={(state,component) => { console.log(state,component) }}>
        <AdyenCheckoutView />
    </AdyenCheckout>

**Comment by descorp** [comment]
Hey @vijay6162 

Was "cancel" button working before opening PayPal?

**Comment by vijay6162** [comment]
> Hey @vijay6162
> 
> Was "cancel" button working before opening PayPal?

Yes it is working, On selecting card payment also its working, but not incase of paypal

**Comment by descorp** [comment]
@vijay6162 

When "cancel" clicked the callback `onError` expected to get triggered.
Does it happening?

Same behaviour on both iOS and Android?
After closing PayPal, can you still make a payment with card?

---
We [recently updated](https://github.com/Adyen/adyen-react-native#opening-payment-component) docs. We recommend using `useCallback` from React. This will make sure that callback is not recreated, hanse not missing.
Could you check if this makes any difference ?

**Comment by vijay6162** [comment]
@descorp ,

In android it's working fine, but in iOS its not working and, I can confirm that we are using class component here since complete checkout component is written using class component

After closing payPal we are not being able to make second payment again in IOS.

**Comment by descorp** [comment]
@vijay6162 

> On selecting card payment also its working, but not incase of paypal.

Can you [successfully complete](https://docs.adyen.com/payment-methods/paypal/ios-drop-in/#test-your-integration) PayPal flow?
Can you successfully complete a full 3DS flow (with action)?

> After closing payPal we are not being able to make second payment again in IOS.

Are you using `useCallback` ?
This behaviour may occur if `<AdyenCheckout></AdyenCheckout>` element on your "Checkout" page or it's callbacks was recreated. Without `useCallback` re-rendering of UI may regenerate callback functions.

I see that there is a loading bar on top happening during "/payment" request. Any chance it cause re-rendering of other parts of UI?

> In android it's working fine

Does the page that hosting `<AdyenCheckout></AdyenCheckout>` have different behaviour on iOS and Android?

**Comment by vijay6162** [comment]
Hey @descorp ,
I cannot complete 3DS flow and Paypal flow since my onAdditonalSubmit is not being triggered.

Yes im using useCallback for Dropin function 

```js
  const onPaymentSubmit = useCallback(
    (resp, component) => {
      onAdyenPaymentSubmit(resp, component);
    },
    [configuration],
  );

  const doThirdPartyAction = useCallback(
    (resp, component) => {
      onAdditionalDetailsSubmit(resp, component);
    },
    [configuration],
  );

  const onErrorCallback = useCallback(
    (resp, component) => {
      onAdyenPaymentError(resp, component);
    },
    [configuration],
  );

  const onPaymentComplete = useCallback(
    component => {
      onAdyenPaymentComplete(component);
    },
    [configuration],
  );

  return (
    <AdyenCheckout
      config={configuration}
      paymentMethods={removeNullValuesFromResponses(paymentMethods)}
      onSubmit={onPaymentSubmit}
      onAdditionalDetails={doThirdPartyAction}
      onError={onErrorCallback}
      onComplete={onPaymentComplete}>
        <AdyenCheckoutView />
    </AdyenCheckout>
  );
```

The loading bar is just to display payment api is being called.No its not causing any re-rendering.
 
In android the flow is working fine  [ i.e cancel button on dropin in android ]

**Comment by descorp** [comment]
@vijay6162 

> I cannot complete 3DS flow and Paypal flow since my onAdditonalSubmit is not being triggered.

This is exactly what I thought..
Something is triggering re-generation of view tree while (or after) `\payments` request.

> The loading bar is just to display payment api is being called.No its not causing any re-rendering.

Is this external library ? Does it work differently for iOS and Android ?

---

Could you create a blank project and mimic your "checkout" page structure so we can reproduce this issue on our side?

**Comment by vijay6162** [comment]
> @vijay6162
> 
> > I cannot complete 3DS flow and Paypal flow since my onAdditonalSubmit is not being triggered.
> 
> This is exactly what I thought.. Something is triggering re-generation of view tree while (or after) `\payments` request.
> 
> > The loading bar is just to display payment api is being called.No its not causing any re-rendering.
> 
> Is this external library ? Does it work differently for iOS and Android ?
> 
> Could you create a blank project and mimic your "checkout" page structure so we can reproduce this issue on our side?

No its just a progress bar. and it works same on both android and ios.

I don't think its issue related to triggering re-generation because i have kept static response from postman and called the adyen  handle action but unable to trigger the onAdditionalSumit.

Let me create a blank project and get back to you.

**Comment by descorp** [comment]
Hey @vijay6162 

We were trying to replicate similar behaviour locally.
In you console log, when you have this issue and click on "X" - do you see warning like:

```
 WARN  Sending `didFailCallback` with no listeners registered.
```

**Comment by descorp** [comment]
Hey @vijay6162 

Were you able to resolve this?
