### ISSUE TITLE
Question: Disable Save toggle in new Credit Card Payment

### ISSUE THREAD

**Issue by Alieltahan** [Adyen/adyen-react-native#299]
**Is your feature request related to a problem? Please describe.**
I would like to disable the toggle to save the Credit Card conditionally but not always.

**Describe the solution you'd like**
I don't want the customer to toggle the Save Card switch in some cases (The customer is subscriber and should save the card before subscription).

**Comment by descorp** [comment]
Hey @Alieltahan 

There is [configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#card-component) `showStorePaymentField ` that allows you to hide the toggle.
Is this something you are looking for?

**Comment by Alieltahan** [comment]
@descorp 
Thank you for your support, What I want is to disable the toggle : "Remember for next time.   ```toggle```"

so the user doesn't have the option to enable or disable it ( also hiding it from the form is fine )
![image](https://github.com/Adyen/adyen-react-native/assets/46691446/1d93c3c3-84c8-4461-80b0-5116a790d13a)

**Comment by descorp** [comment]
@Alieltahan 

`showStorePaymentField` is exactly what you need :)
Have you tried setting it to **false** ?

You can find example in [Configuration.md](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#example)

![Screenshot 2023-10-31 at 16 52 19](https://github.com/Adyen/adyen-react-native/assets/2648655/5fbb6c64-b8e6-457e-aee3-0740d8672ca5)

**Comment by Alieltahan** [comment]
Hello @descorp 
Thank you once again for your extended support, this definitely correct and disable the Store Payment Toggle.

Have a great day ahead.
