### ISSUE TITLE
Event listeners not cleaning up causing multiple payments

### ISSUE THREAD

**Issue by piccialessandro** [Adyen/adyen-react-native#302]
**Describe the bug**
Probably the same issue as https://github.com/Adyen/adyen-react-native/issues/44
Using drop in,
Say I complete payment A. After that I complete payment B, the onSubmit is called twice, once for payment A and once for payment B, etc. for every consecutive payment.
I believe this line https://github.com/Adyen/adyen-react-native/blob/8fb3bc0a2938278136a494afda14eeb858918b71/src/AdyenCheckoutContext.tsx#L129 does not properly clean up previous attached listeners 

**To Reproduce**
1. Follow example using drop in
2. Complete a payment
3. Complete another payment
4. The following one gets called N times, with info from prev payments

**Expected behavior**
The didSubmit should be called only once and only for the last payment

**Smartphone (please complete the following information):**
 Any mobile device, any OS version

**Additional notes**
Closing the app resets the behaviour

Thank you.

**Comment by descorp** [comment]
Hey @piccialessandro 

What version of ReactNative and our sdk you are using?

In our experience the problem usually the opposite - `subscriptions` got deleted prematurely 😅

`removeEventListeners` supposed to be called when `<AdyenCheckout>` got unmounted and when new payment started.
Any chance that you create multiple instances of `<AdyenCheckout>` that stays in memory?
I can imagine in this case old one still responding to events if it wasn't removed from view hierarchy but `start` was called on a new instance 🤔

---

Could you reproduce this behaviour on blank project and share with us?

**Comment by piccialessandro** [comment]
Hi @descorp
React native 0.70.13
@adyen/react-native 1.1.0

We do not create multiple instances of the component, also after every payment completed we pop the entire checkout stack

Edit: I've just checked by adding a console.log to your removeEventListeners callback and it actually gets called after the stack is popped. So the listeners should be removed and nothing should still be in memory

**Comment by descorp** [comment]
Thanks @piccialessandro 

Nothing looks out of ordinary indeed. 🤔

> Edit: I've just checked by adding a console.log to your removeEventListeners callback and it actually gets called after the stack is popped. So the listeners should be removed and nothing should still be in memory

When you get a breakpoint, does the `subscriptions` collection contains any elements?

---

Unfortunately the only way to get to the bottom of this - if we can reproduce it locally.
Could you try reproducing this on "Example app" provided alongside the SDK or on a blank project?

**Comment by descorp** [comment]
Hey @piccialessandro 

Any luck?

**Comment by piccialessandro** [comment]
Hi @descorp , solved it.
The event listeners collection was actually empty and it was a bit of a pain to debug.
The main screen component was switching between a loading component and the adyen context wrapper under an if statement. That seems to be causing multiple renders of the wrapper. Even though the component was rendering just 1 time, the event listeners were attaching many times.
We moved the loading conditions inside of the view wrapped inside AdyenCheckout and it's all good.
Thank you

**Comment by descorp** [comment]
Thanks @piccialessandro for confirming.

This is indeed known cavity that we will look to address in future version.
