### ISSUE TITLE
[JEST TEST] - crash on jest test

### ISSUE THREAD

**Issue by gkueny** [Adyen/adyen-react-native#321]
**Describe the bug**

Hello,

In our app, we have some `jest` tests to assert that our Adyen integration work as expected.
We recently upgraded from `1.0.0-rc2` to `1.2.0` and our tests fails with:

```
  ● Test suite failed to run

    Cannot find module './../../../package.json' from 'node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/post-telemetry.js'

    Require stack:
      node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/post-telemetry.js
      node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/Analytics.js
      node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/index.js
      node_modules/@adyen/react-native/lib/commonjs/AdyenCheckoutContext.js
      node_modules/@adyen/react-native/lib/commonjs/index.js
      [...]
```

see https://github.com/Adyen/adyen-react-native/blob/184c233d3b35162635376c25e1bfa5b76bc8ba25/src/Core/Analytics/post-telemetry.ts#L4

**To Reproduce**

- Create a project with @adyen/react-native
- Setup a component with  @adyen/react-native
- Test this component with `jest`

**Expected behavior**

No crash

**Workaround**

Manually create a `package.json`

```bash
echo '{ "version": "1.2.0" }' > node_modules/@adyen/react-native/lib/package.json
```

**Additional Request**

If possible, I think some documentation and a mock of the library ready to use will facilitate test integration.

For information to test component with `@adyen/react-native` with have this mock:
```ts
import { NativeModules } from 'react-native';

NativeModules.AdyenDropIn = {};
NativeModules.AdyenInstant = {};
NativeModules.AdyenApplePay = {};
NativeModules.AdyenGooglePay = {};
NativeModules.AdyenCSE = {};

module.exports = {
  ...require('@adyen/react-native'),
  useAdyenCheckout: {
    start: jest.fn(),
  },
 AdyenCheckout: jest.fn(),
};
```

And we mock also react-native NativeModules :

```ts
jest.mock('react-native/Libraries/BatchedBridge/NativeModules', () => ({
  [...], // see https://gist.github.com/sibelius/c345f4577be678d313db7a2868984623
  SettingsManager: {
    settings: {
      AppleLocal: 'pt-br',
      AppleLanguages: ['pt-br'],
    },
  },
}));
```

**Comment by descorp** [comment]
Hey @gkueny 

Thanks for the feedback!
We will add it to our backlog to make a JS-side test.

TBH, we have not yet investigated JEST tests. This library is a thin layer between native SDKs and React Native, hence to cover it with tests, one needs to mock 95% of the code.

**Comment by gkueny** [comment]
Okey thank you.

> TBH, we have not yet investigated JEST tests. This library is a thin layer between native SDKs and React Native, hence to cover it with tests, one needs to mock 95% of the code.

Yah I understand. I don't think your library needs js tests. But the library's users will probably be doing some on their own to test their integration (like us), and this will inevitably involve a partial mock of your library (which doesn't currently work without manual creation of the `package.json` file in the `lib` subfolder).

**Comment by descorp** [comment]
BTW @gkueny 

We have `package.json` at the root of the project.
Is it possible to do `node_modules/@adyen/react-native/package.json` instead ?

**Comment by gkueny** [comment]
> Is it possible to do node_modules/@adyen/react-native/package.json instead ?


Yes! 
but not really important in the context of our tests

**Comment by descorp** [comment]
@gkueny 

Help me understand:
You expect us to add one additional `package.json` to **lib** folder?
Should it be a copy of the one from root but with adjusted path?

Maybe you can make a PR?

**Comment by gkueny** [comment]
Hello @descorp,

I have to admit that I don't know what would be the best fix for your lib.

What I'm seeing at the moment is that in the context of a `jest` test, this line https://github.com/Adyen/adyen-react-native/blob/184c233d3b35162635376c25e1bfa5b76bc8ba25/src/Core/Analytics/post-telemetry.ts#L4 is a problem because the package.json doesn't exist (because on runtime, the file path is `node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/post-telemetry.js` in the contexte of our `jest` test)

Cf stacktrace:

```
  ● Test suite failed to run

    Cannot find module './../../../package.json' from 'node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/post-telemetry.js'

    Require stack:
      node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/post-telemetry.js
      node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/Analytics.js
      node_modules/@adyen/react-native/lib/commonjs/Core/Analytics/index.js
      node_modules/@adyen/react-native/lib/commonjs/AdyenCheckoutContext.js
      node_modules/@adyen/react-native/lib/commonjs/index.js
      [...]
```

One solution would be to copy your `package.json` into the `./lib` folder when you build to npm. 

Or maybe it's possible to update the `require` path on your build to npm ?

**Comment by gkueny** [comment]
> Maybe you can make a PR

Can you point me to the file(s) responsible for the publishing process?
I think the best thing to do would be to copy the package.json file at that point.

**Comment by Seamus1989** [comment]
any update on this?

**Comment by descorp** [comment]
@Seamus1989 @gkueny 

The block of code causing this issue was removed on v2-BETA. That fixes the issue.
Migration from v1 to v2 expected to be seamless, so if you feel courage to try BETA version - feel free to do so :)

**Comment by camil-adyen** [comment]
Hi @gkueny / @Seamus1989 , I'm closing this issue for now. Feel free to reopen if it's not solved.
