### ISSUE TITLE
Drop-in component hangs when calling component.handle (Android)

### ISSUE THREAD

**Issue by lachlanmcbride** [Adyen/adyen-react-native#328]
**Describe the bug**
When calling `component.handle(response)`, Adyen drop-in component will hang in a loading state and become unresponsive. This happens when `action.type` is both `"threeDS2"` and `"redirect"`. Other types have not been tested.

The redirect can be forced by hot-reloading the JS bundle. Upon submitting a valid code in the redirect window, redirection back to the app is successful, but the drop-in component will remain in a hung state until the JS code is hot-reloaded again.

Exact same code works correctly on iOS.

**To Reproduce**
1. Install RN SDK and follow step 1 and 2 of [Android integration](https://github.com/Adyen/adyen-react-native?tab=readme-ov-file#android-integration)
2. Implement payment flow as per [documentation](https://github.com/Adyen/adyen-react-native?tab=readme-ov-file#opening-payment-component)
3. Inside the `onSubmit` handler, call `/make_payment` and with the valid response body, call `component.handle(response)`
4. Observe the component hanging in the loading state

_When called, navbar changes color to indicate re-direct is occurring, but then immediately freezes up_

**Expected behavior**
Calling `component.handle(response)` should trigger a redirect to the redirect URL, or the 3DS handler.

**Screenshots**
<img width="200" alt="Screenshot 2023-12-04 at 1 46 45 pm" src="https://github.com/Adyen/adyen-react-native/assets/82347851/d146d37e-14c3-4dd0-afa9-9e44258f1395"><img width="600" alt="Screenshot 2023-12-04 at 1 46 45 pm" src="https://github.com/Adyen/adyen-react-native/assets/82347851/30295770-82e4-4d2b-b041-471148c401b9">

**Screenshot 1:** App immediately after `component.handle(response)` is called
**Screenshot 2:** Logcat logs immediately after`component.handle(response)` is called

**RN Version:** v0.71.7
**SDK Version:** v1.2.0

**Comment by descorp** [comment]
Hey @lachlanmcbride 

Thank you for reporting this.
From the logs it is clear that 3DS2 component was launched as expected.
I assume that both 3DS2 flow and redirect have issue with opening Android in-app browser 🤔

Is this an emulator or physical device?

**Comment by lachlanmcbride** [comment]
Hi @descorp 

> I assume that both 3DS2 flow and redirect have issue with opening Android in-app browser 🤔

I agree this seems to be the issue

> Is this an emulator or physical device?

This has been tested on both physical device and emulator.

**Some additional info:**

1. I'm integrating the Advanced Payment Flow and sending requests to Checkout API v70
2. PSP of a **successful** iOS flow `LQMT7D4XCTGLNK82`
3. PSP of an **unsuccessful** Android flow `XKL4TKBCXQBNHJ65`
4. I've noticed for Android, `browserInfo` is not being passed in the `onSubmit` callback

**Comment by descorp** [comment]
~~Could be related #334~~

**Comment by descorp** [comment]
Hey @lachlanmcbride 

Were you able to figure this out?

**Comment by lachlanmcbride** [comment]
Hey @descorp 

It seems to be an issue with the React Native Debugger. Disconnecting the app from the debugger will get this to work again.
