### ISSUE TITLE
No opportunity to proceed payment with saved card via Adyen-Components

### ISSUE THREAD

**Issue by daklin2** [Adyen/adyen-react-native#329]
**Describe the bug**
We're making integration with Adyen via Adyen-Components.
During work on the "pay with saved card" functionality, we've faced a problem that nothing is working to pass saved card details into the component so it would be pre-filled.

We already went through the documentation and no information about how to deal with that functionality.

Could you please help to understand how to proceed with saved card payments from the mobile application point of view? 

**Expected behavior**
Saved card data is passed into the component and user should not enter details one more time.

**Smartphone:**
 - Device: any simulator/emulator or real device
 - OS: iOS/Android
 - Version: any version

**Additional context**
* Cards are saved during the payment before, we also receive all the needed data about saved cards from BackEnd.
* Using 1.2.0 ReactNative Adyen

**Comment by descorp** [comment]
Hey @daklin2 

This flow is indeed still missing.
We collecting feedback in [another ticket](https://github.com/Adyen/adyen-react-native/issues/172).

I am going to close this one as duplicate
