### ISSUE TITLE
Cannot get property 'adyenReactNativeRedirectScheme' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by AhmSaeed** [Adyen/adyen-react-native#330]
**Describe the bug**
I'm trying to get Adyen to work with my project but it fails with Android with the following error:

> Cannot get property 'adyenReactNativeRedirectScheme' on extra properties extension as it does not exist

Even If am totally sure I added the required keys in env file.

I tried Adyen sdk with a [sample project](https://github.com/AhmSaeed/Awesome) with React Native v.0.72.4 and it builds successfully without issues but when I tried to create another [sample project](https://github.com/AhmSaeed/happynrwl) with same React Native version but with NX it fails with the above issue.

**To Reproduce**
1. Go to [sample repo](https://github.com/AhmSaeed/Awesome)
2. Clone it.
3. Run `npm i`.
4. Run `npx react-native start run-android`.

**Screenshoots**
<img width="757" alt="Screenshot 2023-12-19 at 7 41 23 PM" src="https://github.com/Adyen/adyen-react-native/assets/24687421/eb872478-da4c-4eec-9d36-6cef302212d6">

**Expected behavior**
Get adyen work smoothly as it should set `adyenReactNativeRedirectScheme` to rootProject through build time.

**Desktop (please complete the following information):**
 - OS: [Android]
 - Version [1.1]

**Smartphone (please complete the following information):**
 - Device: [Pixel7 pro emulator]
 - OS: [Android 13]
 - Version [Android Studio Giraffe | 2022.3.1 Patch 3]

**Comment by descorp** [comment]
Hey @AhmSaeed 

Is this still a problem?
I was not able to consistently reproduce this on local VM.

I believe I got this error first time I run this repo on a clean machine, but every consecutive run it works as expected.
My assumption - this is simply broken cache. 
Have you tried deleting all *.lock files try again `npm install` and/or `yarn install`?

**Comment by reactnative94** [comment]
I am also facing the same issue after upgrading library to latest version. @AhmSaeed are you able to resolve it or any work around.

@descorp I deleted yarn.lock and also removed cache but then also facing the same issue.

**Comment by descorp** [comment]
@reactnative94 Could you open the project on Android Studio and run it?
Usually this problem simply indicating that lib wasn't properly build due to some other issue.

**Comment by reactnative94** [comment]
@descorp Yes I had opened the project in Android Studio but sync failed. 

![Screenshot 2024-03-08 at 5 09 15 PM](https://github.com/Adyen/adyen-react-native/assets/96985274/252e20bf-c7ac-4543-a75b-2ac996a609d1)


Below are the steps I did to configure for android

**app/build.gradle :**

manifestPlaceholders = [redirectScheme: rootProject.ext.adyenReactNativeRedirectScheme]

**MainActivity.kt:**

import android.content.Intent
import android.os.Bundle
import com.adyenreactnativesdk.AdyenCheckout.handleIntent
import com.adyenreactnativesdk.AdyenCheckout.setLauncherActivity

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(null)
    setLauncherActivity(this)
  }

  override fun onNewIntent(intent: Intent?) {
    super.onNewIntent(intent)
    handleIntent(intent!!)
  }

**AndroidManifest.xml :** 

<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:host="${applicationId}" android:scheme="${redirectScheme}" />
</intent-filter>

**Comment by jreij** [comment]
Hi @reactnative94 , can you share the hierarchy of your `app/build.gradle` file?
Make sure you declared `manifestPlaceholders` in the right place.
The file should look like this:

```groovy
android {
    ..

    defaultConfig {
        ..
        manifestPlaceholders = [redirectScheme: rootProject.ext.adyenReactNativeRedirectScheme]
    }
}

**Comment by tayyabrajpoot12** [comment]
getting same issue

**Comment by reactnative94** [comment]
@tayyabrajpoot12  in  your gradle.properties  add the below line 

**adyenReactNativeRedirectScheme=yourappname** and then clean project and rebuild.

I was able to solve the issue with the above method on my side

**Comment by tayyabrajpoot12** [comment]
can you tell me how did you close the payment sheet after making payment request ?

**Comment by reactnative94** [comment]
Keep this for android and try

onProvide={onProvide}
onFail={onFail}

**Comment by tayyabrajpoot12** [comment]
but there are only that function that can pass as attribute

      onSubmit={didSubmit}
      onAdditionalDetails={didProvide}
      onError={didError}
      onComplete={didComplete}
      
      here when I enter card details didSubmit function runs and call an api like
      
      
        const didSubmit = async e => {
    try {
      const dataToPost = {
        amount: grandTotal,
        paymentMethod: e?.paymentMethod,
        returnUrl: e?.returnUrl,
      };

      const url = 'payment/submit/';
      const response = await post(url, dataToPost);
      console.log(response.data);
    } catch (error) {
      console.log(error.response.data, 'err in did submit');
    }
  };


and the function gives me reponse as well but the payment sheet does not close

**Comment by reactnative94** [comment]
@tayyabrajpoot12 Replace onAdditionalDetails with onProvide and onError with onFail and then try. I have kept the same name it is working. Try once.

**Comment by reactnative94** [comment]
> @tayyabrajpoot12 in your gradle.properties add the below line
> 
> **adyenReactNativeRedirectScheme=yourappname** and then clean project and rebuild.
> 
> I was able to solve the issue with the above method on my side

 were you able to resolve issue with the above method

**Comment by descorp** [comment]
@tayyabrajpoot12 

One must use `useCallback` - it will cache a function definition between re-renders.

See [example here](https://github.com/Adyen/adyen-react-native?tab=readme-ov-file#advanced-flow).

@reactnative94 

> onProvide={onProvide} onFail={onFail}

For v1.2.0 and v2 - use [onAdditionalDetails](https://github.com/Adyen/adyen-react-native/blob/1.2.0/src/AdyenCheckoutContext.tsx#L76) and [onError](https://github.com/Adyen/adyen-react-native/blob/1.2.0/src/AdyenCheckoutContext.tsx#L70)

We deprecated `onProvide` and `onFail` [long time ago](https://github.com/Adyen/adyen-react-native/blob/1.0.0-beta.5/src/AdyenCheckoutContext.js)

**Comment by descorp** [comment]
I am losing this ticket. Please feel free to provide feedback.
