### ISSUE TITLE
Unable to open Drop-in of Adyen

### ISSUE THREAD

**Issue by rahulystl** [Adyen/adyen-react-native#339]
Adyen libraries dependency throwing error in react native

1. Go to Login
2. Click on adyen button
3. Scroll down to Adyen screen,click on Drop in Button

**Expected behavior**
Adyen Drop-in page should be opened.

**Screenshots**
Error:
	Attribute data@scheme at AndroidManifest.xml:45:51-85 requires a placeholder substitution but no value for <redirectScheme> is provided.
	
ERROR  TypeError: Cannot read property 'config' of undefined.

ERROR  TypeError: start is not a function (it is undefined), js engine: hermes

**Desktop (please complete the following information):**
 - OS: ios

**Additional context**

**Comment by descorp** [comment]
Hey @rahulystl 

> Go to Login ... Click on adyen button

I am not sure what is this description.

> ERROR TypeError: start is not a function (it is undefined), js engine: hermes

Do you follow [installation steps](https://github.com/Adyen/adyen-react-native/tree/1.2.0?tab=readme-ov-file#installation)?
