### ISSUE TITLE
Next button in payment form does not allow user to proceed.

### ISSUE THREAD

**Issue by Seamus1989** [Adyen/adyen-react-native#340]
**Describe the bug**
Using drop-in components..

```
      onPress={() => {
        try {
          start('scheme')
        } catch (error) {
          console.log("Error", {
            message: "There was an Error.",
          })
        }
      }}
```

When filling the payment form, I have noticed next button (when entering address fields) does not allow the user to progress - after entering the country from the select field input.

Note the first tap of `Next` from entering card holders name does allow you to progress to the country field. Any further taps of `Next` further down the form the behaviour does not work as intended.

**To Reproduce**
1. Fire a payment method by card or `scheme` to show the drop in components with

```
card: {
    holderNameRequired: true,
    addressVisibility: "full",
  },
  ```
  
  set inside the config.
2. Enter card details
3. Enter card holder name
4. Hit `Next` on the native keyboard and proceed to country select
5. Touch the first address field text input to enter some text
6. Hit `Next` and you will see you do not proceed
**Expected behaviour**
You expect the form to focus on the next text input field.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 pro
 - OS: 15
 - Version `"@adyen/react-native": "1.2.0",`

**Additional context**
This does seem to prevail after further testing on differing device/ios versions (it is not just ios 15 as previously mentioned - edit).  I have seen it work on my device, and then intermittently not work - iphone 13 pro, ios 16.3.1.

**Comment by descorp** [comment]
Hey @Seamus1989 

Thanks for feedback.
Indeed there was an issue on v4 with focus - it is captured by country picker.
On iOS v5 address component was revisited.

Stay tuned for v2.0.0 release

---

![Screenshot 2024-01-18 at 17 46 16](https://github.com/Adyen/adyen-react-native/assets/2648655/c52d2a84-5705-4394-9ff1-158d27c22588)
