### ISSUE TITLE
In Android for Paypal Payment onAdditionalDetails callback not trigger 

### ISSUE THREAD

**Issue by swatibohra9** [Adyen/adyen-react-native#345]
**Describe the bug**
After paypal selection from Adyen DropIn in Android it goes to the paypal payment site after clicking on complete purchase it navigate back to the application but we are not able to get any callback event of payment completed or failure. For ios after navigating back to the application it trigger the `onAdditionalDetails ` callback method and we are able to place order.
**To Reproduce**
1. Go to AdyenDropIn
2. Click on 'paypal' option from the dropIn
3. Complete the Payment It navigate back to the application
4. No callBack trigger

**Expected behavior**
For Android also it should trigger the `onAdditionalDetails `

**Comment by descorp** [comment]
Hey @swatibohra9 

What `returnURL` you are using on Android?

**Comment by swatibohra9** [comment]
We are not setting any returnUrl it is coming from onSubmit  returnURL for android - > adyencheckout://(application id) @descorp

**Comment by descorp** [comment]
@swatibohra9 

This is good - this is how it should be.
Do you have any logs from Android Studio?

**Comment by swatibohra9** [comment]
Hi @descorp  sharing you the logcat file for android  paypal payment can you
 please look into this 
[Uploading logcat.txt…]()
<img width="1458" alt="Screenshot 2024-01-29 at 6 36 15 PM" src="https://github.com/Adyen/adyen-react-native/assets/67097051/e3f9c782-db4a-41f0-a4c7-bf67a79a8977">
<img width="1462" alt="Screenshot 2024-01-29 at 6 36 43 PM" src="https://github.com/Adyen/adyen-react-native/assets/67097051/8f569482-2fcc-42bf-b37b-ebe383a45d9c">

**Comment by descorp** [comment]
Hey @swatibohra9 

> We are not setting any returnUrl it is coming from onSubmit returnURL for android - > adyencheckout://(application id)

The logs above are not very informative, but it looks to me that the `returnUrl` used here is **kcp://adyen/payment**.
I would suggest to check this with your backend team for an actual value of `returnURL` used in this transaction. 
If no luck - please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) and provide them with PSP reference of this transaction (could be found in CA portal or backend trace logs).

**Comment by descorp** [comment]
Hey @swatibohra9 

Any luck?

**Comment by swatibohra9** [comment]
yes it is an issue with returnUrl now it has been fixed for adyen
