### ISSUE TITLE
Android build issue: Kotlin version

### ISSUE THREAD

**Issue by gunnartorfis** [Adyen/adyen-react-native#357]
**Describe the bug**
When building our Expo SDK 50 (RN 0.73) app on Android, we get the following error:
`xx/node_modules/@adyen/react-native/android/src/main/java/com/adyenreactnativesdk/component/base/ComponentEvent.kt:12:5 The feature "data objects" is only available since language version 1.9`

**To Reproduce**
Install and build a React Native app (0.73)

**Expected behavior**
It should build without issues. 

**Desktop (please complete the following information):**
 - OS: Android
 - Version 2.0.0 beta 1

**Smartphone (please complete the following information):**
 - Device: Pixel Emulator
 - OS: Android 
 - Version 32.1.14.0

**Additional context**

**Comment by descorp** [comment]
Hey @gunnartorfis 

Thank you for checking BETA release 💚

This is known issue, but we was not aware it will effect consumers of the library.

**Comment by gunnartorfis** [comment]
Np @descorp - we actually need the standalone action handler from 2.0 😄 

Feel free to check out the PR I attached with the issue. I'm not sure if it has any implications, removing the data attribute.
