### ISSUE TITLE
[NEED ASSIST] How to do IOS integration with AppDelegate.swift file 

### ISSUE THREAD

**Issue by ahmetgsu** [Adyen/adyen-react-native#36]
Adyen IOS integration was working with `AppDelegate.m` file. However, we converted AppDelegate.m file to `AppDelegate.swift` file.
Could you please guide me, if possible, on how to convert IOS integration codes of AppDelegate.m into AppDelegate.swift file?

I tried it with the below code in AppDelegate.swift file, but it does not handle the redirection at the end of the `3DS1 authentication`.

```
import adyen_react_native

func application(_ app: UIApplication, open url: NSURL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
  RedirectComponentProxy.proccessURL(url)
}
```

**Comment by descorp** [comment]
Hey @ahmetgsu 

Seems like you have a typo in `open url: NSURL` -> `open url: URL`.
Could you check if `RedirectComponentProxy.proccessURL(url)` got hit if you debug ?

**Comment by ahmetgsu** [comment]
@descorp Thank you for your prompt response. 

Since `RedirectComponentProxy.processURL` method accept parameter type `NSURL`, I replaced `URL` type with the `NSURL`.

**Comment by descorp** [comment]
Hey @ahmetgsu 

I see the problem. So we are going to add this #37  :)

The correct "override" is with `URL`. 
For now you can do:

```swift
import adyen_react_native

func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    RedirectComponentProxy.proccessURL(url as NSURL)
}
```

**Comment by ahmetgsu** [comment]
Hey @descorp 

I tried your above suggestion. However, it is stuck on this screen. I also try to check it on XCode build.

![2022-09-13_14-00-28](https://user-images.githubusercontent.com/48296634/189895972-234ca010-5a11-4ce8-a5b0-ab051f1d3fae.png)

**Comment by descorp** [comment]
Few questions:

Redirects were working previously?
What version of Xcode are you using?
Does `RedirectComponentProxy.proccessURL(url)` got hit if you debug in Xcode?

**Comment by ahmetgsu** [comment]
My issue looks to be solved. We have both AppDelegate and SceneDelegate files together. I was working on the AppDelegate file but that should be SceneDelegate. Now, it is working. Thank you for your assistance @descorp

**Comment by descorp** [comment]
Any time :)

I am closing this topic
