### ISSUE TITLE
For IOS On saved cards when we try to do payment in the CVV popup pay button is showing disabled after entering details

### ISSUE THREAD

**Issue by swatibohra9** [Adyen/adyen-react-native#367]
**Describe the bug**
On saved cards when we try to do payment in the CVV popup pay button is showing disabled after entering details

**To Reproduce**
1. Go to 'saved card' from the adyenDropIn
2. Click on any saved cards from the list
3. cvv popup open after entering cvv pay button is not enabling

**Expected behavior**
Pay button should be enable

**Screenshots**
<img width="477" alt="Screenshot 2024-02-12 at 10 25 28 AM" src="https://github.com/Adyen/adyen-react-native/assets/67097051/8b2dc1b0-1fad-4a84-9a7f-056d37e6eb54">

**Comment by descorp** [comment]
Hey @swatibohra9 

This is [know iOS 16 bug](https://github.com/Adyen/adyen-ios/issues/1188).
Nothing could be done from Adyen side in this case..

---

Is this v1.2.0 or v2-Beta ?

**Comment by swatibohra9** [comment]
I am using v1.1.0

**Comment by swatibohra9** [comment]
Closing this ticket in real device its working fine simulator we cannot check
