### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException, Directory server root certificates are invalid or nil

### ISSUE THREAD

**Issue by StefanWallin** [Adyen/adyen-react-native#378]
**Describe the bug**
This is a bug we've encountered in our Firebase Crashlytics Reporting. 

**This causes a fatal exception for us.** We have two occurrences so far. Not a major headache yet.

iOS only, we deploy both to Android and iOS

From our telemetry it looks like both of these devices had network issues at the time because they had not handshaken with our backend on app start which they usually do.
```
Fatal Exception: NSInternalInconsistencyException Directory server root certificates are invalid or nil,
providing the Directory server root certificates and public key is required. check [documentation](
https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/native)
```

The URL referenced above is also 404.

**To Reproduce**
I don't know honestly.

**Expected behavior**
The app to not crash with the above exception.

**Screenshots**
Device 1
- App run time at point of crash: `1 minute 38 seconds`
- Package version: `"@adyen/react-native": "^1.1.0",`
<img width="1117" alt="Screenshot 2024-02-22 at 16 45 23" src="https://github.com/Adyen/adyen-react-native/assets/457653/f42a9398-5eaa-4022-b40a-8b573c1b86f2">

Device 2
- App run time at point of crash: `2 minutes 20 seconds`
- Package version: `"@adyen/react-native": "^1.1.0",`
<img width="1116" alt="Screenshot 2024-02-22 at 16 45 17" src="https://github.com/Adyen/adyen-react-native/assets/457653/307136c0-ab8a-42bc-a1c0-a50a636fef0e">

**Additional context**
Not sure what context is relevant for you, ask questions and I will try to answer.

**Comment by descorp** [comment]
Hey @StefanWallin 

This looks like https://github.com/Adyen/adyen-3ds2-ios/issues/34 

I'll check with 3DS2 team..

**Comment by descorp** [comment]
We just released [2.0.0-rc.1](https://github.com/Adyen/adyen-react-native/releases/tag/2.0.0-rc.1) and [1.2.1](https://github.com/Adyen/adyen-react-native/releases/tag/1.2.1) that uses latest Adyen3DS.

@StefanWallin could you verify the fix ?

**Comment by StefanWallin** [comment]
Well, we've only seen this a couple of times. Since I filed this issue, only once and that was on 31st of march. We are also currently stuck with apple, but I'll try to squeeze this into an upcoming release and then we'll just have wait and see...

**Comment by descorp** [comment]
I'll close this ticket for now. Feel free to leave feedback and continue the discussion here.
