### ISSUE TITLE
Use new react native architecture

### ISSUE THREAD

**Issue by ukasiu** [Adyen/adyen-react-native#38]
Hi,

React Native maintainers are introducing new architecture to [solve some of the issues that afflicted the Old Architecture in terms of performance and flexibility](https://reactnative.dev/docs/next/the-new-architecture/why). New architecture facilitates backwards compatibility with the old architecture (https://reactnative.dev/docs/next/the-new-architecture/backward-compatibility).

As this is a new library it would make sense to make it future proof by supporting the new architecture from the very beginning.

**Comment by descorp** [comment]
Hey @dcosmin2003 

Thanks for feedback!

Swift is not compatible with Objective-C++, indeed 
We will investigate potential workarounds!

**Comment by hzblj** [comment]
Hello,
Is there any progress on this? 

I tried this library on `expo 46.0.16 `and` React Native 0.69.6` **bare workflow** without importing `@import adyne_react_native` and everything is seen to work. 

Is there any catch with this import? Will the library work without this import on the production build or do I need to downgrade to the old version with only one (.m)?

Thank you

**Comment by descorp** [comment]
Hey @JBlazej 

> Is there any catch with this import? 

After (almost any) payment flow is completed, this Import allows you to use `RedirectComponentProxy` to process the redirect URL and receive `onProvide` callback  **on iOS** :

```obj-c
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RedirectComponentProxy proccessURL:url];
}
```

> Will the library work without this import on the production build or do I need to downgrade to the old version with only one (.m)?

It is not essential for product build since when the payment is conducted your backend will receive a webhook from Adyen backend about payment status (could take up to 10-30 minutes). 
Also, return URL could be processed by other means (on your web or backend), you only need to think of means to notify your mobile app.

However, to conduct payment status in a real time and provide actual feedback to the shopper we recommend to arrange custom URL scheme in your app, receive the redirect then pass it to component by using `RedirectComponentProxy`.

Currently, there is a potential workaround:

manually parse the URL (see Swift sample [here](https://github.com/Adyen/adyen-ios/blob/develop/AdyenActions/Components/Redirect/RedirectDetails.swift)) so it is compatible with [/payments/details](https://docs.adyen.com/api-explorer/Checkout/68/post/payments/details) endpoint on Adyen API.

We are planing to work on Objective-C++ compatible helper for beta-8

**Comment by descorp** [comment]
**UPD**

The easiest workaround is to create local Obj-c class and use it in your `AppDelegate.mm`

### MYRedirectComponentProxy.h 

```objc
@interface MYRedirectComponentProxy : NSObject

+ (BOOL)proccessURL:(nonnull NSURL *)url;

@end
```

### MYRedirectComponentProxy.m

```objc
#import "MYRedirectComponentProxy.h"
@import adyen_react_native;

@implementation MYRedirectComponentProxy

+ (BOOL)proccessURL:(nonnull NSURL *)url {
  return [RedirectComponent proccessURL:url];
}

@end
```

### AppDelegate.mm
```c++
#import "MYRedirectComponentProxy.h"

...

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [MYRedirectComponentProxy proccessURL:url];
}

```

**Comment by descorp** [comment]
Working on a fix in #121

**Comment by robwalkerco** [comment]
Hey @descorp, sorry to jump into this issue asking about SDK releases, but we have just run into this issue!

Do you have an idea of when https://github.com/Adyen/adyen-react-native/pull/121 would be released in a new SDK version, once it's merged? Just trying to get an idea of whether we should wait, or implement your suggested workaround!

**Comment by descorp** [comment]
Hey @robwalkerco 

#121 is merged. Release [beta-8](https://github.com/Adyen/adyen-react-native/milestone/3) can be expected in January.

**Comment by BenSagir** [comment]
> **UPD**
> 
> The easiest workaround is to create local Obj-c class and use it in your `AppDelegate.mm`
> 
> ### MYRedirectComponentProxy.h
> ```objc
> @interface MYRedirectComponentProxy : NSObject
> 
> + (BOOL)proccessURL:(nonnull NSURL *)url;
> 
> @end
> ```
> 
> ### MYRedirectComponentProxy.m
> ```objc
> #import "MYRedirectComponentProxy.h"
> @import adyen_react_native;
> 
> @implementation MYRedirectComponentProxy
> 
> + (BOOL)proccessURL:(nonnull NSURL *)url {
>   return [RedirectComponent proccessURL:url];
> }
> 
> @end
> ```
> 
> ### AppDelegate.mm
> ```c++
> #import "MYRedirectComponentProxy.h"
> 
> ...
> 
> - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
>   return [MYRedirectComponentProxy proccessURL:url];
> }
> ```

Hi @descorp . this solution does not solve the problem. where the files should be placed? because i get modules error when im trying to render the Adyen Drop in component.[](url)
![Simulator Screen Shot - iPhone 11 - 2023-01-22 at 11 40 05](https://user-images.githubusercontent.com/74058388/213909298-bcff382c-189e-486f-be52-30ad6bf28d57.png)

**Comment by robwalkerco** [comment]
> Hi @descorp . this solution does not solve the problem. where the files should be placed? because i get modules error when im trying to render the Adyen Drop in component. 

While waiting for the [beta-8](https://github.com/Adyen/adyen-react-native/milestone/3) release we are using [patch-package](https://github.com/ds300/patch-package) to [apply the changes](https://github.com/Adyen/adyen-react-native/pull/121/commits/2f39d098ac30bbf243d51b31ae660f9a78cb1ebc) that will be released in the new beta. Than avoids the need to edit any of our own project files etc.

<details><summary>View the patch contents</summary>

`patches/@adyen+react-native+1.0.0-beta.7.patch`

```
@@ -0,0 +1,50 @@
diff --git a/node_modules/@adyen/react-native/ios/ADYRedirectComponent.h b/node_modules/@adyen/react-native/ios/ADYRedirectComponent.h
new file mode 100644
index 0000000..5f6fbea
--- /dev/null
+++ b/node_modules/@adyen/react-native/ios/ADYRedirectComponent.h
@@ -0,0 +1,22 @@
+//
+// Copyright (c) 2023 Adyen N.V.
+//
+// This file is open source and available under the MIT license. See the LICENSE file for more info.
+//
+
+#import <Foundation/Foundation.h>
+
+NS_ASSUME_NONNULL_BEGIN
+
+/// Handles any redirect Url whether its an App custom scheme url, or an app universal link.
+@interface ADYRedirectComponent : NSObject
+
+/// This function should be invoked from the application's delegate when the application is opened through a URL.
+///
+/// - Parameter url: The URL through which the application was opened.
+/// - Returns: A boolean value indicating whether the URL was handled by the redirect component.
++ (BOOL)applicationDidOpenURL:(nonnull NSURL *)url;
+
+@end
+
+NS_ASSUME_NONNULL_END
diff --git a/node_modules/@adyen/react-native/ios/ADYRedirectComponent.m b/node_modules/@adyen/react-native/ios/ADYRedirectComponent.m
new file mode 100644
index 0000000..af5b100
--- /dev/null
+++ b/node_modules/@adyen/react-native/ios/ADYRedirectComponent.m
@@ -0,0 +1,16 @@
+//
+// Copyright (c) 2023 Adyen N.V.
+//
+// This file is open source and available under the MIT license. See the LICENSE file for more info.
+//
+
+#import "ADYRedirectComponent.h"
+#import <adyen_react_native-Swift.h>
+
+@implementation ADYRedirectComponent
+
++ (BOOL)applicationDidOpenURL:(nonnull NSURL *)url {
+    return [RedirectComponentProxy proccessURL: url];
+}
+
+@end
```

</details>

**Comment by descorp** [comment]
@BenSagir 

>  where the files should be placed?

Files expected to be added to your iOS project in Xcode (New File -> Cocoa Touch Class).

> i get modules error 

Can you build your Xcode project?

**Comment by jamestimbrell** [comment]
> Hey @robwalkerco
> 
> #121 is merged. Release [beta-8](https://github.com/Adyen/adyen-react-native/milestone/3) can be expected in January.

@descorp When trying to incorporate this fix (from #121) in our project; We are getting an error in ADYRedirectComponent.m throwing 'ayden_react_native_Swift.h> file not found.

Other than that we are still getting the same issue in AppDelegate.mm erroring with 'Use of undeclared identifier 'ADYRedirectComponent'.

We are using AppDelegate.mm, rather than AppDelegate.m - could this be an issue?

**Comment by mantasdb** [comment]
hey, @descorp any ETA on [beta-8](https://github.com/Adyen/adyen-react-native/milestone/3) release?

**Comment by descorp** [comment]
Hey @mantasdb 

Sorry for delay.
We plan release this week.

**Comment by descorp** [comment]
**Beta-8** is released with the fix.
Please confirm it resolves the problem 💚

**Comment by robwalkerco** [comment]
Thanks @descorp
FYI: I've just updated, and I'm getting an Android build error - https://github.com/Adyen/adyen-react-native/issues/140

**Comment by rosen777** [comment]
I am getting the same error that @jamestimbrell is getting: 'Use of undeclared identifier 'ADYRedirectComponent' in XCode. This is with the latest version: 1.0.0-beta.9. In addition when I try to pod install, I am getting an error that 'ffi_c.bundle mach-o file but is an incompatible architecture have x86_64 need arm64'. I do not have errors pod installing other libraries and everything works correctly when I remove the @adyen/react-native package.
