### ISSUE TITLE
DropIn: Starting GooglePay Component.

### ISSUE THREAD

**Issue by Alieltahan** [Adyen/adyen-react-native#386]
**Describe the bug**
I'm using Adyen and working as starting it with 'dropin'. 
I'm sending to Adyen the desired PaymentMethod and its configuration only, so I wanted to open GooglePay Directly and avoiding seeing Googlepay as PaymentMethod and choose it in order to open GooglePay overlay.

when I `start('googlepay')`, and click on the button it opens normally, and when clicking on Pay the overlay hides, but the screen kept dimmed, and no log is happening in didSubmit nor didFail.

**To Reproduce**
1. Click on the button to start Adyen `start('googlepay')`
2. Click on Pay.
3. Error: Adyen over lay hidden, and screen kept dimmed.

**Expected behavior**
Adyen closes successfully and calls didSubmit.

**Smartphone (please complete the following information):**
 - Device: [Xaiomi POCO 4]
- OS: [Android]
 - Version [13]

**Additional context**
App is running on:
- Node v: 16.20.2
- Ruby: 2.7.8

**Comment by Alieltahan** [comment]
Node v upgraded to 21.7.1, and still issue persist.

**Comment by descorp** [comment]
Hey @Alieltahan 

What version of SDK you are using? v.1.2.0 or v2 Beta ?

> I'm using Adyen and working as starting it with 'dropin'.

> when I start('googlepay'), and click on the button it opens normally,

So is it a DropIn or just GooglePay?

> the overlay hides, but the screen kept dimmed,

Could you provide video or GIF ?

**Comment by Alieltahan** [comment]
Hi @descorp , 
> What version of SDK you are using? v.1.2.0 or v2 Beta ?

I'm using Adyen SDK v 1.2

> So is it a DropIn or just GooglePay?

I'm using DropIn


When starting the DropIn via ```start('googlepay')```, it opens GooglePay and dimmed overlay on background.
once I click pay, the Google Pay modal gets hidden, and the dimmed overlay keeps there and app freezes ( No logs happen in didSubmit/DidFail/DidComplete ).

![1Google Pay](https://github.com/Adyen/adyen-react-native/assets/46691446/24244f17-3a54-40d9-b673-6ab6c0b3e1cd)


 What I'm trying to avoid is ( Starting Google pay in 2 steps ) :
1- User clicks the CTA Btn starting the dropin `start('dropin)`. 
2- The user has to click on Google Pay ```( PaymentMethod )``` to open the GooglePay overlay ( this works fine and user can complete the entire journey of Google Pay).
I had seen the example app can start Google Pay in a single step and works fine. 

![Screenshot 2024-03-19 at 00 11 09](https://github.com/Adyen/adyen-react-native/assets/46691446/9bfe83e0-4fe3-4ed5-b6be-0b94725f5520)

Thank you for your support.

**Comment by Alieltahan** [comment]
Hi @descorp 

Thank you for your reply, I figured it out, it was a missed configuration in Android files.

Closing this thread as it's not an issue :)

**Comment by descorp** [comment]
Thanks @Alieltahan 

Do you mean `onActivityResult` ?
