### ISSUE TITLE
Apple Privacy Manifest File

### ISSUE THREAD

**Issue by leofolive** [Adyen/adyen-react-native#389]
Apple is recommending declaring the use of the UserDefaults API in the privacy manifest file.
https://developer.apple.com/news/?id=r1henawx

Describe the solution you'd like
Create a privacy manifesto declaring all APIs and reasons.

Additional context

Used symbols in binary ./XCFrameworkIntermediates/Adyen3DS2/Adyen3DS2.framework/Adyen3DS2: NSUserDefaults
Used symbols in binary ./XXXX.app/Frameworks/Adyen3DS2.framework/Adyen3DS2: NSUserDefaults
UserDefault API: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401

I would like to request that we use latest version of the iOS SDK.
https://github.com/Adyen/adyen-ios/issues/1506

**Comment by leofolive** [comment]
@descorp Can we release a version of the Adyen React Native SDK with the latest version of the iOS SDK ([5.7.0](https://github.com/Adyen/adyen-ios/releases/tag/5.7.0) or [4.12.0](https://github.com/Adyen/adyen-ios/releases/tag/4.12.0)).

**Comment by descorp** [comment]
Hey @LFMAKER 

Sure thing! We are planing release this week.

**Comment by StefanWallin** [comment]
Are you planning there to be a release to the 1.2.0 version-branch with this change, or is this strictly 2.0-branch?

**Comment by descorp** [comment]
Will update shortly! Thanks for reminder @StefanWallin  💚

**Comment by descorp** [comment]
V1 updated with latest Privacy Manifest
https://www.npmjs.com/package/@adyen/react-native/v/1.2.1

**Comment by descorp** [comment]
Current v2 have issue with Adyen3DS SDK Privacy Manifest. Will update and release **v2-Release candidate** with updated Privacy Manifest shortly.

**Comment by kpoelhekke** [comment]
Hi @descorp our release is currently blocked because we're already on the 2.0 branch. Do you have an ETA on when the fix will arrive?

And if I understand you correctly just patching the current beta.3 to use iOS SDK `5.7.1` won't work because of issues with Adyen3DS?

---

Edit: We're currently doing this and that seems to work... or am I missing some edge cases?

```patch
diff --git a/adyen-react-native.podspec b/adyen-react-native.podspec
index cf6ed8cdf68aa2fe5ca186900e8c87a5b142405c..e4e3111790cf9204bcceff5ca4009d8a50dc23d2 100644
--- a/adyen-react-native.podspec
+++ b/adyen-react-native.podspec
@@ -16,7 +16,7 @@ Pod::Spec.new do |s|
 
 
   s.dependency "React-Core"
-  s.dependency "Adyen", '5.7.0'
+  s.dependency "Adyen", '5.7.1'
   s.resource_bundles = { 'adyen-react-native' => [ 'ios/PrivacyInfo.xcprivacy' ] }
 
 end
```

**Comment by descorp** [comment]
Hey @kpoelhekke 

> We're currently doing this

This is indeed an easy workaround for the situation. Thanks for sharing 💚

We are planing to release `2.0.0-rc.1` today.
