### ISSUE TITLE
How to change in IOS drop-in  when re-using card the name of the app

### ISSUE THREAD

**Issue by descorp** [Adyen/adyen-react-native#391]
### Discussed in https://github.com/Adyen/adyen-react-native/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **YankovWeb** March 26, 2024</sup>
![Screenshot at Mar 22 11-44-43](https://github.com/Adyen/adyen-react-native/assets/109748669/6a492bbc-a260-4999-b069-7b8a2196d98e)
how use custom text ?</div>

**Comment by Alieltahan** [comment]
I tried before, but it always takes the CFBundleDisplayName - value.

Will be glad if it can be customised

**Comment by descorp** [comment]
Config for DropIn title released on [2.0.0-rc.1](https://github.com/Adyen/adyen-react-native/releases/tag/2.0.0-rc.1)

use [configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#drop-in):

```js
dropin: {
    title: "my cool title"
}
```
