### ISSUE TITLE
Klarna Pay Over Time payment method does not redirecting back to the app after payment

### ISSUE THREAD

**Issue by BenSagir** [Adyen/adyen-react-native#392]
Following your [official documentation](https://docs.adyen.com/payment-methods/klarna/api-only/) Klarna changed their protocol or something.

when paying with Klarna Pay Over Time. the transaction is set up well and the backend acknowledge it as a valid payment but the SDK is stuck on loader and not redirected back to the app. the didProvide function is not running in this case.

after i close the app and open it again it looks like a successful payment but only the redirection is breaking the flow.

are you planning on deal with this issue? is there a workaround to activate the didProvide callback when paying with Klarna?

thanks in advance, Ben Sagir.

**Comment by BenSagir** [comment]
looks like Paypal cancelation has the same issue
i got this warning in the console:

Sending `didFailCallback` with no listeners registered.

**Comment by descorp** [comment]
Hey @BenSagir 

> Sending didFailCallback with no listeners registered.

This means that native code emitting event, but no one is listening. 
Is it possible that `AdyenCheckout` object or it's parent was recreated?

Make sure you are using `useCallback`:
```
import { useCallback } from 'react';
```

---

Could you create a blank app and reproduce this behaviour?

**Comment by YankovWeb** [comment]
@descorp  Is working we fix it Thank you

**Comment by descorp** [comment]
Thanks for letting us know @YankovWeb !

What was the cause of the issue?

**Comment by YankovWeb** [comment]
We change the screen components  on loading to show animation of loading and AdyenCheckout was re-created.
Thank you.
