### ISSUE TITLE
With iOS integration, changing application:openURL breaks react native linking?

### ISSUE THREAD

**Issue by jimbofoo** [Adyen/adyen-react-native#394]
In the setup guide we need to add this line to Appdelegate.mm:

```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [ADYRedirectComponent applicationDidOpenURL:url];
}
```
This overrides the original line:

```
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
    return [RCTLinkingManager application:application openURL:url options:options]; 
}
```

Which causes deeplinking to not work anymore:

```
Linking.addEventListener('url', (url) => {
  console.log('deeplink:', url)
})
```

Is this correct? Shouldn't it be something like:

```
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [ADYRedirectComponent applicationDidOpenURL:url] || [RCTLinkingManager application:application openURL:url options:options];
}
```

**Comment by descorp** [comment]
Hey @jimbofoo 

This is correct order :)

If you are using custom Url schemes, you can also do something like
```objc
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  if ([[url scheme] isEqualToString:@"my-payment-scheme"]) {
    return [ADYRedirectComponent applicationDidOpenURL:url];
  }
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

**Comment by descorp** [comment]
This is [documented now](https://github.com/Adyen/adyen-react-native?tab=readme-ov-file#ios-integration)
I am going to close this ticket.

**Comment by gunnartorfis** [comment]
This is broken for the Expo Config plugin.
Should there be an option to add the custom URL scheme to the config plugin?

**Comment by descorp** [comment]
Hey @gunnartorfis 

> This is broken for the Expo Config plugin.

What do you mean?

> Should there be an option to add the custom URL scheme to the config plugin?

Our SDK does not modify or create URL Scheme. You can use standard [Expo linking](https://docs.expo.dev/guides/linking/#creating-urls), use Universal Link or create Custom URL by other means.

**Comment by ignaciotcrespo** [comment]
Hi @descorp,

In the [documentation](https://github.com/Adyen/adyen-react-native?tab=readme-ov-file#ios-integration), it is specified to implement `continueUserActivity` with a call to `[super application:application continueUserActivity:userActivity restorationHandler:restorationHandler]`. This causes a crash in my release builds whenever I open my app through deep links. 

I am curious about the necessity of this call to `super`. From my understanding, `UIApplicationDelegate` is a protocol and does not implement `continueUserActivity`. Could you clarify if this call to `super` is required specifically for Adyen, and if so, why? 

Thank you!

**Comment by descorp** [comment]
Hey @ignaciotcrespo 

Thanks for pointing this out 💚
Indeed, it is not necessary for [vanila ReactNative](https://github.com/facebook/react-native/blob/main/packages/react-native/template/ios/HelloWorld/AppDelegate.h#L4), and only needed [for `expo`](https://github.com/expo/expo/blob/main/apps/bare-expo/ios/BareExpo/AppDelegate.h#L7).

**Comment by descorp** [comment]
PR to update README #472
