### ISSUE TITLE
Android Example Project is not working.

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#43]
**Describe the bug**
Please try to run the example project on Android, It's breaking.

**To Reproduce**
1. Run Android Example Project

**Expected behavior**
The project should work. 

**Screenshots**
<img width="1440" alt="Screenshot 2022-10-10 at 3 00 20 PM" src="https://user-images.githubusercontent.com/18231674/194851440-a28e25f7-22c3-488f-9153-c44435f22101.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Android Studio: Android Studio Dolphin | 2021.3.1

**Smartphone (please complete the following information):**
 - Device: Android Simulator
 - OS: Android 11

**Comment by descorp** [comment]
Hey @iranaahsanali 

Have you tried `yarn` or `run yarn install` ?
This doesn't seem like a this is Adyen specific error 🤔

**Comment by iranaahsanali** [comment]
Yes, After installing node modules in example directory.

**Comment by faizantariq2** [comment]
`<AdyenCheckout
  config={configuration}
  paymentMethods={paymentMethods}
  onSubmit={didSubmit}
  onProvide={didProvide}
  onFail={didFail}
  onComplete={didComplete} >
    <MyChekoutView/>
</AdyenCheckout>`


In MyCheckoutView using  const { start } = useAdyenCheckout(); this start the require payment method. like start('paypal') etc.

**Comment by descorp** [comment]
So if you run `yarn react-native run-ios` - that is what you see?

**Comment by descorp** [comment]
Hey @iranaahsanali 

Any luck?

**Comment by descorp** [comment]
I am going to close this ticket due to lack of activity. 
Please feel free to continue discussion here

**Comment by descorp** [comment]
Potential fix for this is to first run `yarn` on SDK itself (from the root of the repo) then run `yarn ios` or `yarn android` from "Example" folder
