### ISSUE TITLE
Two challenges, one after the other, doesn't open on Android

### ISSUE THREAD

**Issue by LeandroSimoes42** [Adyen/adyen-react-native#440]
**Describe the bug**
I have a flow in my app where the user can pay with two cards, so if I need to do the 3ds for both cards, should open two challenges, one after the other, but it doesn't open, when the person buys with one card opens normally

**To Reproduce**
1. Go to page of product
2. Click to buy
3. select two credit cards
4. send information about payment
5. receive the challenges
6. 3ds modal doesn't open the first modal and second modal, not doing the challenges

**Expected behavior**
open the first modal, the user completes the challenge, open the second modal, the user completes the challenge and follow the standard flow

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android

**Smartphone (please complete the following information):**
 - Device: Nexus 5x
 - OS: Android 13.0
 - 
**Additional context**
this happens only on Android device, on iOS, open both modes, one after the other. The only error show to me is: 

```json
  {
    "nativeStackAndroid": [
      {
        "lineNumber": 25,
        "file": "AmountExtensions.kt",
        "methodName": "validate",
        "class": "com.adyen.checkout.components.core.internal.util.AmountExtensionsKt"
      },
      {
        "lineNumber": 113,
        "file": "BaseConfigurationBuilder.kt",
        "methodName": "setAmount",
        "class": "com.adyen.checkout.components.core.internal.BaseConfigurationBuilder"
      },
      {
        "lineNumber": 378,
        "file": "GooglePayConfiguration.kt",
        "methodName": "setAmount",
        "class": "com.adyen.checkout.googlepay.GooglePayConfiguration$Builder"
      },
      {
        "lineNumber": 416,
        "file": "GooglePayConfiguration.kt",
        "methodName": "googlePay",
        "class": "com.adyen.checkout.googlepay.GooglePayConfigurationKt"
      },
      {
        "lineNumber": 188,
        "file": "BaseModule.kt",
        "methodName": "invoke",
        "class": "com.adyenreactnativesdk.component.base.BaseModule$getCheckoutConfiguration$1"
      },
      {
        "lineNumber": 187,
        "file": "BaseModule.kt",
        "methodName": "invoke",
        "class": "com.adyenreactnativesdk.component.base.BaseModule$getCheckoutConfiguration$1"
      },
      {
        "lineNumber": 70,
        "file": "CheckoutConfiguration.kt",
        "methodName": "<init>",
        "class": "com.adyen.checkout.components.core.CheckoutConfiguration"
      },
      {
        "lineNumber": 181,
        "file": "BaseModule.kt",
        "methodName": "getCheckoutConfiguration",
        "class": "com.adyenreactnativesdk.component.base.BaseModule"
      },
      {
        "lineNumber": 46,
        "file": "ActionModule.kt",
        "methodName": "handle",
        "class": "com.adyenreactnativesdk.cse.ActionModule"
      },
      {
        "lineNumber": -2,
        "file": "Method.java",
        "methodName": "invoke",
        "class": "java.lang.reflect.Method"
      },
      {
        "lineNumber": 372,
        "file": "JavaMethodWrapper.java",
        "methodName": "invoke",
        "class": "com.facebook.react.bridge.JavaMethodWrapper"
      },
      {
        "lineNumber": 149,
        "file": "JavaModuleWrapper.java",
        "methodName": "invoke",
        "class": "com.facebook.react.bridge.JavaModuleWrapper"
      },
      {
        "lineNumber": -2,
        "file": "NativeRunnable.java",
        "methodName": "run",
        "class": "com.facebook.jni.NativeRunnable"
      },
      {
        "lineNumber": 942,
        "file": "Handler.java",
        "methodName": "handleCallback",
        "class": "android.os.Handler"
      },
      {
        "lineNumber": 99,
        "file": "Handler.java",
        "methodName": "dispatchMessage",
        "class": "android.os.Handler"
      },
      {
        "lineNumber": 29,
        "file": "MessageQueueThreadHandler.java",
        "methodName": "dispatchMessage",
        "class": "com.facebook.react.bridge.queue.MessageQueueThreadHandler"
      },
      {
        "lineNumber": 201,
        "file": "Looper.java",
        "methodName": "loopOnce",
        "class": "android.os.Looper"
      },
      {
        "lineNumber": 288,
        "file": "Looper.java",
        "methodName": "loop",
        "class": "android.os.Looper"
      },
      {
        "lineNumber": 234,
        "file": "MessageQueueThreadImpl.java",
        "methodName": "run",
        "class": "com.facebook.react.bridge.queue.MessageQueueThreadImpl$4"
      },
      {
        "lineNumber": 1012,
        "file": "Thread.java",
        "methodName": "run",
        "class": "java.lang.Thread"
      }
    ],
    "userInfo": null,
    "message": "Value cannot be less than 0.",
    "code": "parsingError"
  }
  ```

**Comment by descorp** [comment]
Hey @LeandroSimoes42 

> user can pay with two cards

This use-case is currently not possible, unfortunately. 
You can have two sets of `AdyenCheckout`, but under the hood [BaseModule](https://github.com/Adyen/adyen-react-native/blob/develop/ios/Components/BaseModule.swift) is a singleton, so both instances will still rely on the same internal properties.

I can suggest using your custom UI and [Client-side encryption](https://github.com/Adyen/adyen-react-native/blob/develop/example/src/Views/CseView.js) as an alternative.

In future versions, we are planning to work on embedded views for Components, so there is a chance this limitation could be addressed. No promises just yet, since we haven't completed assessing this architecture.

**Comment by descorp** [comment]
Hey @LeandroSimoes42 

What version of SDK are you using?

**Comment by descorp** [comment]
Are you using "standalone action handling" ?

```js
AdyenAction.handle(action, configuration);
```

>     "message": "Value cannot be less than 0.",

Seem like it is failing, because [`amount` is less then zero](https://github.com/Adyen/adyen-android/blob/develop/components-core/src/main/java/com/adyen/checkout/components/core/internal/util/AmountExtensions.kt#L24).

How is your `configuration` looks like?

**Comment by descorp** [comment]
@LeandroSimoes42 

Any luck?

**Comment by descorp** [comment]
I'm going to close this ticket. Feel free to reopen or continue the discussion here.
