### ISSUE TITLE
Adyen.modulemap not found

### ISSUE THREAD

**Issue by bpolonia** [Adyen/adyen-react-native#443]
**Describe the bug**
We are trying to use this package in a React Native app on version 0.63.3.

We follow the installation instructions in the README:

`yarn add @adyen/react-native`, `pod install`, `#import <adyen-react-native/ADYRedirectComponent.h>` into `AppDelegate.m`. We noticed that the Pod install doesn't pick up the pod. To confirm we check the import in AppDelegate but the import isn't found. When we CMD+Click into the import statement it does nothing.

We then tried the same steps but we added the pod into our Podfile:

`pod 'adyen-react-native', :path => '../node_modules/@adyen/react-native'`

and ran pod install again. This time the Adyen pod dependencies were installed and we are able to access the imported module in AppDelegate.m

However, when we try to build the app, it immediately fails with this failure message:

```
/Users/<...>/Library/Developer/Xcode/DerivedData/<...>/Build/Intermediates.noindex/<...>.build/Debug-iphonesimulator/<...>.build/DerivedSources/<...>_vers.c module map file '/Users/<...>/Library/Developer/Xcode/DerivedData/<...>Build/Products/Debug-iphonesimulator/Adyen/Adyen.modulemap' not found
```

We have tried this on three separate machines. One intel based Mac, and two M1 Macs.

**Comment by descorp** [comment]
Hey @bpolonia 

We haven't tried integrating with React-Native below 0.71.
It appears that versions below 0.70 are [deprecated](https://www.npmjs.com/package/react-native/v/0.63.3).

Unfortunately, I can only suggest updating to at least version 0.70.

**Comment by FaresHamel** [comment]
did you find any solution for t react native 0.74 ios side
