### ISSUE TITLE
Android: PayPal not listed in stored payment methods of the drop

### ISSUE THREAD

**Issue by RyanLinXiang** [Adyen/adyen-react-native#450]
**Describe the bug**
Android is not listed in the drop in the list of stored payment methods. In iOS it works fine, but not in Android. Any explanations & workarounds? Using 2.0.0-rc1

**Comment by descorp** [comment]
Hey @RyanLinXiang 

This is known behaviour - stored PayPal is only available on iOS, which is rather defect.
AFAIK, this feature is available on TEST, and should not be present on LIVE.

We are working with PayPal to fully enable stored PayPal via PayPal SDK.

If you are interested in this feature to be available  for both iOS and Android - please reach out to [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) and request it - this will help us to adjust priority :)

If you are not interested in seeing stored PayPal on iOS - please filter payment methods manually (this is the only way for now).

**Comment by RyanLinXiang** [comment]
Thank you!
