### ISSUE TITLE
`onFail` callback does not get called on Android

### ISSUE THREAD

**Issue by kadikraman** [Adyen/adyen-react-native#46]
**Describe the bug**
If the payment is cancelled by closing the webview, the `onFail` does not get called on Android.

**To Reproduce**
1. Open the example app
2. Refetch payment methods
3. Start payment with a payment method that opens in a webview (e.g. PayPal or Klarna)
4. Close the webview
5. The `onFail` callback is not called on Android

**Expected behavior**
The `onFail` callback should be called so we could update the UI.

**Screenshots**
iOS - this is working as expected

https://user-images.githubusercontent.com/6534400/195580206-8ddd8040-d1e9-4f45-a86c-b2918f2c0d92.mp4

Android - this is not working

https://user-images.githubusercontent.com/6534400/195580243-2eb5b41f-9423-4699-92ac-21e0fba5bbcb.mp4

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: Chrome
 - Version: 91.0.4472.114

**Smartphone (please complete the following information):**
 - Device:  Pixel 5
 - OS: API 32
 - Browser: Chrome
 - Version: 91.0.4472.114

**Comment by faizantariq1** [comment]
i think for android your return url is not correct.

returnUrl: 'myapp://', // Custom URL scheme of your iOS app. This value is overridden for Android by `AdyenCheckout`. Can be send from your backend

**Comment by kadikraman** [comment]
@faizantariq1 sorry, I don't quite understand: shouldn't the redirect work in the example app in this repo? I haven't changed any native code.

**Comment by descorp** [comment]
Hey @kadikraman 

Thank you for a feedback! 
Indeed, going back on in-browser is buggy.

**Comment by descorp** [comment]
@kadikraman 

I don't think there are any way to fix this (unless in current version of Android SDK).
For Example same issue could be observed on Drop-In or 3DS1 wed redirect 🤔

This is indeed very undesirables behaviour but Is this causing issues to you?

**Comment by kadikraman** [comment]
Hi @descorp yes, this issue would be a release blocker for us, because once the user initialises the payment flow we do a bunch of things in the background (we convert a cart into an order, and show a loading state) - if the user cancels we'd need to undo these things in order for the user to be able to try a different payment method. However since we can't tell that the payment has failed, we don't know to trigger the cancel flow and the only way to try a different payment method would be to force close the app and start the checkout flow again.

We've probably found a workaround for now: we use the React Native `AppState` so that if the app goes from `background/inactive` to `active` in the place order screen, we wait 500ms to see if any other callback has handled the request and if not we initiate the cancel flow.

**Comment by descorp** [comment]
We use something similar on iOS SDK to detect redirect to and external app.

The main problem here, is that unlike DropIn (or ex CardComponent that runs DropIn under the hood) Activity is outside of the control of SDK.
I'll check with Android team today - to my knowledge they are working on a fix.
Will keep you posted.

**Comment by descorp** [comment]
Hey @kadikraman 

Our Android team is working for a solution, but it will be part of v5 of Android SDK, so no immediate solution.
I hope your workaround is sustainable till we can approach this from React Native SDK side..

**Comment by ahsan-lebara** [comment]
@descorp I am also facing the same issue. Can you please share the timeline, for when this issue will be fixed? It's a big **blocker for me.**

**Comment by iranaahsanali** [comment]
@descorp I am also facing the same issue. Can you please share the timeline, for when this issue will be fixed? It's a big blocker for me.

**Comment by descorp** [comment]
Hey @iranaahsanali 

Sorry, there is no timeline as of today. The best I have is mid 2023

**Comment by kadikraman** [comment]
Just to share our workaround in case it helps others while the actual fix is being worked on:

**🚨 Discalimer**: this _seems_ to work, but we currently have another issue on Android that's preventing us from QAing this fully, so it's not yet used in production

We have a ref at the top of the provider to store the SDK state (needs to be a ref because we can't rely on re-renders)

```js
const adyenState = React.useRef<'initial' | 'open' | 'closed'>('initial');
```

In `didSubmit` we set the `adyenState` to 'open':
```js
const handleDidSubmit = async (
  data: AdyenData,
  nativeComponent: AdyenNativeComponent,
) => {
  adyenState.current = 'open';
  ...
}
```

In all the other callbacks, we set `adyenState` to 'closed':

```js
// didComplete
const handleDidComplete = (nativeComponent: AdyenNativeComponent) => {
  adyenState.current = 'closed';
  ...
}

// didFail
const handleDidFail = (
  error: Error,
  nativeComponent: AdyenNativeComponent,
) => {
  adyenState.current = 'closed';
  ...
}

// didProvide
const handleDidProvide = async (
  data: AdyenProvideData,
  nativeComponent: AdyenNativeComponent,
) => {
  adyenState.current = 'closed';
  ...
}
```

Then we use the react native app state goes from 'inactive' or 'background' -> 'active', we wait for 500ms (this is to that if the cancel event was sent, there would be time for it to get handled), and it the `adyenState` is still 'open' and nothing has handled the SDK event, we init the cancel payment flow.

```js
useAppState({
  onForeground: () => {
    wait(500).then(() => {
      if (adyenState.current === 'open' && Platform.OS === 'android') {
        // init cancel flow here 
      }
    });
  },
});
```

`useAppState` here is a until function that calls `onForeground` when `AppState` goes from  'inactive' or 'background' -> 'active'.

**Comment by descorp** [comment]
Thanks sharing @kadikraman 💚

In other words - you are assuming that if shopper get back to app after being "redirected" - it is either successful auto-redirect or deliberate decision not to pay. 

I see 2 minor faults her:
- 500ms could be not enough on a older devices
- sometimes redirect could be simply broken and shopper decides to go back manually (happens more often on iOS, but still)

What we had in mind as a solution for v5 - to make shopper decide:
Show extra "waiting" screen with a dialog "Are you still paying?" where "NO" -> means `Cancel` and "YES" - redirects again (payment link could be fetched from `action object`)

**Comment by kadikraman** [comment]
Thanks for the suggestion @descorp! I agree, the timeout is definitely the most uncertain part of the workaround. We'll try using an alert here instead of cancelling silently.

**Comment by descorp** [comment]
This was fixed by pushing extra "Pending" view on RedirectComponent execution in #55 
UI is very simple for now.
Cancel button is localized.

![Image Pasted at 2022-10-26 12-05](https://user-images.githubusercontent.com/2648655/198232495-1beab035-942a-43af-9654-0f12b5fddeb2.png)

**Comment by descorp** [comment]
Hey @kadikraman @iranaahsanali 

This bug should be fixed in [1.0.0-beta6](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.6)
Could you verify?

**Comment by iranaahsanali** [comment]
Sure, I will update you soon.

**Comment by kadikraman** [comment]
Can confirm, this is working for me now on beta 6 🎉 - Android shows an overlay with a cancel button while the SDK is open, and I can press cancel once I get redirected back to the app which correctly calls `onFail`.

Just a note - looks like there was a small breaking change where the import for the action handle changed:

```diff
- import com.adyenreactnativesdk.ActionHandler;
+ import com.adyenreactnativesdk.action.ActionHandler;
```

It might be a good idea to add that in the release notes.

**Comment by descorp** [comment]
Good point! 
We usually avoiding breaking changes, will do our best to avoid this in future 😅


Updated [Release Notes](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.6)
Thanks for feedback, @kadikraman
