### ISSUE TITLE
Recurring ApplePay

### ISSUE THREAD

**Issue by patrikmolnar** [Adyen/adyen-react-native#468]
Hey! I was wondering if you have any plans to support recurring payments with ApplePay? It's something we really want to integrate but I saw it on the website that it's not supported with React Native. Do you maybe have any workarounds in the meantime?

**Comment by descorp** [comment]
Hey @patrikmolnar 

It is in our backlog indeed.
Will keep you posted!

---

The only possible workaround - is to fork our SDK and alter the way how [PKPaymentRequest](https://github.com/Adyen/adyen-react-native/blob/develop/ios/Configuration/ApplePay/ApplepayConfigurationParser.swift#L131-L143) is created.

**Comment by patrikmolnar** [comment]
Thanks a lot for the reply @descorp ! Do you have any ETA on this feature? I will have a look at the workaround in the meantime :)

**Comment by descorp** [comment]
We don't have concrete ETA, but will try to address this in Q3.
Will keep you posted.

**Comment by camil-adyen** [comment]
This feature was just released in [v2.4.0](https://github.com/Adyen/adyen-react-native/releases/tag/2.4.0). Closing this issue for now.
