### ISSUE TITLE
SEPA test credentials valid with live account

### ISSUE THREAD

**Issue by bbialas** [Adyen/adyen-react-native#476]
**Describe the bug**
It's possible to use SEPA test credentials to create a new payment instrument on the Live account.

**To Reproduce**
1. Open Adyen SEPA widget
2. Use SEPA test credentials from https://docs.adyen.com/development-resources/testing/test-other-payment-methods/#sepa-direct-debit
3. For example: A.Klaassen NL13TEST0123456789
4. Hit the save button.
5. Payment method is successfully created.

**Expected behavior**
There should be an error returned from Adyen, that credentials are invalid.

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.5.1

**Additional context**
Other payment methods are validated correctly, for example it's not possible to use test credit card credentials on Live account.

**Comment by descorp** [comment]
Hey @bbialas 

FYI, SEPA Direct Debit is also not recommended for e-commerce or one-off payments. 

SEPA request are not happen in real-time and will return status `Received` or `Authorized ` if IBAN is valid. This process might take up to 2 days. Till then merchants are expected to treat this transaction as pending.
See more in [Docs](https://docs.adyen.com/payment-methods/sepa-direct-debit/api-only/#present-the-payment-result)

---

In general, this question is out of the scope of React Native SDK. If you believe something is wrong with those transactions or you need assistance with SEPA Direct Debit - please reach out to [Adyen Support](https://www.adyen.help/hc/en-us/requests/new).
