### ISSUE TITLE
Where We need to pass this parameter in @adyen/react-native metadata: { subChannel: "IOS", }, 

### ISSUE THREAD

**Issue by ak19945** [Adyen/adyen-react-native#483]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by descorp** [comment]
Hey @ak19945 

I wasn't able to find any mentioning of `subChannel` in our public or internal documentation.
This question is beyond React-Native SDK scope, so please reach out Adyen Support via [Customer Area](https://ca-live.adyen.com/ca/ca/contactUs/support.shtml) or via email: support@adyen.com
