### ISSUE TITLE
Metadata is not showing on the adyen webhook notification while passing from our ios react native app 

### ISSUE THREAD

**Issue by miniunikove** [Adyen/adyen-react-native#484]
**Describe the bug**
Metadata is not showing on the adyen webhook notification while passing from our ios react native app 

**To Reproduce**
```js
 let payload = {
      "merchantAccount": "TheFragranceShopECOM",
      "amount": {
        "value": 100,
        "currency": "EUR"
      },
      "returnUrl": "adyencheckout://com.thefragranceshop",
      "reference": OrderId,
      "countryCode": "GB",
      metadata: {
				subChannel: "IOS"
			},
      channel: CHANNEL,
  
    }
```

**Expected behavior**
It should have received by the webhooks which is not working

**Comment by descorp** [comment]
Hey @miniunikove 

Unfortunately, this question is outside of ReactNative SDK scope.

To determine whether this is integration issue or bug on our API, please reach out Support Team via [Customer Area](https://ca-live.adyen.com/ca/ca/contactUs/support.shtml) or via email: support@adyen.com
