### ISSUE TITLE
Apple Pay showing up on Google client

### ISSUE THREAD

**Issue by simonarcher** [Adyen/adyen-react-native#489]
**Describe the bug**
When using the Drop-In component and payment session on iOS, Apple Pay shows up as expected (and as configured).
However on Android Apple Pay shows up as well, but even if there is no `applepay` in the `AdyenCheckout` config object.
I dont quite understand what controls the Apple Pay payment method to show up in Android and how to prevent it from happening.

**Screenshots**
<img width="369" alt="Screenshot 2024-07-09 at 13 53 07" src="https://github.com/Adyen/adyen-react-native/assets/10696147/bc80dba8-a4fa-44e7-9dd9-863b950bbeda">

this is the response to the `session` that I am requesting from my backend (the backend creates the session for me and this is just the body of the response I get from our backend), but should at least show that the `channel` is being recognised as `Android`

```
{
    "amount": {
        "currency": "EUR",
        "value": 895
    },
    "blockedPaymentMethods": [
        "sepadirectdebit"
    ],
    "channel": "Android",
    "countryCode": "NL",
    "expiresAt": "2024-07-09T13:09:44.000Z",
    "id": "[id]",
    "merchantAccount": "[merchant-account]",
    "reference": "196073",
    "returnUrl": "adyencheckout://[my-app-name]",
    "sessionData": "[session-data]",
    "shopperInteraction": "Ecommerce",
    "shopperLocale": "en-US",
    "shopperReference": "[reference]",
    "storePaymentMethod": false
}
```

and then this is the `config` object that the `<AdyenCheckout config={config} session={session} />` is being initialised with...

```
{
    "clientKey": "[my-client-key]",
    "environment": "test",
    "returnUrl": "adyencheckout://[my-app-name]",
    "locale": "en-US",
    "amount": {
        "currency": "EUR",
        "value": 895
    },
    "countryCode": "NL",
    "analytics": {
        "enabled": true,
        "verboseLogs": true
    },
    "googlepay": {
        "billingAddressRequired": true,
        "billingAddressParameters": {
            "format": "FULL",
            "phoneNumberRequired": true
        },
        "shippingAddressRequired": true,
        "shippingAddressParameters": {
            "allowedCountryCodes": [
                "NL",
                "UK"
            ],
            "phoneNumberRequired": true
        },
        "emailRequired": true
    }
}
```

as you can see in this case there is no `applepay` configuration though it still appears. 
What determines this then? 

```
@adyen/react-native": "2.0.1"
"react-native": "0.74.3"
```

thanks!

**Comment by descorp** [comment]
Hey @simonarcher 

This should not be possible, but this is second time I am hearing about this.

Could you reach-out Support Team via [Customer Area](https://ca-live.adyen.com/ca/ca/contactUs/support.shtml) or via email: [support@adyen.com](mailto:support@adyen.com) and provide your "session ID" and/or "pspReference" ?
We will investigate.

**Comment by descorp** [comment]
@simonarcher 

were you able to resolve the problem?

**Comment by descorp** [comment]
I am going to close this one due to lack of activity. Feel free to continue discussion here or reopen.
