### ISSUE TITLE
where we can enable or show the card holder name option in card payment details

### ISSUE THREAD

**Issue by ak19945** [Adyen/adyen-react-native#494]
![Simulator Screenshot - iPhone 15 - 2024-07-13 at 20 14 10](https://github.com/user-attachments/assets/80c9c6a9-3a60-4ee0-a4fc-538947808c52)
    
    **Describe the bug**
The `holderNameRequired` parameter does not work as expected in the Adyen React Native SDK. Setting this parameter to `true` does not display the cardholder name field in the card component.

**To Reproduce**
1. Set `holderNameRequired` to `true` in the configuration object for the card component.
2. Go to the example app.
3. Click on "Open DropIn".
4. Select the Card Payment Method.
5. Observe that the cardholder name field is not visible.

**Expected behavior**
The cardholder name field should be visible when `holderNameRequired` is set to `true`.

```javascript
const dropInConfiguration = {
  paymentMethodsConfiguration: {
    card: {
      holderNameRequired: true,
      addressVisibility: 'postalCode',
    },
  },
};
```

    Thanks 
  anilk@unikove.com

**Comment by descorp** [comment]
Hey @ak19945 

I believe you are using `paymentMethodsConfiguration` from Web SDK.
For react native we simplified it:

```js
const dropInConfiguration = {
  environment: 'test',
  clientKey: '{YOUR_CLIENT_KEY}',
  ...
  card: {
    holderNameRequired: true,
    addressVisibility: 'postalCode',
    ...
  }
};
```

See [Configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#card-component) reference.

**Comment by ak19945** [comment]
@descorp Thanks now also not coming

**Comment by descorp** [comment]
Hey @ak19945 

I have double checked, and it works as expected on 2.1.1
I would suggest to check your integration code.

**Comment by camil-adyen** [comment]
Hey @ak19945, any luck?
