### ISSUE TITLE
Long wait when waiting on iDeal 2.0 Success flow 

### ISSUE THREAD

**Issue by simonarcher** [Adyen/adyen-react-native#495]
**Describe the bug**
I recently updated our Adyen React Native package to `2.0.1` and using the new iDeal 2.0 session flow.

During our development testing our team is noticing sometimes very long waiting times when choosing the Success flow.

We occasionally get stuck on the "Waiting for full response" screen for up to minutes, which I assume at that point means it would never resolve and we have to try again later.

This behaviour seems inconsistent (sometimes it works within seconds, while sometimes it hangs forever), which makes me feel like its not something on our side, but on the test adyen ideal environment?

Is it possible to know that this behaviour is something that is "known" and "aware" by the team and if its something that is being looked on improving, or maybe suggestions how it can be minimised so it doesnt block our testing?

Just curious if it's something that others are also experiencing or if it is just me for some reason. :) 

Thanks!

![IMG_6650](https://github.com/user-attachments/assets/5ed07965-ee9d-401a-912a-2ad63a13cc62)

EDIT: after a while of waiting, I then got this message.. Not sure if this sheds light on where the possible issue could be coming from?

![IMG_6649](https://github.com/user-attachments/assets/61c60b4f-3109-40b6-93e0-20074267bf5a)

**Comment by descorp** [comment]
Hey @simonarcher 

Thanks for feedback 💚

We will report to our EMEA LPM team, but IMHO this seems like internal iDEAL issue 🤔

**Comment by descorp** [comment]
@simonarcher 

iDEAL confirms that this is a known issue on their "test environment".

**Comment by simonarcher** [comment]
Thank you for the update!
