### ISSUE TITLE
Pre populated data on form fields for credit card billing address

### ISSUE THREAD

**Issue by MarlonAEC** [Adyen/adyen-react-native#502]
**Is your feature request related to a problem? Please describe.**
One of the issues I have been struggling with is the billing address on cards on the Drop-in component. So if I'm adding a new card and I set the billing address it gets saved correctly but let us say I noticed I made a mistake will adding it and I hit again the button to change the address. All the fields I already populated get cleared and I have the type the whole address again from scratch. Is there a way to give a default value or save these values in some state or variable while I edit these fields to save the already populated values? check the video for reference:

https://github.com/user-attachments/assets/e0eb18be-2d8c-4501-b893-72acabf1209d

Is there a way to do this or the only way is to fully customize the components from scratch?

**Describe the solution you'd like**
Maybe add some default values for the adyen configuration object same as there is for the `allowedAddressCountryCodes` property for the card.

**Comment by descorp** [comment]
Hey @MarlonAEC 

Thank you for feedback 💚

This is indeed bug on our iOS SDK. 
Added to backlog

**Comment by descorp** [comment]
This was fixed on iOS [5.10.0](https://github.com/Adyen/adyen-ios/releases/tag/5.10.0) and released on 2.3.0.

Closing the thread, feel free to follow up.
