### ISSUE TITLE
Unable to close the Payment Bottom sheet when returning to the app from background

### ISSUE THREAD

**Issue by MarlonAEC** [Adyen/adyen-react-native#503]
**Describe the bug**
If I have the bottom sheet open when I put the app in the background and then I come back to the app the close button of the bottom sheet doesn't work anymore but the bottom sheet is still responsive.

**To Reproduce**
1. Click the button that triggers the `start()` function of your particular method of payment
2. click the close button (it closes correctly)
3. Hit the button again to open a second time the bottom sheet component
4. move the app to the background either by visiting your phone/simulator home screen
5. return to the app
6. Notice the close button doesn't work anymore but the bottom sheet is still functional and you can add data to it.

**Expected behavior**
The button should still work when you return to the app from the background

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://github.com/user-attachments/assets/df8c664f-ca35-4e34-bf71-6350d9fc6b08

**Desktop (please complete the following information):**
 - OS: Mac OS

**Smartphone (please complete the following information):**
 - Device: any phone or simulator
 - OS: I tried on IOS 16 and 17

**Additional context**
@adyen/react-native: "^2.1.1"
react-native: "0.71.7"

**Comment by descorp** [comment]
Hey @MarlonAEC 

Can one still finish the payment? 😄

---

I have to admit - this video made our iOS team just scratch our heads 😅
We were not able to reproduce this on iOS SDK and React Native SDK; iOS 16.5 and 17.4 both devices and Simulators.

So this behaviour reproducible on different iOS versions and both Simulator and physical device?
Do you see anything "suspicious" in Xcode logs ?

I wonder if any 3rd party dependency causing this 🤔
Is it possible to reproduce this behaviour on a blank RN project?

**Comment by MarlonAEC** [comment]
Hey @descorp thanks for the reply! I will try to create a blank project and give it a try but I had the same thoughts as you mentioned I went looking into XCode but there is nothing relevant there about it, neither in my metro console it's super weird for me too. I will try to reproduce it in a snack or something like that and I will pin you here later today.

**Comment by MarlonAEC** [comment]
Oh, I forgot to mention I haven't finished the whole integration because I'm waiting for my backend team to complete the backend part to be able to complete a successful payment but it is in our current sprint and should be ready in the next few weeks. I was also planning on revisiting this after the whole integration is completed

**Comment by MarlonAEC** [comment]
OK, I was able to figure it out is not a problem on your side guys just a mistake in our team code with a forced re-render my bad for opening this one. I will close this one since is not longer relevant sorry for the problems @descorp

**Comment by descorp** [comment]
No problem, we are here to help :)
Thanks for letting us know the outcome!
