### ISSUE TITLE
Apple pay not showing up in drop in

### ISSUE THREAD

**Issue by zegenerative** [Adyen/adyen-react-native#504]
**Describe the bug**
Even though the payment methods response includes apple pay, the drop in does not show the option

**To Reproduce**
1. Implement advanced flow and [configure apple pay](https://docs.adyen.com/payment-methods/apple-pay/react-native-drop-in/) 
2. Build for iOS
3. Open drop in

**Expected behavior**
Drop in opens and shows Apple Pay as an option (response from paymentMethods)

**Response**
```json
[
  {
    "brands": ["amex", "bcmc", "cartebancaire", "mc", "visa"],
    "name": "Credit en Debit card",
    "type": "scheme"
  },
  {
    "brands": ["mc", "visa"],
    "configuration": {
      "merchantId": "XXX",
      "merchantName": "XXX"
    },
    "name": "Apple Pay",
    "type": "applepay"
  },
  {
    "brands": ["bcmc", "mc", "visa"],
    "name": "Bancontact card",
    "type": "bcmc"
  },
  {
    "configuration": { "gatewayMerchantId": "XXX", "merchantId": "50" },
    "name": "Google Pay",
    "type": "googlepay"
  },
  {
    "issuers": [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []],
    "name": "iDEAL",
    "type": "ideal"
  }
]
```

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.1
 - Version 2.2.0
 - 
<img width="405" alt="Screenshot 2024-07-26 at 11 09 32" src="https://github.com/user-attachments/assets/60475874-3be4-4829-b298-b44fd46b5aee">

**Comment by FaresHamel** [comment]
I think you should enable apple pay alone for ios after reading the documentation I found that adyen open api apple pay just for web but for mobile you should enable apple pay certificate

**Comment by zegenerative** [comment]
We have seen it working before, as we have already configured Apple Pay using a certificate. Perhaps an issue with 2.2.0?

**Comment by descorp** [comment]
Hey @zegenerative 

Indeed, one needs an ApplePay Certificate, a MerchantID configured in "Signing & Capabilities" and same `MerchantID` in ApplePay [Configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#applepay-component).
Make sure you have provided both `amount` and `countryCode`.

**Comment by zegenerative** [comment]
In signing and capabilities I believe you mean `merchantIdentifier`, correct?

**Comment by zegenerative** [comment]
If I add the following to the drop in configuration it crashes the app: 
`
 amount: {
      value: 42,
      currency: "EUR"
    }
`  
value is a number. a configuration without amount does not crash the app. We are using the advanced flow, so I find it a bit odd that I have to specify the amount myself, as it is also coming as a response from our back end via our `/payments` endpoint and the first thing a user sees is not a button with the value, but a list of payment methods (as you can see in the screenshot)

EDIT: found out value was actually 0 and apparently that crashes the drop in and app. Still not being able to see Apple Pay with a positive value.

**Comment by descorp** [comment]
> In signing and capabilities I believe you mean merchantIdentifier, correct?

This part:

![Screenshot 2024-07-29 at 12 27 51](https://github.com/user-attachments/assets/8c8ff426-4e07-42c8-a994-06412a948f23)

Same value must be provided to
```js
   applepay: {
    merchantID: '{YOUR_APPLE_MERCHANT_ID}',
  }
```

> I find it a bit odd that I have to specify the amount myself

This is [how ApplePay works](https://developer.apple.com/documentation/passkit_apple_pay_and_wallet/apple_pay/payment_token_format_reference#overview): it will generate a token for a specific amount. Adyen API will verify that the amount inside of the token is matching amount requested via POST `\payments`.

> Still not being able to see Apple Pay with a positive value.

There is a small trick: you can enable `verboseLogs` and check Xcode logs for warning message that explains why Apple Pay is not displayed.
```js
  analytics: {
    verboseLogs: true,
  },
```

**Comment by zegenerative** [comment]
Inspected the logs in XCode as you suggested. Can you elaborate where exactly this configuration is missing?  
`AdyenAppearance: class not linked or does not conform to AdyenAppearanceProvider protocol
Failed to instantiate ApplePayComponent because ApplePayConfiguration is missing`  
Because on my side I can confirm the signing and capabilities are correct:
![Screenshot 2024-07-29 at 13 32 17](https://github.com/user-attachments/assets/5a470169-8d35-4d29-bc8d-ceacb9972625)
and in the drop in config:  
```
applepay: {
    merchantID: Constants?.expoConfig?.extra?.environment.PAYMENT_APPLEPAY_MERCHANT_ID,
    merchantName: Constants?.expoConfig?.extra?.environment.PAYMENT_MERCHANT_ACCOUNT,
  }
```

**Comment by descorp** [comment]
> AdyenAppearance: class not linked or does not conform to AdyenAppearanceProvider protocol Failed to instantiate ApplePayComponent because ApplePayConfiguration is missing

This is part of [iOS customisation](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Customization.md) and not related to ApplePay. 

> and in the drop in config:

You sure both `merchantID ` and `merchantName` are populated?
And you have both `amount` and `countryCode` ?

```
  countryCode: 'FR',
  amount: { currency: 'EUR',  value: 9800, },
```

**Comment by zegenerative** [comment]
You sure? Because it clearly states 

> {...} because ApplePayConfiguration is missing

Yup, all configured and populated. We are now checking if apple pay is configured correctly in the adyen test environment. 

```json
{
  "amount": {
    "currency": "EUR",
    "value": 1578.72
  },
  "analytics": {
    "enabled": true,
    "verboseLogs": true
  },
  "applepay": {
    "merchantID": "merchant.com.adyen.XXX",
    "merchantName": "XXX"
  },
  "card": {
    "holderNameRequired": true,
    "showStorePaymentField": false
  },
  "clientKey": "XXX",
  "countryCode": "EN",
  "environment": "test",
  "googlepay": {
    "merchantAccount": "XXX"
  },
  "locale": "en-US",
  "returnUrl": "XXX"
}
```

**Comment by descorp** [comment]
And nothing in Xcode log?
BTW, if you are testing on physical device, your have at least one "mc" or "visa" card in your wallet?

**Comment by zegenerative** [comment]
Well in XCode you can see that it failed to open ApplePayComponent, because of the previously mentioned error. 

It happens in the iOS simulator as well as on a physical device, regardless if I have a stored payment method or not.

**Comment by descorp** [comment]
> Well in XCode you can see that it failed to open ApplePayComponent, because of the previously mentioned error.

Could you share a screenshot or log?

**Comment by zegenerative** [comment]
I already shared the log from XCode, but here is a screenshot. I get this when opening the drop in. 

![Screenshot 2024-07-29 at 15 10 15](https://github.com/user-attachments/assets/486267c7-7e7e-43b6-a0c1-e1a939e7cc0a)

![Screenshot 2024-07-29 at 15 11 09](https://github.com/user-attachments/assets/a8ae37d4-aa9d-4612-95a2-065cbf31b0a9)

again, all configurations seem correct and populated. I am logged in with an apple account

**Comment by descorp** [comment]
Aha, 

> Failed to instantiate ApplePayComponent because ApplePayConfiguration is missing

This is the line I was looking for. This is not very descriptive, but it shows that `ApplePayConfiguration` was not created.
That means that at least one of `merchantID`, `merchantName`, `amount` or `countryCode` is invalid.

On [your config](https://github.com/Adyen/adyen-react-native/issues/504#issuecomment-2255808886):

`EN` is not a valid ISO Country Code. Could you try your actual country code?

**Comment by zegenerative** [comment]
And with the apple pay configuration you mean on the adyen test environment side and not on the front end side?

**Comment by zegenerative** [comment]
no apple pay with:

config:
```json
{
  "config": {
    "amount": {
      "currency": "EUR",
      "value": 1200.95
    },
    "analytics": {
      "enabled": true,
      "verboseLogs": true
    },
    "applepay": {
      "merchantID": "merchant.com.adyen.XXX.XX",
      "merchantName": "XXX"
    },
    "card": {
      "holderNameRequired": true,
      "showStorePaymentField": false
    },
    "clientKey": "XXX",
    "countryCode": "NL",
    "environment": "test",
    "googlepay": {
      "merchantAccount": "XXX"
    },
    "locale": "nl-NL",
    "returnUrl": "XXX"
  }
}
```

<details markdown=1><summary>I do see some native logs on opening the drop in:</summary>
[UIKitCore] Unable to simultaneously satisfy constraints.
Probably at least one of the constraints in the following list is one you don't want.
Try this:
(1) look at each constraint and try to figure out which you don't expect;
(2) find the code that added the unwanted constraint or constraints and fix it.
(
"<NSLayoutConstraint:0x6000019f86e0 Adyen.PaymentMethodListCo....leading ==
UILayoutGuide:0x60000012a060'UIViewLayoutMarginsGuide'.leading   (active, names:
Adyen.PaymentMethodListCo...:0x12f217700 )>",
"<NSLayoutConstraint:0x6000019f9310 Adyen.PaymentMethodListCo....trailing ==
UILayoutGuide:0x60000012a060'UIViewLayoutMarginsGuide'.trailing   (active, names:
Adyen.PaymentMethodListCo...:0x12f217700 )>",
"<NSLayoutConstraint:0x6000019fa350 UIStackView:0x12f2186d0.leading ==
UILayoutGuide:0x600000128540'UIViewLayoutMarginsGuide'.leading   (active)>",
"<NSLayoutConstraint:0x6000019fa710 UIStackView:0x12f2186d0.trailing ==
UILayoutGuide:0x600000128540'UIViewLayoutMarginsGuide'.trailing   (active)>",
"<NSLayoutConstraint:0x6000019f90e0 UIImageView:0x12f217950.width == 40   (active)>",
"<NSLayoutConstraint:0x6000019f9b80 'fittingSizeHTarget' UITableViewCellContentView:0x12f217340.width == 0
(active)>",
"<NSLayoutConstraint:0x6000019f8b90 'UISV-canvas-connection' UIStackView:0x12f2186d0.leading ==
UIImageView:0x12f217950.leading   (active)>",
"<NSLayoutConstraint:0x6000019f8730 'UISV-canvas-connection' H:[UIStackView:0x12f2181d0]-(0)-|   (active,
names: '|':UIStackView:0x12f2186d0 )>",
"<NSLayoutConstraint:0x6000019fa990 'UISV-spacing'
H:[UIImageView:0x12f217950]-(16)-[UIStackView:0x12f2181d0]   (active)>",
"<NSLayoutConstraint:0x6000019f8be0 'UIView-leftMargin-guide-constraint'
H:|-(8)-[UILayoutGuide:0x60000012a060'UIViewLayoutMarginsGuide'](LTR)   (active, names:
'|':UITableViewCellContentView:0x12f217340 )>",
"<NSLayoutConstraint:0x6000019fa3a0 'UIView-leftMargin-guide-constraint'
H:|-(0)-[UILayoutGuide:0x600000128540'UIViewLayoutMarginsGuide'](LTR)   (active, names:
Adyen.PaymentMethodListCo...:0x12f217700, '|':Adyen.PaymentMethodListCo...:0x12f217700 )>",
"<NSLayoutConstraint:0x6000019f8eb0 'UIView-rightMargin-guide-constraint'
H:[UILayoutGuide:0x60000012a060'UIViewLayoutMarginsGuide']-(8)-|(LTR)   (active, names:
'|':UITableViewCellContentView:0x12f217340 )>",
"<NSLayoutConstraint:0x6000019fa490 'UIView-rightMargin-guide-constraint'
H:[UILayoutGuide:0x600000128540'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names:
Adyen.PaymentMethodListCo...:0x12f217700, '|':Adyen.PaymentMethodListCo...:0x12f217700 )>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x6000019f90e0 UIImageView:0x12f217950.width == 40   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may
also be helpful.
</details>

Could it perhaps be that our adyen test environment is configured incorrectly in regards to apple pay? And that it's not an issue on the front end configuration?

**Comment by descorp** [comment]
Hey @zegenerative 

Sorry, I see what the issue is.
```
"value": 1200.95
```

Amount must be `Int` - our API operates in  [minor units](https://docs.adyen.com/development-resources/currency-codes/#minor-units).

**Comment by zegenerative** [comment]
Awesome!

<img width="378" alt="Screenshot 2024-07-30 at 11 09 31" src="https://github.com/user-attachments/assets/12a33d44-0868-43d4-b880-a19682acbeec">

**Comment by descorp** [comment]
Thank for confirming! 
We will add "improving error and validation messages" to your backlog 💚

**Comment by FaresHamel** [comment]
@zegenerative can you show me how you import or using apple pay , adyen it's work now and the configuration contain 2 cards one of this cards is apple pay but not showing on the phone ios , can you help ?

**Comment by descorp** [comment]
Hey @FaresHamel 

> adyen it's work now and the configuration contain 2 cards one of this cards is apple pay but not showing on the phone ios , can you help ?

So you can see Apple Pay on Simulator but not on physical device?

**Comment by FaresHamel** [comment]
@descorp no I cannot see it I don't have the configuration for active apple pay , from my adyen I have two cards repond apple pay and visa card , but I see just visa card not apple pay in Simulator or physical device

**Comment by descorp** [comment]
@FaresHamel 

Have you follow documentation on [How to enable Apple Pay](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay/?tab=setup-own-ios_2#process-overview) with **own Apple Pay certificate** on iOS?

**Comment by FaresHamel** [comment]
@zegenerative step please to enable apple pay , my payment methods contain apple pay and credit card butin the simulator it's how just credit cards and this mean I did not enable apple pay ?

**Comment by descorp** [comment]
Hey @FaresHamel 

- check that you follow [Apple guidelines](https://developer.apple.com/help/account/manage-identifiers/enable-app-capabilities#enable-apple-pay)
   -  you have `merchantID` selected in Xcode "Signing & Capabilities"
- check that you have [correct configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#applepay-component)
   - `countryCode` must be present
   - `amount` must be present and `value` is Integer
   - `merchantID` must be present
   - `merchantName` must be present
   
   If you have doubts - enable `analytics.verboseLogs`

**Comment by FaresHamel** [comment]
@descorp  
in this configuration he sent the payment method in the configuration 
```json
{
  "config": {
    "amount": {
      "currency": "EUR",
      "value": 1200.95
    },
    "analytics": {
      "enabled": true,
      "verboseLogs": true
    },
    "applepay": {
      "merchantID": "merchant.com.adyen.XXX.XX",
      "merchantName": "XXX"
    },
    "card": {
      "holderNameRequired": true,
      "showStorePaymentField": false
    },
    "clientKey": "XXX",
    "countryCode": "NL",
    "environment": "test",
    "googlepay": {
      "merchantAccount": "XXX"
    },
    "locale": "nl-NL",
    "returnUrl": "XXX"
  }
}
```

but I have another on can you take look please if it's true 
```js
<AdyenCheckout
                config={{
                  environment: 'live',
                  apiKey: apiKey,
                  clientKey: clientKey,
                  countryCode:countrycode1,
                  amount: {
                    currency:countrycode,
                    value: parseInt(total * 100)
                  }, // Value in minor units
                  returnUrl: 'myUlr://payment',
                  showStorePaymentField: false, /
                }}   
               paymentMethods={paymentMethods}
                onSubmit={handleSubmit}
                onAdditionalDetails={(paymentData, component) => {
                  console.log('Detail');
                }}
                 onError={closeAdyen} 
                 >
               <MyCheckOutViewBottom/>
              </AdyenCheckout>
```

1) int payment method paymentMethods={paymentMethods} I have two cards apple pay and another card apple pay card contain the merchantId and merchantName so should this work ? and the marchentId it's a value like this 000999203 for example and in my apple payment certificate I send the merchantId look like what did you say in the documentation 
merchant.com.adyen.000992..... this is just an example what do you think about this configuration , I'am confused in the merchanId should be the same ? merchant.com.adyen..... or what and thank you for your time

**Comment by descorp** [comment]
Hey @FaresHamel 

```
"value": 1200.95
```

Amount must be integer

**Comment by descorp** [comment]
@FaresHamel 

> and the marchentId it's a value like this 000999203

As you have observed, `\paymentMethods` JSON for `applepay` does contain `merchantID`, and its value does not match **merchant.com.XXX pattern** because it is "merchantID" your Web Apple Pay integration is using via [Adyen Certificate](https://docs-admin.is.adyen.com/payment-methods/apple-pay/enable-apple-pay).

>  so should this work 

No. Is not common to use own certificate on Web, hence our SDK do not expect `merchantID` value  from `\paymentMethods` JSON. Also iOS can operate with multiple `merchantID` (unlike Web), hanse it would be limiting to hardcode only one.

---

Please follow React-Native [Configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#applepay-component) and provide applepay to `AdyenCheckout.config` :
```json
"applepay": {
      "merchantID": "merchant.com.adyen.XXX.XX",
      "merchantName": "XXX"
    },
```

**Comment by FaresHamel** [comment]
@descorp first of all thank you for your response , yes the merchantId 005050 ex , it's used on our website ,so should I create another one look like this merchant.com.XXX  for ios apple pay ? and \paymentMethods it's a JSON file contain two aconfiguration card and apple pay the apple pay object contain merchant Id and merchant Name both using on web , my question is should I create another one for ios devise ?

**Comment by descorp** [comment]
@FaresHamel 

> should I create another one look like this merchant.com.XXX 

Yes. 

- check that you follow [Enable Apple Pay](https://developer.apple.com/help/account/manage-identifiers/enable-app-capabilities#enable-apple-pay) Apple guidelines
   -  you have `merchantID` selected in Xcode "Signing & Capabilities"
   
- check that you have [correct configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#applepay-component)
   - `countryCode` must be present
   - `amount` must be present and `value` is Integer
   - `applepay.merchantID` must be present
   - `applepay.merchantName` must be present

**Comment by FaresHamel** [comment]
@descorp thank you right now I have apple payment card showing  in the simulator because in my apple dev account I had added before an example of MerhcantId and the same example I passed it in the configuration of AdyenCheckOut , now I need to create a real one in our adyen account with this format merchant.com.adyen.XXX.XX and the merchantId for web Adyen Certificate different to mobile MerchantId ?

**Comment by descorp** [comment]
> the merchantId for web Adyen Certificate different to mobile MerchantId 

Correct. 
You can find full instruction in our [Apple Pay docs](https://docs-admin.is.adyen.com/payment-methods/apple-pay/enable-apple-pay?tab=setup-own-ios_2#process-overview). You need to follow "Use your own Apple Pay certificate" then "iOS" tabs.

> create a real one in our adyen account

3 steps:
- Create Apple Pay Merchant ID
- Enable Apple Pay in your app
- Create payment processing certificate

**Comment by FaresHamel** [comment]
@descorp I was able to see apple pay in the simlator and when I change the simulator or run it on real device apple pay not show on the simulator

**Comment by FaresHamel** [comment]
@descorp and what about returnUrl: 'myapp://adyencheckout', should I replace 'myapp://adyencheckout' with my bundle identifier or what ? and thank you

**Comment by descorp** [comment]
@FaresHamel 

> I was able to see apple pay in the simlator and when I change the simulator or run it on real device apple pay not show on the simulator

- Ensure the device is set to a region where Apple Pay is supported and that a valid card is added to the Wallet.
- Double-check your project’s entitlements and configuration to ensure Apple Pay is correctly set up.

> about returnUrl: 'myapp://adyencheckout', should I replace 'myapp://adyencheckout' with my bundle identifier or what 

No, not necessary - on iOS you can use any `returnUrl` you want.
You can find more info here in [Configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#root-configurations) documentation

**Comment by FaresHamel** [comment]
@descorp thank you I can now see apple pay , but I have question please when I make request to adyen to get payment method when the user is login it's send to me credit card and apple pay , but when the user is not login the response from payment method is just credit card , and the parameters I send in the two setuation it's the same for example I don't send any additional parametres in the request tell adyen the user is login or not any seggustion ?

**Comment by descorp** [comment]
> any seggustion

Nope, sorry
This is purely part of your implementation and I doubt it have anything to do with React Native SDK.
I would suggest checking with you backend team
