### ISSUE TITLE
/Build/Products/Debug-iphonesimulator/Adyen/Adyen.modulemap' not found

### ISSUE THREAD

**Issue by FaresHamel** [Adyen/adyen-react-native#505]
I get this error react native 0.74.0
I tried many solution but nothing work with me .
and when I go to folder /Build/Products/Debug-iphonesimulator/ I cannot find folder Adyen even I install it and linked it

**Comment by descorp** [comment]
Hey @FaresHamel 

Can you try running `pod update` ?
Can you reproduce that on a blank react native 0.74.0 project?
Have you updated your project from lower version or it was started as react native 0.74.0?

**Comment by FaresHamel** [comment]
Hello @descorp 
i tried every solution , delete pod ,install it again , but if are getting this error ,what I found that the xcode>DringData>yourProjectname>build will not contain Adyen packages you can do everything every solution ,delete the build and build it again , you need to create new one that's what I found

**Comment by descorp** [comment]
Just to clarify:

Can you reproduce that on a [blank 0.74.0 project](https://reactnative.dev/docs/getting-started-without-a-framework)?
Have you updated your project from lower version of RN or it was originally a RN 0.74.0?

**Comment by FaresHamel** [comment]
no I did not update my project from old version react native to 0.74.0 , the project created with this version 0.74.0 .

**Comment by descorp** [comment]
When did this issue start?

In general - I don't think this is an Adyen issue.
It is [common Cocoapods](https://stackoverflow.com/questions/55675694/how-to-fix-cocoapod-modulemap-file-not-found) issue and `Adyen` happens to be the first package in alphabetic order.

For an experiment, try removing `yarn remove @adyen/react-native`  and check if the issue persists.

**Comment by descorp** [comment]
@FaresHamel 

Any progress resolving on this issue?

**Comment by FaresHamel** [comment]
@descorp I create new project and install adyen again but the old project all solution not working so I resolve it with create new project

**Comment by descorp** [comment]
I am going to close this ticket then.
