### ISSUE TITLE
Android only - On Adyen payment sheet close button is displaying on the left side instead of right side.

### ISSUE THREAD

**Issue by amorales2020** [Adyen/adyen-react-native#513]
**Describe the bug**
On latest Mobile React
![Android_Issue](https://github.com/user-attachments/assets/b87d78e5-8109-4b66-aabf-3cf429808ec5)
 Native app 3.31.800(44) when user checkout and click on credit card, in payment sheet close button is displaying at left corner instead of right corner.

**To Reproduce**
1. Open DYN/GRG app 3.31.800(44).
2. Login as user.
3. Click on cart.
4. Click on checkout.
5. Click on credit card.
6. Observe in payment sheet close icon is displaying at left corner instead of right corner.

![image](https://github.com/user-attachments/assets/bd5c9d6b-0797-4acd-9056-d534e2562bbe)

**Expected behavior**
There is an inconsistency between the IOS UI and the Android UI. The experience for the customer should be the same. The expected behaviour is to have the close X on the right side same for Android.

**Screenshots**

**Smartphone (please complete the following information):**
 - Android. Dynamite and Garage Mobile APP version 3.31.800(44).

**Additional context**
The inconsistency in the UI could create confusion for the GDI Mobile APP customers

**Comment by descorp** [comment]
Hey @amorales2020 

Let's agree that design decisions can be subjective :)

> The expected behaviour is to have the close X on the right side same for Android.

Not according to the [Material Design](https://m2.material.io/components/app-bars-top#usage) "Contextual action bar".

> IOS UI and the Android UI. The experience for the customer should be the same.

I understand your point, but it's important to recognize that iOS and Android follow different paradigms. We are aiming to provide a "native" experience. Few people own both iOS and Android, but everyone will compare their payment experience with other apps and services on their phones.

In our design, Adyen is aim to maintain a visual similarity to the Google Pay on Android and the Apple Pay on iOS:

<img src="https://github.com/user-attachments/assets/252ea4f4-103c-48fc-b669-6e3e5295dbfb" width="300">
<img src="https://github.com/user-attachments/assets/ee6bdf48-a059-4c48-a66f-c66e54d2b29b" width="300">

**Comment by descorp** [comment]
I am going to close this topic due to lack of activity.
