### ISSUE TITLE
UI Enhancement RN v2.2

### ISSUE THREAD

**Issue by Alieltahan** [Adyen/adyen-react-native#518]
**Is your feature request related to a problem? Please describe.**

1. (Android ) When adding/paying with 3DS card, an overlay appears with cancel Btn after calling onSubmit.
![image](https://github.com/user-attachments/assets/30984920-9b78-4110-90d2-4ec7d339cfc5)

2. ( Android ) After the 3DS model appears, when cancelling there is an Alert modal appears.
![image](https://github.com/user-attachments/assets/bc40f3a9-3102-4d00-be63-be5879e75da0)

3. ( Android ) Loading spinner indicator color.  
![image](https://github.com/user-attachments/assets/0013b4a9-d43c-4383-a4cf-07c8a875c447)

**Describe the solution you'd like**
1. Suggesting to disable the cancel Button or remove it, as when pressing on it, the user still redirected to the 3DS challenge however Adyen overlay is dismissed.
2. We don't need to show the user the Alert modal.
3. Is. there a way  to customize the color of the Loading spinner ?

**Additional context**
We are using RN v2.2

**Comment by descorp** [comment]
Hey @Alieltahan 

`1)` and `2)` These are a good points - we have added ticket for Android SDK to hide this popup, unless actual error happened. Thanks for feedback!
`3)` You should be able to set spinner color via 

```xml
    <style name="AdyenCheckout" parent="Adyen">
        <item name="android:indeterminateTint">@color/md_amber_A400</item>
    </style>
```

**Comment by Alieltahan** [comment]
Thank you @descorp 

Also when Submit the payment, during the loading, the Pay Btn is disabled, but yet taking the look/styles of active btn.

If we may add enhancement as well here as disable look/style for the Btn, will make better experience.

Btn during the loading state as attached image:
![image](https://github.com/user-attachments/assets/2c477287-ab0c-42ec-9454-0d98e13896b1)

**Comment by descorp** [comment]
Hey @Alieltahan 

Are you checking it on emulator? Do you see same behaviour on real device as well?

In my experience, on Android emulator "loading" overlay is not visible sometimes.

![Screenshot_20240917_155923_AdyenExample](https://github.com/user-attachments/assets/87ea3f8f-36b5-49b1-b96c-806ae18968ae)

**Comment by Alieltahan** [comment]
Thanks for your feedback @descorp 
I tested on real device and seems the loading overlay is there.

Thank you for your support.

**Comment by Alieltahan** [comment]
Hello @camil-adyen 
Appreciate your feedback on the points 1 & 2 and the release version.
Also following [Point](https://github.com/Adyen/adyen-react-native/issues/518#issuecomment-2352705812)

**Comment by ali-v9** [comment]
@descorp May u please update on this UI enhancement for point 1 & 2 ?

> Hey @Alieltahan
> 
> `1)` and `2)` These are a good points - we have added ticket for Android SDK to hide this popup, unless actual error happened. Thanks for feedback!
> ```

**Comment by Alieltahan** [comment]
Hello @descorp May u please update on this UI enhancement for point 1 & 2 ?
Also following [Point](https://github.com/Adyen/adyen-react-native/issues/518#issuecomment-2352705812) 

> Hey @Alieltahan
> 
> `1)` and `2)` These are a good points - we have added ticket for Android SDK to hide this popup, unless actual error happened. Thanks for feedback!

**Comment by descorp** [comment]
Hey @Alieltahan 

There is no updates yet - still in our backlog.
