### ISSUE TITLE
Take the user to "Set up Apple Pay" if the user doesn't have any Saved cards

### ISSUE THREAD

**Issue by divyegd** [Adyen/adyen-react-native#520]
**Describe the bug**
Currently, when the user clicks on Pay with Apple Pay, nothing happens and we get this error message in the console:

{ message: 'The user can’t make payments on any of the payment request’s supported networks.',
  description: 'The user can’t make payments on any of the payment request’s supported networks.' }

However in other applications, the user is taken to "Set up Apple Pay", 

https://github.com/user-attachments/assets/88378948-b1f4-43e6-a81f-8bc396279104

**Comment by descorp** [comment]
Hey @divyegd 

Your device's wallet has no cards that are suitable for this payment.
To make a proper test - use [a sandbox account](https://developer.apple.com/apple-pay/sandbox-testing/) and add a couple of test cards for different networks (VISA, MC, Amex, etc).

---

We have property `allowOnboarding` for [Apple Pay configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#applepay-component) that controls this. Once enabled - it will open the "Card Onboarding" (aka "Set up Apple Pay") screen in case the wallet is empty or no suitable cards are found.
