### ISSUE TITLE
Execution failed for task ':adyen_react-native:compileDebugJavaWithJavac'. > error: invalid source release: 17

### ISSUE THREAD

**Issue by faizantariq1** [Adyen/adyen-react-native#521]
**Describe the bug**
I'm trying to get Adyen(2.3.0) to work with my project but it fails with Android with the following error

> > Task :adyen_react-native:compileDebugJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':adyen_react-native:compileDebugJavaWithJavac'.
> > error: invalid source release: 17

**To Reproduce**
react native: 0.69
compileSdkVersion = 34
targetSdkVersion = 34

**Screenshots**

<img width="734" alt="Screenshot 2024-09-02 at 4 16 19 PM" src="https://github.com/user-attachments/assets/92c210c0-5e38-4e89-83e8-ac55e192780e">

**Smartphone (please complete the following information):**
 - Device: Android Simulator

**Comment by faizantariq1** [comment]
this is resolved after upgrading java version to 17.

**Comment by descorp** [comment]
Hey @faizantariq1 

Thanks for confirming! 
What version of Java you had?

**Comment by faizantariq1** [comment]
previously 11
