### ISSUE TITLE
Android AdyenInstant "stacking" `didProvide` calles

### ISSUE THREAD

**Issue by descorp** [Adyen/adyen-react-native#53]
```
To reproduce:
1. start payment on Android
2. cancel payment with the "cancel and go back to XX"
3. -> `handleDidProvide` gets called once with a cancel result
4. start payment again (in the same session)
5. -> `handleDidProvide` gets called twice with a cancel result
6. start payment again (in the same session)
7. -> `handleDidProvide` gets called three times with a cancel result
8. etc

The other (for us more serious) issue we're having that is also Android specific is:
1. start payment on Android
2. cancel payment with the "cancel and go back to XX"
3. -> `handleDidProvide` gets called once with a cancel result
4. start payment again (in the same session)
5. -> `handleDidProvide` gets called _immediately_ with a cancel result, without doing anything in the webview. This means that it is not possible to complete a payment once you've cancelled once because the cancel flow is triggered immediately.

```

_Originally posted by @kadikraman in https://github.com/Adyen/adyen-react-native/issues/44#issuecomment-1288802869_

**Comment by descorp** [comment]
Hey @kadikraman 

This is "another bug", that I have [mentioned earlier](https://github.com/Adyen/adyen-react-native/issues/44#issuecomment-1278576565).
It happens due to the nature of Android ViewModel lifecycle: when PaymentComponent (any) attached to the Activity - it "contaminates" it with it's own state.
Fix for this will be an introduction of an extra fragment to isolate individual payment's lifecycle.
 
We are planing to fix for beta6 release as well ASAP

**Comment by kadikraman** [comment]
Thank you @descorp - look forward to the fix!

**Comment by descorp** [comment]
Hey @kadikraman 

This bug should be fixed in [1.0.0-beta6](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.6)
Could you verify?

**Comment by kadikraman** [comment]
Can confirm, this is working for me now on beta 6 🎉

**Comment by descorp** [comment]
Then I'll close this issue. Feel free to continue discussion here or reopen if problem occurs..
