### ISSUE TITLE
showPreselectedStoredPaymentMethod: false - still showing stored methods (iOS)

### ISSUE THREAD

**Issue by zegenerative** [Adyen/adyen-react-native#533]
**Describe the bug**
Providing a `showPreselectedStoredPaymentMethod: false` to the drop in config is not working

**To Reproduce**
1. configure drop in 2.4.0 with said property

**Expected behavior**
No stored payment methods

**Screenshots**
![Simulator Screenshot - iPhone 15 Pro - 2024-09-25 at 16 56 50](https://github.com/user-attachments/assets/abce61ee-d1e7-4d2d-a35d-b47dc3410e29)

**Smartphone (please complete the following information):**
 - Device: iPhone15
 - OS: iOS 17.5
 - Version 2.4.0

**Comment by descorp** [comment]
Hey @zegenerative 

Unfortunately, this is not how `showPreselectedStoredPaymentMethod ` works - it only disable first UI step.

If you wish your shoppers to not use stored cards - you can use `card.showStorePaymentField` on [configuration](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Configuration.md#card-component).

Are you using \sessions or \payments (aka "Advance") API flow ?

**Comment by zegenerative** [comment]
I see, that is a misunderstanding then. We are using the advanced flow and we want to prevent apple pay from being a stored method, since that needs extra configuration on the back end and is now resulting in errors.

Our back end will probably filter apple pay from being stored. Thanks for the explanation.

**Comment by descorp** [comment]
>  prevent apple pay from being a stored method

My assumption - your backend is always sending [storePaymentMethod](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-storePaymentMethod) as **true**. 
I would advice to reach out our Support Team via [Customer Area](https://ca-live.adyen.com/ca/ca/contactUs/support.shtml) or via email: [support@adyen.com](mailto:support@adyen.com).

> Our back end will probably filter apple pay from being stored. 

You can modify JSON collection you have received from `paymentMethods` on backend or on client.

FYI, on [2.4.0](https://github.com/Adyen/adyen-react-native/releases/tag/2.4.0) we added option for shopper to request removal of a stored payment methods. In Advanced  flow it requires you to implement a callback `onDisableStoredPaymentMethod` and use [/disable](https://docs.adyen.com/api-explorer/Recurring/68/post/disable) API endpoint.

**Comment by zegenerative** [comment]
Thank you, I have noticed the /disable option, but that requires an additional BE change as well

**Comment by descorp** [comment]
I am going to close this thread.
Feel free to continue the discussion or create a separate thread if you need any assistance with `/disable` or something else.
