### ISSUE TITLE
2.4.0 - Typescript: Property 'handle' does not exist on type 'AdyenComponent'

### ISSUE THREAD

**Issue by zegenerative** [Adyen/adyen-react-native#534]
**Describe the bug**
AdyenCheckout onSubmit callback expects a second argument 'component' typed as AdyenComponent, but the component needs to be able to handle additional action, which seems only to be present in `AdyenActionComponent`

**Comment by descorp** [comment]
Hey @zegenerative 

This was done on purpose, since not every component is capable of handling actions or not in every case it is needed.
However, you are right that `AdyenComponent` is limiting, and we can ignore Interface Segregation Principle here for the general convenience 🤔

**Comment by descorp** [comment]
Improved!
#540 

Thanks for feedback 💚

**Comment by zegenerative** [comment]
@descorp thanks! when will this be released?

**Comment by descorp** [comment]
Hey @zegenerative 

Since this is not a blocking issue, we will release this at 2.5.0. ETA end of October.

**Comment by gunnartorfis** [comment]
@descorp FYI this is still an issue in 2.4.1.

**Comment by camil-adyen** [comment]
HI @gunnartorfis, can you please confirm that the issue has been resolved in our [latest release](https://github.com/Adyen/adyen-react-native/releases/tag/2.5.0)?

**Comment by irawel** [comment]
Hi @camil-adyen, I can confirm that this has been fixed on the release 2.5.0.
