### ISSUE TITLE
Handling Multiple API Environments in an App Using Adyen SDK

### ISSUE THREAD

**Issue by vanGalilea** [Adyen/adyen-react-native#538]
Hey there 👋🏻 

We are currently integrating Adyen into our app at MyWheels, and we’re encountering a challenge with managing multiple environments. Our app includes a feature that allows switching between development and production API environments via a secret developer menu (for QA purposes). This environment switching happens in runtime and we are wondering how best to manage this in conjunction with your SDK.

To ensure we can test integrations properly without risking the integrity of our production environment, we would like to understand how other clients may have dealt with this issue.

Specifically:
- Have you seen clients manage this by maintaining two separate apps (one for production connected to Adyen’s production environment, and another for internal use with the development environment)?
- Do you have suggestions for handling environment switching with the Adyen SDK within a single app, while still ensuring a reliable and testable integration before release? 
   1. Is it even possible due to nature of the Expo plugin that takes `merchantIdentifier` in build time?
   2. This `merchantIdentifier` is also being filled as part of `AdyenCheckout`'s `config` prop

Our goal is to ensure that we can test payments in a development environment while maintaining confidence in our production releases. Any best practices or recommendations you can share would be greatly appreciated!

Thank you in advance for your help 👍🏻

**Comment by descorp** [comment]
Hey @vanGalilea 

> Is it even possible due to nature of the Expo plugin that takes merchantIdentifier in build time

It is possible to provide a collection to the `merchantIdentifier` property:
```json
  "plugins": [
    [
      "@adyen/react-native",
      {
        "merchantIdentifier": [
          "merchant.com.my-merchant-id-test",
          "merchant.com.my-merchant-id-live"
        ]
      }
    ]
  ]
```

Sorry, this option is not documented. 😅
Will look into improving that.

> Have you seen clients manage this by maintaining two separate apps (one for production connected to Adyen’s production environment, and another for internal use with the development environment)?

Our SDK is agnostic to API environment and everything can be set dynamically.

**Comment by vanGalilea** [comment]
Lovely, and it'll be great if you'd be able to add this to some advanced section in your docs 🙌🏻
