### ISSUE TITLE
PayConiq by Bancontact Payment Method not Working

### ISSUE THREAD

**Issue by iyanushow** [Adyen/adyen-react-native#549]
**Describe the bug**
When testing a payment method `Payconiq by Bancontact`, everything runs smoothly, and the webview opens but the screen is empty and the payment page isn't loaded (see recording)

**To Reproduce**
1. Go to checkout
2. Select `Payconiq by Bancontact` payment method
3. Try to complete payment

**Expected behavior**
The payment screen should load in webview to allow user complete payment

**Screenshots**

https://github.com/user-attachments/assets/70131146-4bb1-4d58-a732-60c163bcb1a3

**Smartphone (please complete the following information):**
 - Device: Google Pixel 8 Pro (Simulator)
 - OS: Android (API 34)
 - Browser Chrome
 - Version 2.4.1

**Comment by descorp** [comment]
Hey @iyanushow 

This is TEST environment, right?
Do you have a [Payconiq test App](https://developer.payconiq.com/online-payments-dock/#merchant-portal) installed?

**Comment by descorp** [comment]
Hey @iyanushow 

Were you able to resolve this issue?

**Comment by iyanushow** [comment]
Hi @descorp, not entirely
But it appears to be more on the payconiq app. 
Thank you

**Comment by descorp** [comment]
If possible - it is always a good idea to make a penny test on LIVE. 
In my experience, test environments of payment methods are not always providing adequate experience, unfortunately.

**Comment by iyanushow** [comment]
> If possible - it is always a good idea to make a penny test on LIVE. In my experience, test environments of payment methods are not always providing adequate experience, unfortunately.

Yeah, that works as well 
Thank you
