### ISSUE TITLE
Stored payments not showing in DropIn

### ISSUE THREAD

**Issue by patrikmolnar** [Adyen/adyen-react-native#554]
**Describe the bug**
Stored payments are not showing up in the DropIn component. 

Here's an example of what's being passed into the Adyen Context:
```json
  "storedPaymentMethods": [
    {
      "brand": "visa",
      "expiryMonth": "**",
      "expiryYear": "****",
      "holderName": "dave",
      "id": "CL4HZKKZP45JFH65",
      "lastFour": "****",
      "name": "VISA",
      "networkTxReference": "47*********4915",
      "supportedShopperInteractions": [
        "ContAuth"
      ],
      "type": "scheme"
    }
  ]
```

I pass the `paymentMethods` response as it is and the supported methods show up just fine.

**Expected behavior**
Saved payment methods to show up in the list

**Screenshots**
<img width="366" alt="Screenshot 2024-11-21 at 12 35 54" src="https://github.com/user-attachments/assets/d9760ce1-3750-4c18-b26b-acb846c1b991">

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Simulator
 
**Additional context**
We're using version `@adyen/react-native: 1.1.0` and `react-native: 0.71.19`

**Comment by patrikmolnar** [comment]
FYI, I've managed to upgrade the library to `2.2.0` but facing the same issue.

**Comment by patrikmolnar** [comment]
Figured it out.. After investigating on the backend a bit, it seems like `recurringProcessingModel` needs to be `CardOnFile`. Closing this issue :)

**Comment by descorp** [comment]
Hey @patrikmolnar 

Indeed. This stored card has `"supportedShopperInteractions": ["ContAuth"]`, which makes it not acceptable for Ecommerce payment.
Providing a [suitable](https://help.adyen.com/knowledge/ecommerce-integrations/tokenization/how-to-choose-recurring-processing-model) `recurringProcessingModel` on your backend should correct this behavior.
