### ISSUE TITLE
iOS user don't have full view of address search in Adyen screen

### ISSUE THREAD

**Issue by ahmed-fayyaz-lebara** [Adyen/adyen-react-native#556]
**Describe the bug**
iOS user don't have full view of address search in Adyen screen. When entering address blank space is observed on bottom of screen clipping out input fields. Which effects user experience. 

**To Reproduce**
1. Use iOS device to checkout
2. Create Klarna account for new number
3. Try to input search address “tell us bit abut you page”

**Expected behavior**
All the available area should be visible with rest of fields like a standard form, No blank space should be obeserved

**Screenshots**
![ios adyen-klarna view issue](https://github.com/user-attachments/assets/e97ccff7-2119-4512-bab5-686df12e8c63)

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: iOS 18.1

**Library Version**
- 2.4.0

**Comment by descorp** [comment]
Hey @ahmed-fayyaz-lebara 

I am afraid Adyen have no control over this web page or the way it is rendered.
This issue is on Klarna side. 

I will report this to our LPM team.
From your side you can also reach out Klarna support.

**Comment by ahmed-fayyaz-lebara** [comment]
Hey @descorp 

Thanks for considering.
I will raise an issue on this klarna thread https://github.com/klarna/react-native-klarna-inapp-sdk

Issue link in klarna issue thread: https://github.com/klarna/react-native-klarna-inapp-sdk/issues/280

**Comment by descorp** [comment]
Thanks @ahmed-fayyaz-lebara 💚

I'll close this thread for now, but feel free to continue here or reopen if needed.
