### ISSUE TITLE
Cannot build Android when upgrade package from 1.1.0 to version >= 1.2.0

### ISSUE THREAD

**Issue by vlmcode** [Adyen/adyen-react-native#559]
**Describe the bug**
When I upgrade package @adyen/react-native from 1.1.0 to a version >=1.2.0, I can't build on Android no more. No problem on iOS.
I tried with versions 1.2.0, 2.4.1 and 2.5.0.
Here is the error : 
![Capture d’écran 2024-12-17 à 13 14 37](https://github.com/user-attachments/assets/b4b27e86-30b9-4fab-b984-4c5f11b632a7)

**To Reproduce**
react native: 0.72.4
compileSdkVersion = 33
targetSdkVersion = 34
kotlinVersion='1.6.10'

**Screenshots**

**Desktop**
 - OS: macOS Sonoma 14.4.1(23E224) MacBook Pro M1 Pro

Here is the full error log : 

`.../node_modules/@adyen/react-native/android/src/main/java/com/adyenreactnativesdk/configuration/CardConfigurationParser.kt: (92, 24): Class 'com.adyen.checkout.card.KCPAuthVisibility' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from .../.gradle/caches/transforms-3/b814bccb5142ec540d71c7a53dc16837/transformed/jetified-card-4.13.3-api.jar!/com/adyen/checkout/card/KCPAuthVisibility.class`

**Comment by descorp** [comment]
Hey @vlmcode 

Could you try updating kotlin version to 1.8.22 ?

**Comment by vlmcode** [comment]
Hi @descorp !
Thanks for the answer
Even after upgrading kotlin version to 1.8.22, I have this issue : 
`... node_modules/@adyen/react-native/android/src/main/java/com/adyenreactnativesdk/component/base/SessionsComponentViewModel.kt:20:43 Class 'kotlinx.coroutines.CoroutineDispatcher' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.0.0, expected version is 1.8.0.`

**Comment by descorp** [comment]
What version of Adyen React-Native SDK you are on right now?

**Comment by vlmcode** [comment]
After upgrading React Native to 0.73, I can use SDK version 2.0.1 but I cannot use any higher version
Right now my Android config is :
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "26.1.10909125"
        kotlinVersion='1.8.0'

**Comment by descorp** [comment]
For RN 0.73 you must update `kotlinVersion` inside "@react-native/gradle-plugin":
See [docs here](https://github.com/Adyen/adyen-react-native/blob/develop/docs/Compatibility.md)

> I can use SDK version 2.0.1 but I cannot use any higher version

"The binary version of its metadata is 1.8.0, expected version is 1.6.0." error stoping you to update to 2.5.0, right?

**Comment by vlmcode** [comment]
@descorp Thank you it's the solution ! 👌

**Comment by descorp** [comment]
Thanks for confirming! 💚

BTW, It should work out of the box with RN 0.74+

**Comment by descorp** [comment]
I am going to close this one for now. Feel free to continue discussion here.
