### ISSUE TITLE
Question: Android Appearance

### ISSUE THREAD

**Issue by faizan-tariq-lebara** [Adyen/adyen-react-native#563]
**Describe the bug**
i want to change the background color of the Button of the card and address lookup. but unable to change that. it's working fine with AdyenCheckout.Card.CardNumberInput

**To Reproduce**
put code in styles.xml of android code.
```

<style name="AdyenCheckout.Card.CardNumberInput" parent="AdyenCheckout.TextInputEditText">
    <!-- Attribute from base style, it's recommended to leave it as is -->
    <item name="android:hint">@string/checkout_card_number_hint</item>
    <!-- Change the background color to magenta and increase the text size -->
    <item name="android:background">#FF00FF</item>
    <item name="android:textSize">16sp</item>
</style>
```

above to change the background color is working fine for CardNumberInput.

but when i try to change the color of the button it's not working. can you help me out?

       <style name="AdyenCheckout.Button.Colored" parent="AdyenCheckout.Button.Primary">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">@dimen/primary_button_height</item>
        <item name="android:layout_marginStart">@dimen/standard_margin</item>
        <item name="android:layout_marginEnd">@dimen/standard_margin</item>
        <item name="android:focusable">false</item>
        <item name="android:focusableInTouchMode">false</item>
        <item name="android:background">#FF00FF</item>
         <item name="colorPrimary">#FF00FF</item>
    </style>

    <style name="AdyenCheckout.Button.Primary" parent="Widget.MaterialComponents.Button.UnelevatedButton">
        <item name="colorAccent">?attr/colorPrimary</item>
        <item name="android:background">#00FF00</item>
         <item name="colorPrimary">#00FF00</item>
    </style>

    <style name="AdyenCheckout.Button.Secondary" parent="Widget.MaterialComponents.Button.TextButton">
        <item name="android:textColor">?attr/colorPrimary</item>
        <item name="android:layout_marginStart">@dimen/standard_margin</item>
        <item name="android:layout_marginEnd">@dimen/standard_margin</item>
        <item name="android:background">#0045f2</item>
         <item name="colorPrimary">#0045f2</item>
    </style>
    
    i tried all of these but it's not working for background color. may be i'm passing a wrong name or parent.

**Screenshots**
<img width="330" alt="Screenshot 2024-12-24 at 16 27 19" src="https://github.com/user-attachments/assets/53ec1989-c94f-448e-9935-5eea044bd9c4" />
<img width="322" alt="Screenshot 2024-12-24 at 16 27 37" src="https://github.com/user-attachments/assets/464f15cb-c1b4-41d5-a625-bcf3da2f904d" />

**Smartphone (please complete the following information):**
 - Device: Android Emulator

Reference:
https://github.com/Adyen/adyen-android/blob/develop/docs/UI_CUSTOMIZATION.md
https://github.com/Adyen/adyen-android/blob/main/ui-core/src/main/res/values/styles.xml

**Comment by descorp** [comment]
Hey @faizantariq2 

Could you try `android:backgroundTint` instead of `colorPrimary`? 

See example [here](https://github.com/Adyen/adyen-flutter/blob/main/example/android/app/src/main/res/values/styles.xml#L19-L25)

**Comment by faizan-tariq-lebara** [comment]
thanks. working
