### ISSUE TITLE
Android Build not compilable after bete-6 Release

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#62]
**Describe the bug**
Upgraded to beta-6 release, the iOS build is working fine, but the Android build is not compilable.

**To Reproduce**
I just Upgraded the Adyen package, deleted node modules, and clean Gradle, and the build will break.

**Expected behavior**
The build should work.

**Screenshots**
![Screenshot 2022-11-01 at 3 59 53 PM](https://user-images.githubusercontent.com/18231674/199218738-aa996d9f-657b-457b-8a9c-29ac4af35dac.png)
![Screenshot 2022-11-01 at 4 00 04 PM](https://user-images.githubusercontent.com/18231674/199218782-322a774a-d21f-4a81-8d2e-335e325cc4d8.png)

**Comment by descorp** [comment]
Hey @iranaahsanali 

try `com.adyenreactnativesdk.action.ActionHandler`

Sorry for inconvenience, this is a breaking change that accidentally slipped through.
It is mentioned in [Release Notes](https://github.com/Adyen/adyen-react-native/releases/tag/1.0.0-beta.6)

**Comment by iranaahsanali** [comment]
Thanks for the update, It's working.
