### ISSUE TITLE
Unable to resolve module AdyenCheckoutEvents 

### ISSUE THREAD

**Issue by esack-n-lebara** [Adyen/adyen-react-native#63]
Upgraded the **@adyen/react-native** library version from **"1.0.0-beta.5" to "1.0.0-beta.6"**. App is getting crashed and getting the below error.

**error: Error: Unable to resolve module ./AdyenCheckoutEvents from C:\Users\esack\Documents\Lebara\storybook-mobile\node_modules\@adyen\react-native\lib\commonjs\index.js:**

**To Reproduce**
1. Upgrade the adyen library version to 1.0.0-beta.6.
2. Run the app on Android platform.
3. App will not get installed. Crash will happen.
4. See the above error

**Expected behavior**
App should not get crashed.

Screenshot: 

<img width="208" alt="image" src="https://user-images.githubusercontent.com/88027580/199705802-23e69dc6-ca46-46c7-abd7-61b1f5436105.png">

<img width="650" alt="image" src="https://user-images.githubusercontent.com/88027580/199705893-215ee5e2-029e-44ca-9bf1-9c8008fb4257.png">

**Smartphone (please complete the following information):**
 - Device: Android 9.0 Emulator(Nexus 5) - API Level 28
 - OS: Android

**Comment by descorp** [comment]
Hey @EsackNaz 

`AdyenCheckoutEvents` no longer exist, it [was moved](https://github.com/Adyen/adyen-react-native/commit/1af4484e33d28a9c4fb2d8fb06c0e2675a2b0294#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L20) to `constants.js`.

Seems like an error with installation 🤔
Can you try to delete `node_modules` and run `yarn` again?

**Comment by esack-n-lebara** [comment]
Hi @descorp , Yes i deleted the `node_modules `and `package-lock.json` and did **npm install** again. Still getting the same error on Android.

**Comment by esack-n-lebara** [comment]
@descorp ,  [npx react-native start --reset-cache](url)  worked. Issue was with the cache. Thanks.

**Comment by descorp** [comment]
Thanks a lot for confirmation @EsackNaz 💚
I myself had not time to check what is causing this issue..
