### ISSUE TITLE
PAY button gives wrong indication to the user while saving the card - Pre Authorisation 

### ISSUE THREAD

**Issue by iranaahsanali** [Adyen/adyen-react-native#64]
**Describe the bug**
Select a Credit or Debit card, and pass the amount as 0, to show the reauthorization button, but it's not working.

**Expected behavior**
If the passed amount is zero, the button shouldn't show the Pay button.

**Screenshots**
<img width="255" alt="Screenshot 2022-11-04 at 1 10 41 PM" src="https://user-images.githubusercontent.com/18231674/199924255-87613377-337f-40e7-9675-c19ebfd7df71.png">

**SDK Info**
 - Version: beta-6

**Comment by descorp** [comment]
Thanks for feedback @iranaahsanali 

Will take a look

**Comment by descorp** [comment]
Hey @iranaahsanali 

If I provide `amount` as this:

```
  amount: {
    currency: 'EUR',
    value: 0,
  }
```

It works fine on iOS:

![Screenshot 2022-11-04 at 15 16 20](https://user-images.githubusercontent.com/2648655/199996894-f95fcbf3-c23d-45fa-8133-0a2c1904d5df.png)

**Comment by descorp** [comment]
BTW, this feature is not supported on native Android SDK 🤔

**Comment by faizantariq1** [comment]
@descorp i have check on IOS( beta.7 version) it's not working. I provide the amount on config like you mentioned above and directly open the scheme from dropIn it's not working.

**Comment by descorp** [comment]
Hey @faizantariq1 

I was able to reproduce this bug.
Will investigate

**Comment by iranaahsanali** [comment]
@descorp Any Update? When can we get this fix?

**Comment by descorp** [comment]
Hi @iranaahsanali 

For iOS to apply configuration must have 3 parameters: `amount`, `currencyCode` and `countryCode`. 
We will investigate how to improve developer experience in our API and documentation

**Comment by iranaahsanali** [comment]
Thanks, @descorp, It's working after setting the countryCode param.

**Comment by esack-n-lebara** [comment]
This issue is still observed in Android. Please provide a fix for this. Thanks.

![image-20221220-120120](https://user-images.githubusercontent.com/88027580/209627922-b0c76d85-6302-430b-940b-91e3c7fc6d45.png)

**Comment by descorp** [comment]
Hey @EsackNaz 

As mentioned above, this is missing feature on Android SDK v4.
It is added to `develop` branch and going to be released on v5.

I'll keep you updated when this feature is available on React Native

**Comment by descorp** [comment]
[Documentation updated](https://docs.adyen.com/online-payments/react-native/drop-in#configure-adyen-checkout) for showing the amount on the **Pay** button.

**Comment by esack-n-lebara** [comment]
Hi @descorp , Can you please confirm whether this change got updated or not? Thanks.

> Hey @EsackNaz
> 
> As mentioned above, this is missing feature on Android SDK v4. It is added to `develop` branch and going to be released on v5.
> 
> I'll keep you updated when this feature is available on React Native

**Comment by descorp** [comment]
Hey @EsackNaz 

It wasn't updated on v4. `v5-alpha` was released, but it is not yet stable enough to use for React Native.
We will keep you posted on this.

**Comment by descorp** [comment]
This issue is fixed on v2.0.0-BETA
