### ISSUE TITLE
kcpVisibility uses addressVisibility configuration on IOS

### ISSUE THREAD

**Issue by ahmetgsu** [Adyen/adyen-react-native#68]
**Describe the bug**
`kcpVisibility` configuration uses `addressVisibility` configuration on IOS [BETA.7]. 

**Expected behavior**
`kcpVisibility` should be used instead of `addressVisibility`

**Screenshots**
![image](https://user-images.githubusercontent.com/48296634/201333019-aea6a190-993e-481a-bba7-199b700f80d0.png)

**Comment by descorp** [comment]
Hey @ahmetgsu 

thank you for the feedback!
Indeed, a silly mistake on our side

**Comment by descorp** [comment]
Fixed on [146b022](https://github.com/Adyen/adyen-react-native/commit/146b022c88a4a4c1daf690100ba50ee0714578a1)

**Comment by descorp** [comment]
**Beta-8** is released with the fix.
Please confirm it resolves the problem 💚

**Comment by ahmetgsu** [comment]
Hey @descorp,

This is not a feature we implemented on our app. I discovered that bug while I was diving deep into the code base. But I will check it as soon as possible.
