### ISSUE TITLE
Drawer is not opening when component is added within "AdyenPaymentProvider" tags

### ISSUE THREAD

**Issue by basitarshad-lebara** [Adyen/adyen-react-native#9]
**Description**
The drawer doesn't get opened when I write some code within **AdyenPaymentProvider** tags, but when I call another custom component, which exactly includes the same Button that I was trying to implement directly under AdyenPaymentProvider tags, it starts working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add **AdyenPaymentProvider** tag, try adding any <Text></Text> or <Button/> component in it.
3. Set onPress function and pass useAdyenCheckout().start('AdyenDropIn');

**Expected behaviour**
It will not open the Bottom Drawer with payment options. However, payment options are fetching successfully. 

But if you pass another component to AdyenPaymentProvider i.e <CustomButtonWrapper/>, with just a simple Button having an onPress function for opening DropIn Drawer, it will start working

This code mentioned below doesn't works:

`<AdyenPaymentProvider
      config={context.config}
      paymentMethods={context.paymentMethods}
      onSubmit={didSubmit}
      onProvide={didProvide}
      onFail={didFail}
      onComplete={didComplete}>
    <Button
      title="Open DropIn"
      disabled={paymentMethods === null}
      onPress={() => {
        console.log('Paying with AdyenDropIn');
        start('AdyenDropIn');
      }}
    />
     </AdyenPaymentProvider>`

The Code given below works:
`<AdyenPaymentProvider
      config={context.config}
      paymentMethods={context.paymentMethods}
      onSubmit={didSubmit}
      onProvide={didProvide}
      onFail={didFail}
      onComplete={didComplete}>
    <CustomDrawerWrapper/>
     </AdyenPaymentProvider>`

**Comment by descorp** [comment]
Hey @basitarshad-lebara 

Thanks for feedback!
This is indeed odd behaviour from RN. We will update our sample code and add disclaimer to it.

**Comment by basitarshad-lebara** [comment]
Thanks @descorp 
I will be waiting for this issue to get fixed

**Comment by descorp** [comment]
Hey @basitarshad-lebara 

I have updated my previous comment.
Sorry for misinformation.

**Comment by basitarshad-lebara** [comment]
Hey @descorp

thanks for getting back to me. I have tried the implementation that you shared, but it is giving me the following error**(see screenshot attached below)**. Also, I remember this was one of the errors that I got when I was trying some other approaches while trying to wrap components within **AdyenPaymentProvider** before.
Can you help me out with this? Thanks in advance!

<img width="389" alt="Screen Shot 2022-05-26 at 1 46 28 PM" src="https://user-images.githubusercontent.com/104000631/170453172-f606555a-056f-4ab4-8bcd-5401a7df1498.png">

**Comment by descorp** [comment]
Hi @basitarshad-lebara 

First of all - I would recommend to **recreate your TEST client key** and blur it on screenshots :) 
Exposing LIVE keys is a security threat and could be harmful.

About the issue - this looks like in `AdyenDropIn.open(paymentMethods, configuration)` first parameter is missing. 
Could you check if my assumption is right?

**Comment by descorp** [comment]
This is understandable.
Hope to see you back when we release a market-ready version 😁

Feel free to reach out to us at any time!
I am going to close this thread for now.

**Comment by basitarshad-lebara** [comment]
Yeah, great. Thanks!
